/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SkuUnitAnalyticsDataPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuUnitAnalyticsDataPoint{}

// SkuUnitAnalyticsDataPoint struct for SkuUnitAnalyticsDataPoint
type SkuUnitAnalyticsDataPoint struct {
	// The start of the aggregation time frame in UTC.
	StartTime time.Time `json:"startTime"`
	// The end of the aggregation time frame in UTC.
	EndTime time.Time `json:"endTime"`
	// The number of times the product or SKU was purchased.
	UnitsSold AnalyticsDataPointWithTrend `json:"unitsSold"`
	// The SKU linked to the application.
	Sku string `json:"sku"`
}

type _SkuUnitAnalyticsDataPoint SkuUnitAnalyticsDataPoint

// NewSkuUnitAnalyticsDataPoint instantiates a new SkuUnitAnalyticsDataPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildSkuUnitAnalyticsDataPoint(startTime time.Time, endTime time.Time, unitsSold AnalyticsDataPointWithTrend, sku string) *SkuUnitAnalyticsDataPoint {
	this := SkuUnitAnalyticsDataPoint{}
	this.StartTime = startTime
	this.EndTime = endTime
	this.UnitsSold = unitsSold
	this.Sku = sku
	return &this
}

// NewSkuUnitAnalyticsDataPointWithDefaults instantiates a new SkuUnitAnalyticsDataPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuUnitAnalyticsDataPointWithDefaults() *SkuUnitAnalyticsDataPoint {
	this := SkuUnitAnalyticsDataPoint{}
	return &this
}

// GetStartTime returns the StartTime field value
func (o *SkuUnitAnalyticsDataPoint) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *SkuUnitAnalyticsDataPoint) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *SkuUnitAnalyticsDataPoint) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *SkuUnitAnalyticsDataPoint) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *SkuUnitAnalyticsDataPoint) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *SkuUnitAnalyticsDataPoint) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetUnitsSold returns the UnitsSold field value
func (o *SkuUnitAnalyticsDataPoint) GetUnitsSold() AnalyticsDataPointWithTrend {
	if o == nil {
		var ret AnalyticsDataPointWithTrend
		return ret
	}

	return o.UnitsSold
}

// GetUnitsSoldOk returns a tuple with the UnitsSold field value
// and a boolean to check if the value has been set.
func (o *SkuUnitAnalyticsDataPoint) GetUnitsSoldOk() (*AnalyticsDataPointWithTrend, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnitsSold, true
}

// SetUnitsSold sets field value
func (o *SkuUnitAnalyticsDataPoint) SetUnitsSold(v AnalyticsDataPointWithTrend) {
	o.UnitsSold = v
}

// GetSku returns the Sku field value
func (o *SkuUnitAnalyticsDataPoint) GetSku() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sku
}

// GetSkuOk returns a tuple with the Sku field value
// and a boolean to check if the value has been set.
func (o *SkuUnitAnalyticsDataPoint) GetSkuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sku, true
}

// SetSku sets field value
func (o *SkuUnitAnalyticsDataPoint) SetSku(v string) {
	o.Sku = v
}

func (o SkuUnitAnalyticsDataPoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuUnitAnalyticsDataPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime
	toSerialize["unitsSold"] = o.UnitsSold
	toSerialize["sku"] = o.Sku
	return toSerialize, nil
}

func (o *SkuUnitAnalyticsDataPoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"startTime",
		"endTime",
		"unitsSold",
		"sku",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkuUnitAnalyticsDataPoint := _SkuUnitAnalyticsDataPoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkuUnitAnalyticsDataPoint)

	if err != nil {
		return err
	}

	*o = SkuUnitAnalyticsDataPoint(varSkuUnitAnalyticsDataPoint)

	return err
}

type NullableSkuUnitAnalyticsDataPoint struct {
	value *SkuUnitAnalyticsDataPoint
	isSet bool
}

func (v NullableSkuUnitAnalyticsDataPoint) Get() *SkuUnitAnalyticsDataPoint {
	return v.value
}

func (v *NullableSkuUnitAnalyticsDataPoint) Set(val *SkuUnitAnalyticsDataPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuUnitAnalyticsDataPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuUnitAnalyticsDataPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableSkuUnitAnalyticsDataPoint(val *SkuUnitAnalyticsDataPoint) *NullableSkuUnitAnalyticsDataPoint {
	return &NullableSkuUnitAnalyticsDataPoint{value: val, isSet: true}
}

func (v NullableSkuUnitAnalyticsDataPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuUnitAnalyticsDataPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
