/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePriceType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePriceType{}

// UpdatePriceType struct for UpdatePriceType
type UpdatePriceType struct {
	// The name displayed in the Campaign Manager for the price type.
	Title string `json:"title"`
	// A description of the price type.
	Description *string `json:"description,omitempty"`
	// A list of the IDs of the audiences targeted by this price type.
	TargetedAudiencesIds []int64 `json:"targetedAudiencesIds"`
}

type _UpdatePriceType UpdatePriceType

// NewUpdatePriceType instantiates a new UpdatePriceType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildUpdatePriceType(title string, targetedAudiencesIds []int64) *UpdatePriceType {
	this := UpdatePriceType{}
	this.Title = title
	this.TargetedAudiencesIds = targetedAudiencesIds
	return &this
}

// NewUpdatePriceTypeWithDefaults instantiates a new UpdatePriceType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePriceTypeWithDefaults() *UpdatePriceType {
	this := UpdatePriceType{}
	return &this
}

// GetTitle returns the Title field value
func (o *UpdatePriceType) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *UpdatePriceType) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UpdatePriceType) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdatePriceType) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePriceType) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdatePriceType) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdatePriceType) SetDescription(v string) {
	o.Description = &v
}

// GetTargetedAudiencesIds returns the TargetedAudiencesIds field value
func (o *UpdatePriceType) GetTargetedAudiencesIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.TargetedAudiencesIds
}

// GetTargetedAudiencesIdsOk returns a tuple with the TargetedAudiencesIds field value
// and a boolean to check if the value has been set.
func (o *UpdatePriceType) GetTargetedAudiencesIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetedAudiencesIds, true
}

// SetTargetedAudiencesIds sets field value
func (o *UpdatePriceType) SetTargetedAudiencesIds(v []int64) {
	o.TargetedAudiencesIds = v
}

func (o UpdatePriceType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePriceType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["targetedAudiencesIds"] = o.TargetedAudiencesIds
	return toSerialize, nil
}

func (o *UpdatePriceType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"targetedAudiencesIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePriceType := _UpdatePriceType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePriceType)

	if err != nil {
		return err
	}

	*o = UpdatePriceType(varUpdatePriceType)

	return err
}

type NullableUpdatePriceType struct {
	value *UpdatePriceType
	isSet bool
}

func (v NullableUpdatePriceType) Get() *UpdatePriceType {
	return v.value
}

func (v *NullableUpdatePriceType) Set(val *UpdatePriceType) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePriceType) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePriceType) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableUpdatePriceType(val *UpdatePriceType) *NullableUpdatePriceType {
	return &NullableUpdatePriceType{value: val, isSet: true}
}

func (v NullableUpdatePriceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePriceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


