/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CardAddedDeductedPointsNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardAddedDeductedPointsNotification{}

// CardAddedDeductedPointsNotification struct for CardAddedDeductedPointsNotification
type CardAddedDeductedPointsNotification struct {
	// Loyalty card identification number.
	CardIdentifier string `json:"CardIdentifier"`
	// The name of the employee who added or deducted points.
	EmployeeName string `json:"EmployeeName"`
	// The ID of the loyalty program.
	LoyaltyProgramID int64 `json:"LoyaltyProgramID"`
	// The type of notification.
	NotificationType string `json:"NotificationType"`
	// The integration ID of the customer profile to whom points were added or deducted.
	ProfileIntegrationIDs []string `json:"ProfileIntegrationIDs"`
	// The integration ID of the session through which the points were earned or lost.
	SessionIntegrationID string `json:"SessionIntegrationID"`
	// The ID of the subledger within the loyalty program where these points were added or deducted.
	SubledgerID string `json:"SubledgerID"`
	// The notification source, that is, it indicates whether the points were added or deducted via one of the following routes:  - [The Campaign Manager](/docs/product/getting-started)  - [Management API](/management-api#tag/Loyalty)  - [Rule Engine](/docs/product/applications/evaluation-order-for-rules-and-filters)
	TypeOfChange string `json:"TypeOfChange"`
	// The ID of the employee who added or deducted points.
	UserID int64 `json:"UserID"`
	// The max amount of user profiles with whom a card can be shared. This can be set to `0` for no limit.
	UsersPerCardLimit int64 `json:"UsersPerCardLimit"`
	// The amount of added or deducted loyalty points.
	Amount float32 `json:"Amount"`
	// The expiration date for loyalty points.
	ExpiryDate *time.Time `json:"ExpiryDate,omitempty"`
	// The action (addition or deduction) made with loyalty points.
	Operation string `json:"Operation"`
	// The reason for the points addition or deduction.
	Reason string `json:"Reason"`
	// The start date for loyalty points.
	StartDate *time.Time `json:"StartDate,omitempty"`
}

type _CardAddedDeductedPointsNotification CardAddedDeductedPointsNotification

// NewCardAddedDeductedPointsNotification instantiates a new CardAddedDeductedPointsNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCardAddedDeductedPointsNotification(cardIdentifier string, employeeName string, loyaltyProgramID int64, notificationType string, profileIntegrationIDs []string, sessionIntegrationID string, subledgerID string, typeOfChange string, userID int64, usersPerCardLimit int64, amount float32, operation string, reason string) *CardAddedDeductedPointsNotification {
	this := CardAddedDeductedPointsNotification{}
	this.CardIdentifier = cardIdentifier
	this.EmployeeName = employeeName
	this.LoyaltyProgramID = loyaltyProgramID
	this.NotificationType = notificationType
	this.ProfileIntegrationIDs = profileIntegrationIDs
	this.SessionIntegrationID = sessionIntegrationID
	this.SubledgerID = subledgerID
	this.TypeOfChange = typeOfChange
	this.UserID = userID
	this.UsersPerCardLimit = usersPerCardLimit
	this.Amount = amount
	this.Operation = operation
	this.Reason = reason
	return &this
}

// NewCardAddedDeductedPointsNotificationWithDefaults instantiates a new CardAddedDeductedPointsNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardAddedDeductedPointsNotificationWithDefaults() *CardAddedDeductedPointsNotification {
	this := CardAddedDeductedPointsNotification{}
	return &this
}

// GetCardIdentifier returns the CardIdentifier field value
func (o *CardAddedDeductedPointsNotification) GetCardIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardIdentifier
}

// GetCardIdentifierOk returns a tuple with the CardIdentifier field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetCardIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardIdentifier, true
}

// SetCardIdentifier sets field value
func (o *CardAddedDeductedPointsNotification) SetCardIdentifier(v string) {
	o.CardIdentifier = v
}

// GetEmployeeName returns the EmployeeName field value
func (o *CardAddedDeductedPointsNotification) GetEmployeeName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmployeeName
}

// GetEmployeeNameOk returns a tuple with the EmployeeName field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetEmployeeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmployeeName, true
}

// SetEmployeeName sets field value
func (o *CardAddedDeductedPointsNotification) SetEmployeeName(v string) {
	o.EmployeeName = v
}

// GetLoyaltyProgramID returns the LoyaltyProgramID field value
func (o *CardAddedDeductedPointsNotification) GetLoyaltyProgramID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LoyaltyProgramID
}

// GetLoyaltyProgramIDOk returns a tuple with the LoyaltyProgramID field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetLoyaltyProgramIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoyaltyProgramID, true
}

// SetLoyaltyProgramID sets field value
func (o *CardAddedDeductedPointsNotification) SetLoyaltyProgramID(v int64) {
	o.LoyaltyProgramID = v
}

// GetNotificationType returns the NotificationType field value
func (o *CardAddedDeductedPointsNotification) GetNotificationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationType
}

// GetNotificationTypeOk returns a tuple with the NotificationType field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetNotificationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationType, true
}

// SetNotificationType sets field value
func (o *CardAddedDeductedPointsNotification) SetNotificationType(v string) {
	o.NotificationType = v
}

// GetProfileIntegrationIDs returns the ProfileIntegrationIDs field value
func (o *CardAddedDeductedPointsNotification) GetProfileIntegrationIDs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ProfileIntegrationIDs
}

// GetProfileIntegrationIDsOk returns a tuple with the ProfileIntegrationIDs field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetProfileIntegrationIDsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfileIntegrationIDs, true
}

// SetProfileIntegrationIDs sets field value
func (o *CardAddedDeductedPointsNotification) SetProfileIntegrationIDs(v []string) {
	o.ProfileIntegrationIDs = v
}

// GetSessionIntegrationID returns the SessionIntegrationID field value
func (o *CardAddedDeductedPointsNotification) GetSessionIntegrationID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionIntegrationID
}

// GetSessionIntegrationIDOk returns a tuple with the SessionIntegrationID field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetSessionIntegrationIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionIntegrationID, true
}

// SetSessionIntegrationID sets field value
func (o *CardAddedDeductedPointsNotification) SetSessionIntegrationID(v string) {
	o.SessionIntegrationID = v
}

// GetSubledgerID returns the SubledgerID field value
func (o *CardAddedDeductedPointsNotification) GetSubledgerID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubledgerID
}

// GetSubledgerIDOk returns a tuple with the SubledgerID field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetSubledgerIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubledgerID, true
}

// SetSubledgerID sets field value
func (o *CardAddedDeductedPointsNotification) SetSubledgerID(v string) {
	o.SubledgerID = v
}

// GetTypeOfChange returns the TypeOfChange field value
func (o *CardAddedDeductedPointsNotification) GetTypeOfChange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeOfChange
}

// GetTypeOfChangeOk returns a tuple with the TypeOfChange field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetTypeOfChangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeOfChange, true
}

// SetTypeOfChange sets field value
func (o *CardAddedDeductedPointsNotification) SetTypeOfChange(v string) {
	o.TypeOfChange = v
}

// GetUserID returns the UserID field value
func (o *CardAddedDeductedPointsNotification) GetUserID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserID
}

// GetUserIDOk returns a tuple with the UserID field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetUserIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserID, true
}

// SetUserID sets field value
func (o *CardAddedDeductedPointsNotification) SetUserID(v int64) {
	o.UserID = v
}

// GetUsersPerCardLimit returns the UsersPerCardLimit field value
func (o *CardAddedDeductedPointsNotification) GetUsersPerCardLimit() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UsersPerCardLimit
}

// GetUsersPerCardLimitOk returns a tuple with the UsersPerCardLimit field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetUsersPerCardLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsersPerCardLimit, true
}

// SetUsersPerCardLimit sets field value
func (o *CardAddedDeductedPointsNotification) SetUsersPerCardLimit(v int64) {
	o.UsersPerCardLimit = v
}

// GetAmount returns the Amount field value
func (o *CardAddedDeductedPointsNotification) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CardAddedDeductedPointsNotification) SetAmount(v float32) {
	o.Amount = v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *CardAddedDeductedPointsNotification) GetExpiryDate() time.Time {
	if o == nil || IsNil(o.ExpiryDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetExpiryDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiryDate) {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *CardAddedDeductedPointsNotification) HasExpiryDate() bool {
	if o != nil && !IsNil(o.ExpiryDate) {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given time.Time and assigns it to the ExpiryDate field.
func (o *CardAddedDeductedPointsNotification) SetExpiryDate(v time.Time) {
	o.ExpiryDate = &v
}

// GetOperation returns the Operation field value
func (o *CardAddedDeductedPointsNotification) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *CardAddedDeductedPointsNotification) SetOperation(v string) {
	o.Operation = v
}

// GetReason returns the Reason field value
func (o *CardAddedDeductedPointsNotification) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CardAddedDeductedPointsNotification) SetReason(v string) {
	o.Reason = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *CardAddedDeductedPointsNotification) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardAddedDeductedPointsNotification) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *CardAddedDeductedPointsNotification) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *CardAddedDeductedPointsNotification) SetStartDate(v time.Time) {
	o.StartDate = &v
}

func (o CardAddedDeductedPointsNotification) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardAddedDeductedPointsNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["CardIdentifier"] = o.CardIdentifier
	toSerialize["EmployeeName"] = o.EmployeeName
	toSerialize["LoyaltyProgramID"] = o.LoyaltyProgramID
	toSerialize["NotificationType"] = o.NotificationType
	toSerialize["ProfileIntegrationIDs"] = o.ProfileIntegrationIDs
	toSerialize["SessionIntegrationID"] = o.SessionIntegrationID
	toSerialize["SubledgerID"] = o.SubledgerID
	toSerialize["TypeOfChange"] = o.TypeOfChange
	toSerialize["UserID"] = o.UserID
	toSerialize["UsersPerCardLimit"] = o.UsersPerCardLimit
	toSerialize["Amount"] = o.Amount
	if !IsNil(o.ExpiryDate) {
		toSerialize["ExpiryDate"] = o.ExpiryDate
	}
	toSerialize["Operation"] = o.Operation
	toSerialize["Reason"] = o.Reason
	if !IsNil(o.StartDate) {
		toSerialize["StartDate"] = o.StartDate
	}
	return toSerialize, nil
}

func (o *CardAddedDeductedPointsNotification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"CardIdentifier",
		"EmployeeName",
		"LoyaltyProgramID",
		"NotificationType",
		"ProfileIntegrationIDs",
		"SessionIntegrationID",
		"SubledgerID",
		"TypeOfChange",
		"UserID",
		"UsersPerCardLimit",
		"Amount",
		"Operation",
		"Reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCardAddedDeductedPointsNotification := _CardAddedDeductedPointsNotification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCardAddedDeductedPointsNotification)

	if err != nil {
		return err
	}

	*o = CardAddedDeductedPointsNotification(varCardAddedDeductedPointsNotification)

	return err
}

type NullableCardAddedDeductedPointsNotification struct {
	value *CardAddedDeductedPointsNotification
	isSet bool
}

func (v NullableCardAddedDeductedPointsNotification) Get() *CardAddedDeductedPointsNotification {
	return v.value
}

func (v *NullableCardAddedDeductedPointsNotification) Set(val *CardAddedDeductedPointsNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableCardAddedDeductedPointsNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableCardAddedDeductedPointsNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCardAddedDeductedPointsNotification(val *CardAddedDeductedPointsNotification) *NullableCardAddedDeductedPointsNotification {
	return &NullableCardAddedDeductedPointsNotification{value: val, isSet: true}
}

func (v NullableCardAddedDeductedPointsNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardAddedDeductedPointsNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
