/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewPassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewPassword{}

// NewPassword struct for NewPassword
type NewPassword struct {
	// The new password for your account.
	Password string `json:"password"`
	ResetToken string `json:"resetToken"`
}

type _NewPassword NewPassword

// NewNewPassword instantiates a new NewPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildNewPassword(password string, resetToken string) *NewPassword {
	this := NewPassword{}
	this.Password = password
	this.ResetToken = resetToken
	return &this
}

// NewNewPasswordWithDefaults instantiates a new NewPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewPasswordWithDefaults() *NewPassword {
	this := NewPassword{}
	return &this
}

// GetPassword returns the Password field value
func (o *NewPassword) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *NewPassword) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *NewPassword) SetPassword(v string) {
	o.Password = v
}

// GetResetToken returns the ResetToken field value
func (o *NewPassword) GetResetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResetToken
}

// GetResetTokenOk returns a tuple with the ResetToken field value
// and a boolean to check if the value has been set.
func (o *NewPassword) GetResetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResetToken, true
}

// SetResetToken sets field value
func (o *NewPassword) SetResetToken(v string) {
	o.ResetToken = v
}

func (o NewPassword) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewPassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	toSerialize["resetToken"] = o.ResetToken
	return toSerialize, nil
}

func (o *NewPassword) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
		"resetToken",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewPassword := _NewPassword{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewPassword)

	if err != nil {
		return err
	}

	*o = NewPassword(varNewPassword)

	return err
}

type NullableNewPassword struct {
	value *NewPassword
	isSet bool
}

func (v NullableNewPassword) Get() *NewPassword {
	return v.value
}

func (v *NullableNewPassword) Set(val *NewPassword) {
	v.value = val
	v.isSet = true
}

func (v NullableNewPassword) IsSet() bool {
	return v.isSet
}

func (v *NullableNewPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableNewPassword(val *NewPassword) *NullableNewPassword {
	return &NullableNewPassword{value: val, isSet: true}
}

func (v NullableNewPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


