/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the GiveawayPoolReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GiveawayPoolReference{}

// GiveawayPoolReference struct for GiveawayPoolReference
type GiveawayPoolReference struct {
	// The unique identifier of the giveaway pool.
	Id int64 `json:"id"`
	// The display name of the giveaway pool.
	Name                 string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _GiveawayPoolReference GiveawayPoolReference

// NewGiveawayPoolReference instantiates a new GiveawayPoolReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildGiveawayPoolReference(id int64, name string) *GiveawayPoolReference {
	this := GiveawayPoolReference{}
	this.Id = id
	this.Name = name
	return &this
}

// NewGiveawayPoolReferenceWithDefaults instantiates a new GiveawayPoolReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGiveawayPoolReferenceWithDefaults() *GiveawayPoolReference {
	this := GiveawayPoolReference{}
	return &this
}

// GetId returns the Id field value
func (o *GiveawayPoolReference) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GiveawayPoolReference) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GiveawayPoolReference) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GiveawayPoolReference) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GiveawayPoolReference) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GiveawayPoolReference) SetName(v string) {
	o.Name = v
}

func (o GiveawayPoolReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GiveawayPoolReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GiveawayPoolReference) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGiveawayPoolReference := _GiveawayPoolReference{}

	err = json.Unmarshal(data, &varGiveawayPoolReference)

	if err != nil {
		return err
	}

	*o = GiveawayPoolReference(varGiveawayPoolReference)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGiveawayPoolReference struct {
	value *GiveawayPoolReference
	isSet bool
}

func (v NullableGiveawayPoolReference) Get() *GiveawayPoolReference {
	return v.value
}

func (v *NullableGiveawayPoolReference) Set(val *GiveawayPoolReference) {
	v.value = val
	v.isSet = true
}

func (v NullableGiveawayPoolReference) IsSet() bool {
	return v.isSet
}

func (v *NullableGiveawayPoolReference) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableGiveawayPoolReference(val *GiveawayPoolReference) *NullableGiveawayPoolReference {
	return &NullableGiveawayPoolReference{value: val, isSet: true}
}

func (v NullableGiveawayPoolReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGiveawayPoolReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
