/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the ReverseSelectorStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReverseSelectorStep{}

// ReverseSelectorStep Reverses the order of the items.
type ReverseSelectorStep struct {
	// A step discriminator of type `reverse`.
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _ReverseSelectorStep ReverseSelectorStep

// NewReverseSelectorStep instantiates a new ReverseSelectorStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildReverseSelectorStep(type_ string) *ReverseSelectorStep {
	this := ReverseSelectorStep{}
	this.Type = type_
	return &this
}

// NewReverseSelectorStepWithDefaults instantiates a new ReverseSelectorStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReverseSelectorStepWithDefaults() *ReverseSelectorStep {
	this := ReverseSelectorStep{}
	return &this
}

// GetType returns the Type field value
func (o *ReverseSelectorStep) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReverseSelectorStep) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReverseSelectorStep) SetType(v string) {
	o.Type = v
}

func (o ReverseSelectorStep) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReverseSelectorStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReverseSelectorStep) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReverseSelectorStep := _ReverseSelectorStep{}

	err = json.Unmarshal(data, &varReverseSelectorStep)

	if err != nil {
		return err
	}

	*o = ReverseSelectorStep(varReverseSelectorStep)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReverseSelectorStep struct {
	value *ReverseSelectorStep
	isSet bool
}

func (v NullableReverseSelectorStep) Get() *ReverseSelectorStep {
	return v.value
}

func (v *NullableReverseSelectorStep) Set(val *ReverseSelectorStep) {
	v.value = val
	v.isSet = true
}

func (v NullableReverseSelectorStep) IsSet() bool {
	return v.isSet
}

func (v *NullableReverseSelectorStep) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableReverseSelectorStep(val *ReverseSelectorStep) *NullableReverseSelectorStep {
	return &NullableReverseSelectorStep{value: val, isSet: true}
}

func (v NullableReverseSelectorStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReverseSelectorStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
