/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AsyncCouponDeletionJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AsyncCouponDeletionJobResponse{}

// AsyncCouponDeletionJobResponse struct for AsyncCouponDeletionJobResponse
type AsyncCouponDeletionJobResponse struct {
	// Unique ID for this entity. Not to be confused with the Integration ID, which is set by your integration layer and used in most endpoints.
	Id int64 `json:"id"`
}

type _AsyncCouponDeletionJobResponse AsyncCouponDeletionJobResponse

// NewAsyncCouponDeletionJobResponse instantiates a new AsyncCouponDeletionJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildAsyncCouponDeletionJobResponse(id int64) *AsyncCouponDeletionJobResponse {
	this := AsyncCouponDeletionJobResponse{}
	this.Id = id
	return &this
}

// NewAsyncCouponDeletionJobResponseWithDefaults instantiates a new AsyncCouponDeletionJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAsyncCouponDeletionJobResponseWithDefaults() *AsyncCouponDeletionJobResponse {
	this := AsyncCouponDeletionJobResponse{}
	return &this
}

// GetId returns the Id field value
func (o *AsyncCouponDeletionJobResponse) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AsyncCouponDeletionJobResponse) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AsyncCouponDeletionJobResponse) SetId(v int64) {
	o.Id = v
}

func (o AsyncCouponDeletionJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AsyncCouponDeletionJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *AsyncCouponDeletionJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAsyncCouponDeletionJobResponse := _AsyncCouponDeletionJobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAsyncCouponDeletionJobResponse)

	if err != nil {
		return err
	}

	*o = AsyncCouponDeletionJobResponse(varAsyncCouponDeletionJobResponse)

	return err
}

type NullableAsyncCouponDeletionJobResponse struct {
	value *AsyncCouponDeletionJobResponse
	isSet bool
}

func (v NullableAsyncCouponDeletionJobResponse) Get() *AsyncCouponDeletionJobResponse {
	return v.value
}

func (v *NullableAsyncCouponDeletionJobResponse) Set(val *AsyncCouponDeletionJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAsyncCouponDeletionJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAsyncCouponDeletionJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableAsyncCouponDeletionJobResponse(val *AsyncCouponDeletionJobResponse) *NullableAsyncCouponDeletionJobResponse {
	return &NullableAsyncCouponDeletionJobResponse{value: val, isSet: true}
}

func (v NullableAsyncCouponDeletionJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAsyncCouponDeletionJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


