/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the AwardLoyaltyPointsBundleTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwardLoyaltyPointsBundleTarget{}

// AwardLoyaltyPointsBundleTarget Awards points based on bundle contents.
type AwardLoyaltyPointsBundleTarget struct {
	// A target discriminator of type `bundle`.
	Type string `json:"type"`
	// Name of the bundle the points target.
	Name                 string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _AwardLoyaltyPointsBundleTarget AwardLoyaltyPointsBundleTarget

// NewAwardLoyaltyPointsBundleTarget instantiates a new AwardLoyaltyPointsBundleTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildAwardLoyaltyPointsBundleTarget(type_ string, name string) *AwardLoyaltyPointsBundleTarget {
	this := AwardLoyaltyPointsBundleTarget{}
	this.Type = type_
	this.Name = name
	return &this
}

// NewAwardLoyaltyPointsBundleTargetWithDefaults instantiates a new AwardLoyaltyPointsBundleTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwardLoyaltyPointsBundleTargetWithDefaults() *AwardLoyaltyPointsBundleTarget {
	this := AwardLoyaltyPointsBundleTarget{}
	return &this
}

// GetType returns the Type field value
func (o *AwardLoyaltyPointsBundleTarget) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AwardLoyaltyPointsBundleTarget) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AwardLoyaltyPointsBundleTarget) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *AwardLoyaltyPointsBundleTarget) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AwardLoyaltyPointsBundleTarget) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AwardLoyaltyPointsBundleTarget) SetName(v string) {
	o.Name = v
}

func (o AwardLoyaltyPointsBundleTarget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwardLoyaltyPointsBundleTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AwardLoyaltyPointsBundleTarget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwardLoyaltyPointsBundleTarget := _AwardLoyaltyPointsBundleTarget{}

	err = json.Unmarshal(data, &varAwardLoyaltyPointsBundleTarget)

	if err != nil {
		return err
	}

	*o = AwardLoyaltyPointsBundleTarget(varAwardLoyaltyPointsBundleTarget)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAwardLoyaltyPointsBundleTarget struct {
	value *AwardLoyaltyPointsBundleTarget
	isSet bool
}

func (v NullableAwardLoyaltyPointsBundleTarget) Get() *AwardLoyaltyPointsBundleTarget {
	return v.value
}

func (v *NullableAwardLoyaltyPointsBundleTarget) Set(val *AwardLoyaltyPointsBundleTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableAwardLoyaltyPointsBundleTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableAwardLoyaltyPointsBundleTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableAwardLoyaltyPointsBundleTarget(val *AwardLoyaltyPointsBundleTarget) *NullableAwardLoyaltyPointsBundleTarget {
	return &NullableAwardLoyaltyPointsBundleTarget{value: val, isSet: true}
}

func (v NullableAwardLoyaltyPointsBundleTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwardLoyaltyPointsBundleTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
