/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GenerateCampaignTags type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateCampaignTags{}

// GenerateCampaignTags struct for GenerateCampaignTags
type GenerateCampaignTags struct {
	// ID of a ruleset.
	RulesetID int64 `json:"rulesetID"`
}

type _GenerateCampaignTags GenerateCampaignTags

// NewGenerateCampaignTags instantiates a new GenerateCampaignTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildGenerateCampaignTags(rulesetID int64) *GenerateCampaignTags {
	this := GenerateCampaignTags{}
	this.RulesetID = rulesetID
	return &this
}

// NewGenerateCampaignTagsWithDefaults instantiates a new GenerateCampaignTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateCampaignTagsWithDefaults() *GenerateCampaignTags {
	this := GenerateCampaignTags{}
	return &this
}

// GetRulesetID returns the RulesetID field value
func (o *GenerateCampaignTags) GetRulesetID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RulesetID
}

// GetRulesetIDOk returns a tuple with the RulesetID field value
// and a boolean to check if the value has been set.
func (o *GenerateCampaignTags) GetRulesetIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RulesetID, true
}

// SetRulesetID sets field value
func (o *GenerateCampaignTags) SetRulesetID(v int64) {
	o.RulesetID = v
}

func (o GenerateCampaignTags) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateCampaignTags) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rulesetID"] = o.RulesetID
	return toSerialize, nil
}

func (o *GenerateCampaignTags) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rulesetID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenerateCampaignTags := _GenerateCampaignTags{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenerateCampaignTags)

	if err != nil {
		return err
	}

	*o = GenerateCampaignTags(varGenerateCampaignTags)

	return err
}

type NullableGenerateCampaignTags struct {
	value *GenerateCampaignTags
	isSet bool
}

func (v NullableGenerateCampaignTags) Get() *GenerateCampaignTags {
	return v.value
}

func (v *NullableGenerateCampaignTags) Set(val *GenerateCampaignTags) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateCampaignTags) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateCampaignTags) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableGenerateCampaignTags(val *GenerateCampaignTags) *NullableGenerateCampaignTags {
	return &NullableGenerateCampaignTags{value: val, isSet: true}
}

func (v NullableGenerateCampaignTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateCampaignTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


