/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LoyaltyCardBatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoyaltyCardBatch{}

// LoyaltyCardBatch struct for LoyaltyCardBatch
type LoyaltyCardBatch struct {
	// Number of loyalty cards in the batch.
	NumberOfCards int64 `json:"numberOfCards"`
	// ID of the loyalty card batch.
	BatchId *string `json:"batchId,omitempty" validate:"regexp=^[A-Za-z0-9_-]*$"`
	// Status of the loyalty cards in the batch.
	Status           *string                `json:"status,omitempty"`
	CardCodeSettings *CodeGeneratorSettings `json:"cardCodeSettings,omitempty"`
}

type _LoyaltyCardBatch LoyaltyCardBatch

// NewLoyaltyCardBatch instantiates a new LoyaltyCardBatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildLoyaltyCardBatch(numberOfCards int64) *LoyaltyCardBatch {
	this := LoyaltyCardBatch{}
	this.NumberOfCards = numberOfCards
	var status string = "active"
	this.Status = &status
	return &this
}

// NewLoyaltyCardBatchWithDefaults instantiates a new LoyaltyCardBatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoyaltyCardBatchWithDefaults() *LoyaltyCardBatch {
	this := LoyaltyCardBatch{}
	var status string = "active"
	this.Status = &status
	return &this
}

// GetNumberOfCards returns the NumberOfCards field value
func (o *LoyaltyCardBatch) GetNumberOfCards() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NumberOfCards
}

// GetNumberOfCardsOk returns a tuple with the NumberOfCards field value
// and a boolean to check if the value has been set.
func (o *LoyaltyCardBatch) GetNumberOfCardsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumberOfCards, true
}

// SetNumberOfCards sets field value
func (o *LoyaltyCardBatch) SetNumberOfCards(v int64) {
	o.NumberOfCards = v
}

// GetBatchId returns the BatchId field value if set, zero value otherwise.
func (o *LoyaltyCardBatch) GetBatchId() string {
	if o == nil || IsNil(o.BatchId) {
		var ret string
		return ret
	}
	return *o.BatchId
}

// GetBatchIdOk returns a tuple with the BatchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoyaltyCardBatch) GetBatchIdOk() (*string, bool) {
	if o == nil || IsNil(o.BatchId) {
		return nil, false
	}
	return o.BatchId, true
}

// HasBatchId returns a boolean if a field has been set.
func (o *LoyaltyCardBatch) HasBatchId() bool {
	if o != nil && !IsNil(o.BatchId) {
		return true
	}

	return false
}

// SetBatchId gets a reference to the given string and assigns it to the BatchId field.
func (o *LoyaltyCardBatch) SetBatchId(v string) {
	o.BatchId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LoyaltyCardBatch) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoyaltyCardBatch) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LoyaltyCardBatch) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *LoyaltyCardBatch) SetStatus(v string) {
	o.Status = &v
}

// GetCardCodeSettings returns the CardCodeSettings field value if set, zero value otherwise.
func (o *LoyaltyCardBatch) GetCardCodeSettings() CodeGeneratorSettings {
	if o == nil || IsNil(o.CardCodeSettings) {
		var ret CodeGeneratorSettings
		return ret
	}
	return *o.CardCodeSettings
}

// GetCardCodeSettingsOk returns a tuple with the CardCodeSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoyaltyCardBatch) GetCardCodeSettingsOk() (*CodeGeneratorSettings, bool) {
	if o == nil || IsNil(o.CardCodeSettings) {
		return nil, false
	}
	return o.CardCodeSettings, true
}

// HasCardCodeSettings returns a boolean if a field has been set.
func (o *LoyaltyCardBatch) HasCardCodeSettings() bool {
	if o != nil && !IsNil(o.CardCodeSettings) {
		return true
	}

	return false
}

// SetCardCodeSettings gets a reference to the given CodeGeneratorSettings and assigns it to the CardCodeSettings field.
func (o *LoyaltyCardBatch) SetCardCodeSettings(v CodeGeneratorSettings) {
	o.CardCodeSettings = &v
}

func (o LoyaltyCardBatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoyaltyCardBatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["numberOfCards"] = o.NumberOfCards
	if !IsNil(o.BatchId) {
		toSerialize["batchId"] = o.BatchId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CardCodeSettings) {
		toSerialize["cardCodeSettings"] = o.CardCodeSettings
	}
	return toSerialize, nil
}

func (o *LoyaltyCardBatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"numberOfCards",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoyaltyCardBatch := _LoyaltyCardBatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoyaltyCardBatch)

	if err != nil {
		return err
	}

	*o = LoyaltyCardBatch(varLoyaltyCardBatch)

	return err
}

type NullableLoyaltyCardBatch struct {
	value *LoyaltyCardBatch
	isSet bool
}

func (v NullableLoyaltyCardBatch) Get() *LoyaltyCardBatch {
	return v.value
}

func (v *NullableLoyaltyCardBatch) Set(val *LoyaltyCardBatch) {
	v.value = val
	v.isSet = true
}

func (v NullableLoyaltyCardBatch) IsSet() bool {
	return v.isSet
}

func (v *NullableLoyaltyCardBatch) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableLoyaltyCardBatch(val *LoyaltyCardBatch) *NullableLoyaltyCardBatch {
	return &NullableLoyaltyCardBatch{value: val, isSet: true}
}

func (v NullableLoyaltyCardBatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoyaltyCardBatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
