/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TemplateLimitConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateLimitConfig{}

// TemplateLimitConfig struct for TemplateLimitConfig
type TemplateLimitConfig struct {
	// The limitable action to which this limit applies. For example: - `setDiscount` - `setDiscountEffect` - `redeemCoupon` - `createCoupon`
	Action string `json:"action"`
	// The value to set for the limit.
	Limit float32 `json:"limit"`
	// The period on which the budget limit recurs.
	Period *string `json:"period,omitempty"`
	// The entity that this limit applies to.
	Entities []string `json:"entities"`
}

type _TemplateLimitConfig TemplateLimitConfig

// NewTemplateLimitConfig instantiates a new TemplateLimitConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildTemplateLimitConfig(action string, limit float32, entities []string) *TemplateLimitConfig {
	this := TemplateLimitConfig{}
	this.Action = action
	this.Limit = limit
	this.Entities = entities
	return &this
}

// NewTemplateLimitConfigWithDefaults instantiates a new TemplateLimitConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateLimitConfigWithDefaults() *TemplateLimitConfig {
	this := TemplateLimitConfig{}
	return &this
}

// GetAction returns the Action field value
func (o *TemplateLimitConfig) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *TemplateLimitConfig) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *TemplateLimitConfig) SetAction(v string) {
	o.Action = v
}

// GetLimit returns the Limit field value
func (o *TemplateLimitConfig) GetLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *TemplateLimitConfig) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *TemplateLimitConfig) SetLimit(v float32) {
	o.Limit = v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *TemplateLimitConfig) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateLimitConfig) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *TemplateLimitConfig) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *TemplateLimitConfig) SetPeriod(v string) {
	o.Period = &v
}

// GetEntities returns the Entities field value
func (o *TemplateLimitConfig) GetEntities() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *TemplateLimitConfig) GetEntitiesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *TemplateLimitConfig) SetEntities(v []string) {
	o.Entities = v
}

func (o TemplateLimitConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateLimitConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["limit"] = o.Limit
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	toSerialize["entities"] = o.Entities
	return toSerialize, nil
}

func (o *TemplateLimitConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"limit",
		"entities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateLimitConfig := _TemplateLimitConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateLimitConfig)

	if err != nil {
		return err
	}

	*o = TemplateLimitConfig(varTemplateLimitConfig)

	return err
}

type NullableTemplateLimitConfig struct {
	value *TemplateLimitConfig
	isSet bool
}

func (v NullableTemplateLimitConfig) Get() *TemplateLimitConfig {
	return v.value
}

func (v *NullableTemplateLimitConfig) Set(val *TemplateLimitConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateLimitConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateLimitConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableTemplateLimitConfig(val *TemplateLimitConfig) *NullableTemplateLimitConfig {
	return &NullableTemplateLimitConfig{value: val, isSet: true}
}

func (v NullableTemplateLimitConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateLimitConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
