/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the WithinCheckAttributeBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WithinCheckAttributeBlock{}

// WithinCheckAttributeBlock Variant of `CheckAttributeBlock` for the `within` and `not(within)` operators, which require both a start and end value.
type WithinCheckAttributeBlock struct {
	// The range comparison operator. Must be `within` or `not(within)`.
	Operator *string `json:"operator,omitempty"`
	// The start value for the `within` operator.
	Start interface{} `json:"start"`
	// The end value for the `within` operator.
	End interface{} `json:"end"`
	// When `true`, the `start` value is included in the range for the `within` operator.
	StartInclusive *bool `json:"startInclusive,omitempty"`
	// When `true`, the `end` value is included in the range for the `within` operator.
	EndInclusive *bool `json:"endInclusive,omitempty"`
	// Indicates whether the `within` operator ignores time zones and compares the wall-clock time only. When `false`, time zones are taken into account.
	TimezoneInsensitive  *bool `json:"timezoneInsensitive,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WithinCheckAttributeBlock WithinCheckAttributeBlock

// NewWithinCheckAttributeBlock instantiates a new WithinCheckAttributeBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildWithinCheckAttributeBlock(start interface{}, end interface{}) *WithinCheckAttributeBlock {
	this := WithinCheckAttributeBlock{}
	this.Start = start
	this.End = end
	return &this
}

// NewWithinCheckAttributeBlockWithDefaults instantiates a new WithinCheckAttributeBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithinCheckAttributeBlockWithDefaults() *WithinCheckAttributeBlock {
	this := WithinCheckAttributeBlock{}
	return &this
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *WithinCheckAttributeBlock) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithinCheckAttributeBlock) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *WithinCheckAttributeBlock) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *WithinCheckAttributeBlock) SetOperator(v string) {
	o.Operator = &v
}

// GetStart returns the Start field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *WithinCheckAttributeBlock) GetStart() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WithinCheckAttributeBlock) GetStartOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *WithinCheckAttributeBlock) SetStart(v interface{}) {
	o.Start = v
}

// GetEnd returns the End field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *WithinCheckAttributeBlock) GetEnd() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WithinCheckAttributeBlock) GetEndOk() (*interface{}, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *WithinCheckAttributeBlock) SetEnd(v interface{}) {
	o.End = v
}

// GetStartInclusive returns the StartInclusive field value if set, zero value otherwise.
func (o *WithinCheckAttributeBlock) GetStartInclusive() bool {
	if o == nil || IsNil(o.StartInclusive) {
		var ret bool
		return ret
	}
	return *o.StartInclusive
}

// GetStartInclusiveOk returns a tuple with the StartInclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithinCheckAttributeBlock) GetStartInclusiveOk() (*bool, bool) {
	if o == nil || IsNil(o.StartInclusive) {
		return nil, false
	}
	return o.StartInclusive, true
}

// HasStartInclusive returns a boolean if a field has been set.
func (o *WithinCheckAttributeBlock) HasStartInclusive() bool {
	if o != nil && !IsNil(o.StartInclusive) {
		return true
	}

	return false
}

// SetStartInclusive gets a reference to the given bool and assigns it to the StartInclusive field.
func (o *WithinCheckAttributeBlock) SetStartInclusive(v bool) {
	o.StartInclusive = &v
}

// GetEndInclusive returns the EndInclusive field value if set, zero value otherwise.
func (o *WithinCheckAttributeBlock) GetEndInclusive() bool {
	if o == nil || IsNil(o.EndInclusive) {
		var ret bool
		return ret
	}
	return *o.EndInclusive
}

// GetEndInclusiveOk returns a tuple with the EndInclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithinCheckAttributeBlock) GetEndInclusiveOk() (*bool, bool) {
	if o == nil || IsNil(o.EndInclusive) {
		return nil, false
	}
	return o.EndInclusive, true
}

// HasEndInclusive returns a boolean if a field has been set.
func (o *WithinCheckAttributeBlock) HasEndInclusive() bool {
	if o != nil && !IsNil(o.EndInclusive) {
		return true
	}

	return false
}

// SetEndInclusive gets a reference to the given bool and assigns it to the EndInclusive field.
func (o *WithinCheckAttributeBlock) SetEndInclusive(v bool) {
	o.EndInclusive = &v
}

// GetTimezoneInsensitive returns the TimezoneInsensitive field value if set, zero value otherwise.
func (o *WithinCheckAttributeBlock) GetTimezoneInsensitive() bool {
	if o == nil || IsNil(o.TimezoneInsensitive) {
		var ret bool
		return ret
	}
	return *o.TimezoneInsensitive
}

// GetTimezoneInsensitiveOk returns a tuple with the TimezoneInsensitive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WithinCheckAttributeBlock) GetTimezoneInsensitiveOk() (*bool, bool) {
	if o == nil || IsNil(o.TimezoneInsensitive) {
		return nil, false
	}
	return o.TimezoneInsensitive, true
}

// HasTimezoneInsensitive returns a boolean if a field has been set.
func (o *WithinCheckAttributeBlock) HasTimezoneInsensitive() bool {
	if o != nil && !IsNil(o.TimezoneInsensitive) {
		return true
	}

	return false
}

// SetTimezoneInsensitive gets a reference to the given bool and assigns it to the TimezoneInsensitive field.
func (o *WithinCheckAttributeBlock) SetTimezoneInsensitive(v bool) {
	o.TimezoneInsensitive = &v
}

func (o WithinCheckAttributeBlock) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WithinCheckAttributeBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if o.Start != nil {
		toSerialize["start"] = o.Start
	}
	if o.End != nil {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.StartInclusive) {
		toSerialize["startInclusive"] = o.StartInclusive
	}
	if !IsNil(o.EndInclusive) {
		toSerialize["endInclusive"] = o.EndInclusive
	}
	if !IsNil(o.TimezoneInsensitive) {
		toSerialize["timezoneInsensitive"] = o.TimezoneInsensitive
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WithinCheckAttributeBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start",
		"end",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWithinCheckAttributeBlock := _WithinCheckAttributeBlock{}

	err = json.Unmarshal(data, &varWithinCheckAttributeBlock)

	if err != nil {
		return err
	}

	*o = WithinCheckAttributeBlock(varWithinCheckAttributeBlock)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operator")
		delete(additionalProperties, "start")
		delete(additionalProperties, "end")
		delete(additionalProperties, "startInclusive")
		delete(additionalProperties, "endInclusive")
		delete(additionalProperties, "timezoneInsensitive")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWithinCheckAttributeBlock struct {
	value *WithinCheckAttributeBlock
	isSet bool
}

func (v NullableWithinCheckAttributeBlock) Get() *WithinCheckAttributeBlock {
	return v.value
}

func (v *NullableWithinCheckAttributeBlock) Set(val *WithinCheckAttributeBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableWithinCheckAttributeBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableWithinCheckAttributeBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableWithinCheckAttributeBlock(val *WithinCheckAttributeBlock) *NullableWithinCheckAttributeBlock {
	return &NullableWithinCheckAttributeBlock{value: val, isSet: true}
}

func (v NullableWithinCheckAttributeBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithinCheckAttributeBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
