/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the CatalogActionPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogActionPatch{}

// CatalogActionPatch Updates an item in the catalog.
type CatalogActionPatch struct {
	// A catalog sync action discriminator of type `PATCH`.
	Type string `json:"type"`
	// The payload of sync action.
	Payload              PatchItemCatalogAction `json:"payload"`
	AdditionalProperties map[string]interface{}
}

type _CatalogActionPatch CatalogActionPatch

// NewCatalogActionPatch instantiates a new CatalogActionPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCatalogActionPatch(type_ string, payload PatchItemCatalogAction) *CatalogActionPatch {
	this := CatalogActionPatch{}
	this.Type = type_
	this.Payload = payload
	return &this
}

// NewCatalogActionPatchWithDefaults instantiates a new CatalogActionPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogActionPatchWithDefaults() *CatalogActionPatch {
	this := CatalogActionPatch{}
	return &this
}

// GetType returns the Type field value
func (o *CatalogActionPatch) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CatalogActionPatch) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CatalogActionPatch) SetType(v string) {
	o.Type = v
}

// GetPayload returns the Payload field value
func (o *CatalogActionPatch) GetPayload() PatchItemCatalogAction {
	if o == nil {
		var ret PatchItemCatalogAction
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *CatalogActionPatch) GetPayloadOk() (*PatchItemCatalogAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *CatalogActionPatch) SetPayload(v PatchItemCatalogAction) {
	o.Payload = v
}

func (o CatalogActionPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogActionPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["payload"] = o.Payload

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CatalogActionPatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"payload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogActionPatch := _CatalogActionPatch{}

	err = json.Unmarshal(data, &varCatalogActionPatch)

	if err != nil {
		return err
	}

	*o = CatalogActionPatch(varCatalogActionPatch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "payload")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalogActionPatch struct {
	value *CatalogActionPatch
	isSet bool
}

func (v NullableCatalogActionPatch) Get() *CatalogActionPatch {
	return v.value
}

func (v *NullableCatalogActionPatch) Set(val *CatalogActionPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogActionPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogActionPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCatalogActionPatch(val *CatalogActionPatch) *NullableCatalogActionPatch {
	return &NullableCatalogActionPatch{value: val, isSet: true}
}

func (v NullableCatalogActionPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogActionPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
