/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FuncArgDef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FuncArgDef{}

// FuncArgDef struct for FuncArgDef
type FuncArgDef struct {
	// The type of value this argument expects.
	Type string `json:"type"`
	// A campaigner-friendly description of the argument, this will also be shown in the rule editor.
	Description *string `json:"description,omitempty"`
}

type _FuncArgDef FuncArgDef

// NewFuncArgDef instantiates a new FuncArgDef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildFuncArgDef(type_ string) *FuncArgDef {
	this := FuncArgDef{}
	this.Type = type_
	return &this
}

// NewFuncArgDefWithDefaults instantiates a new FuncArgDef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFuncArgDefWithDefaults() *FuncArgDef {
	this := FuncArgDef{}
	return &this
}

// GetType returns the Type field value
func (o *FuncArgDef) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FuncArgDef) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FuncArgDef) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FuncArgDef) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FuncArgDef) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FuncArgDef) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FuncArgDef) SetDescription(v string) {
	o.Description = &v
}

func (o FuncArgDef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FuncArgDef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *FuncArgDef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFuncArgDef := _FuncArgDef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFuncArgDef)

	if err != nil {
		return err
	}

	*o = FuncArgDef(varFuncArgDef)

	return err
}

type NullableFuncArgDef struct {
	value *FuncArgDef
	isSet bool
}

func (v NullableFuncArgDef) Get() *FuncArgDef {
	return v.value
}

func (v *NullableFuncArgDef) Set(val *FuncArgDef) {
	v.value = val
	v.isSet = true
}

func (v NullableFuncArgDef) IsSet() bool {
	return v.isSet
}

func (v *NullableFuncArgDef) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableFuncArgDef(val *FuncArgDef) *NullableFuncArgDef {
	return &NullableFuncArgDef{value: val, isSet: true}
}

func (v NullableFuncArgDef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFuncArgDef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
