/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CampaignSetNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignSetNode{}

// CampaignSetNode struct for CampaignSetNode
type CampaignSetNode struct {
	Type string `json:"type"`
}

type _CampaignSetNode CampaignSetNode

// NewCampaignSetNode instantiates a new CampaignSetNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCampaignSetNode(type_ string) *CampaignSetNode {
	this := CampaignSetNode{}
	this.Type = type_
	return &this
}

// NewCampaignSetNodeWithDefaults instantiates a new CampaignSetNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignSetNodeWithDefaults() *CampaignSetNode {
	this := CampaignSetNode{}
	return &this
}

// GetType returns the Type field value
func (o *CampaignSetNode) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CampaignSetNode) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CampaignSetNode) SetType(v string) {
	o.Type = v
}

func (o CampaignSetNode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignSetNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *CampaignSetNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaignSetNode := _CampaignSetNode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCampaignSetNode)

	if err != nil {
		return err
	}

	*o = CampaignSetNode(varCampaignSetNode)

	return err
}

type NullableCampaignSetNode struct {
	value *CampaignSetNode
	isSet bool
}

func (v NullableCampaignSetNode) Get() *CampaignSetNode {
	return v.value
}

func (v *NullableCampaignSetNode) Set(val *CampaignSetNode) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignSetNode) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignSetNode) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCampaignSetNode(val *CampaignSetNode) *NullableCampaignSetNode {
	return &NullableCampaignSetNode{value: val, isSet: true}
}

func (v NullableCampaignSetNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignSetNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
