/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Store type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Store{}

// Store struct for Store
type Store struct {
	// The internal ID of this entity.
	Id int64 `json:"id"`
	// The time this entity was created.
	Created time.Time `json:"created"`
	// The name of the store.
	Name string `json:"name"`
	// The description of the store.
	Description string `json:"description"`
	// The attributes of the store.
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	// The integration ID of the store. You choose this ID when you create a store.  **Note**: You cannot edit the `integrationId` after the store has been created.
	IntegrationId string `json:"integrationId"`
	// The ID of the Application that owns this entity.
	ApplicationId int64 `json:"applicationId"`
	// Timestamp of the most recent update on this entity.
	Updated time.Time `json:"updated"`
	// A list of IDs of the campaigns that are linked with current store.
	LinkedCampaignIds []int64 `json:"linkedCampaignIds,omitempty"`
}

type _Store Store

// NewStore instantiates a new Store object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildStore(id int64, created time.Time, name string, description string, integrationId string, applicationId int64, updated time.Time) *Store {
	this := Store{}
	this.Id = id
	this.Created = created
	this.Name = name
	this.Description = description
	this.IntegrationId = integrationId
	this.ApplicationId = applicationId
	this.Updated = updated
	return &this
}

// NewStoreWithDefaults instantiates a new Store object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreWithDefaults() *Store {
	this := Store{}
	return &this
}

// GetId returns the Id field value
func (o *Store) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Store) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Store) SetId(v int64) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *Store) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Store) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Store) SetCreated(v time.Time) {
	o.Created = v
}

// GetName returns the Name field value
func (o *Store) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Store) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Store) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *Store) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Store) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Store) SetDescription(v string) {
	o.Description = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *Store) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Store) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Store) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *Store) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *Store) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *Store) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *Store) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetApplicationId returns the ApplicationId field value
func (o *Store) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *Store) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *Store) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetUpdated returns the Updated field value
func (o *Store) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *Store) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *Store) SetUpdated(v time.Time) {
	o.Updated = v
}

// GetLinkedCampaignIds returns the LinkedCampaignIds field value if set, zero value otherwise.
func (o *Store) GetLinkedCampaignIds() []int64 {
	if o == nil || IsNil(o.LinkedCampaignIds) {
		var ret []int64
		return ret
	}
	return o.LinkedCampaignIds
}

// GetLinkedCampaignIdsOk returns a tuple with the LinkedCampaignIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Store) GetLinkedCampaignIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.LinkedCampaignIds) {
		return nil, false
	}
	return o.LinkedCampaignIds, true
}

// HasLinkedCampaignIds returns a boolean if a field has been set.
func (o *Store) HasLinkedCampaignIds() bool {
	if o != nil && !IsNil(o.LinkedCampaignIds) {
		return true
	}

	return false
}

// SetLinkedCampaignIds gets a reference to the given []int64 and assigns it to the LinkedCampaignIds field.
func (o *Store) SetLinkedCampaignIds(v []int64) {
	o.LinkedCampaignIds = v
}

func (o Store) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Store) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created"] = o.Created
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	toSerialize["integrationId"] = o.IntegrationId
	toSerialize["applicationId"] = o.ApplicationId
	toSerialize["updated"] = o.Updated
	if !IsNil(o.LinkedCampaignIds) {
		toSerialize["linkedCampaignIds"] = o.LinkedCampaignIds
	}
	return toSerialize, nil
}

func (o *Store) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created",
		"name",
		"description",
		"integrationId",
		"applicationId",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStore := _Store{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStore)

	if err != nil {
		return err
	}

	*o = Store(varStore)

	return err
}

type NullableStore struct {
	value *Store
	isSet bool
}

func (v NullableStore) Get() *Store {
	return v.value
}

func (v *NullableStore) Set(val *Store) {
	v.value = val
	v.isSet = true
}

func (v NullableStore) IsSet() bool {
	return v.isSet
}

func (v *NullableStore) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableStore(val *Store) *NullableStore {
	return &NullableStore{value: val, isSet: true}
}

func (v NullableStore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
