/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PriceHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceHistoryResponse{}

// PriceHistoryResponse struct for PriceHistoryResponse
type PriceHistoryResponse struct {
	// The SKU of the item for which historical prices should be retrieved.
	Sku     string    `json:"sku"`
	History []History `json:"history"`
}

type _PriceHistoryResponse PriceHistoryResponse

// NewPriceHistoryResponse instantiates a new PriceHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildPriceHistoryResponse(sku string, history []History) *PriceHistoryResponse {
	this := PriceHistoryResponse{}
	this.Sku = sku
	this.History = history
	return &this
}

// NewPriceHistoryResponseWithDefaults instantiates a new PriceHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceHistoryResponseWithDefaults() *PriceHistoryResponse {
	this := PriceHistoryResponse{}
	return &this
}

// GetSku returns the Sku field value
func (o *PriceHistoryResponse) GetSku() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sku
}

// GetSkuOk returns a tuple with the Sku field value
// and a boolean to check if the value has been set.
func (o *PriceHistoryResponse) GetSkuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sku, true
}

// SetSku sets field value
func (o *PriceHistoryResponse) SetSku(v string) {
	o.Sku = v
}

// GetHistory returns the History field value
func (o *PriceHistoryResponse) GetHistory() []History {
	if o == nil {
		var ret []History
		return ret
	}

	return o.History
}

// GetHistoryOk returns a tuple with the History field value
// and a boolean to check if the value has been set.
func (o *PriceHistoryResponse) GetHistoryOk() ([]History, bool) {
	if o == nil {
		return nil, false
	}
	return o.History, true
}

// SetHistory sets field value
func (o *PriceHistoryResponse) SetHistory(v []History) {
	o.History = v
}

func (o PriceHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sku"] = o.Sku
	toSerialize["history"] = o.History
	return toSerialize, nil
}

func (o *PriceHistoryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sku",
		"history",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPriceHistoryResponse := _PriceHistoryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPriceHistoryResponse)

	if err != nil {
		return err
	}

	*o = PriceHistoryResponse(varPriceHistoryResponse)

	return err
}

type NullablePriceHistoryResponse struct {
	value *PriceHistoryResponse
	isSet bool
}

func (v NullablePriceHistoryResponse) Get() *PriceHistoryResponse {
	return v.value
}

func (v *NullablePriceHistoryResponse) Set(val *PriceHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullablePriceHistoryResponse(val *PriceHistoryResponse) *NullablePriceHistoryResponse {
	return &NullablePriceHistoryResponse{value: val, isSet: true}
}

func (v NullablePriceHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
