/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TierWillDowngradeNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TierWillDowngradeNotification{}

// TierWillDowngradeNotification struct for TierWillDowngradeNotification
type TierWillDowngradeNotification struct {
	TotalResultSize int64 `json:"TotalResultSize"`
	// The array of upcoming tier downgrade notifications.
	Data []TierWillDowngradeData `json:"Data"`
	// The type of notification.
	NotificationType string `json:"NotificationType"`
}

type _TierWillDowngradeNotification TierWillDowngradeNotification

// NewTierWillDowngradeNotification instantiates a new TierWillDowngradeNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTierWillDowngradeNotification(totalResultSize int64, data []TierWillDowngradeData, notificationType string) *TierWillDowngradeNotification {
	this := TierWillDowngradeNotification{}
	this.TotalResultSize = totalResultSize
	this.Data = data
	this.NotificationType = notificationType
	return &this
}

// NewTierWillDowngradeNotificationWithDefaults instantiates a new TierWillDowngradeNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTierWillDowngradeNotificationWithDefaults() *TierWillDowngradeNotification {
	this := TierWillDowngradeNotification{}
	return &this
}

// GetTotalResultSize returns the TotalResultSize field value
func (o *TierWillDowngradeNotification) GetTotalResultSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalResultSize
}

// GetTotalResultSizeOk returns a tuple with the TotalResultSize field value
// and a boolean to check if the value has been set.
func (o *TierWillDowngradeNotification) GetTotalResultSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalResultSize, true
}

// SetTotalResultSize sets field value
func (o *TierWillDowngradeNotification) SetTotalResultSize(v int64) {
	o.TotalResultSize = v
}

// GetData returns the Data field value
func (o *TierWillDowngradeNotification) GetData() []TierWillDowngradeData {
	if o == nil {
		var ret []TierWillDowngradeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TierWillDowngradeNotification) GetDataOk() ([]TierWillDowngradeData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *TierWillDowngradeNotification) SetData(v []TierWillDowngradeData) {
	o.Data = v
}

// GetNotificationType returns the NotificationType field value
func (o *TierWillDowngradeNotification) GetNotificationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotificationType
}

// GetNotificationTypeOk returns a tuple with the NotificationType field value
// and a boolean to check if the value has been set.
func (o *TierWillDowngradeNotification) GetNotificationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationType, true
}

// SetNotificationType sets field value
func (o *TierWillDowngradeNotification) SetNotificationType(v string) {
	o.NotificationType = v
}

func (o TierWillDowngradeNotification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TierWillDowngradeNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["TotalResultSize"] = o.TotalResultSize
	toSerialize["Data"] = o.Data
	toSerialize["NotificationType"] = o.NotificationType
	return toSerialize, nil
}

func (o *TierWillDowngradeNotification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TotalResultSize",
		"Data",
		"NotificationType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTierWillDowngradeNotification := _TierWillDowngradeNotification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTierWillDowngradeNotification)

	if err != nil {
		return err
	}

	*o = TierWillDowngradeNotification(varTierWillDowngradeNotification)

	return err
}

type NullableTierWillDowngradeNotification struct {
	value *TierWillDowngradeNotification
	isSet bool
}

func (v NullableTierWillDowngradeNotification) Get() *TierWillDowngradeNotification {
	return v.value
}

func (v *NullableTierWillDowngradeNotification) Set(val *TierWillDowngradeNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableTierWillDowngradeNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableTierWillDowngradeNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTierWillDowngradeNotification(val *TierWillDowngradeNotification) *NullableTierWillDowngradeNotification {
	return &NullableTierWillDowngradeNotification{value: val, isSet: true}
}

func (v NullableTierWillDowngradeNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTierWillDowngradeNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


