/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AddedDeductedPointsBalancesAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddedDeductedPointsBalancesAction{}

// AddedDeductedPointsBalancesAction struct for AddedDeductedPointsBalancesAction
type AddedDeductedPointsBalancesAction struct {
	// The amount of added or deducted loyalty points.
	Amount float32 `json:"Amount"`
	// The reason for the points addition or deduction.
	Reason string `json:"Reason"`
	// The action (addition or deduction) made with loyalty points.
	Operation string `json:"Operation"`
	// The start date for loyalty points.
	StartDate *time.Time `json:"StartDate,omitempty"`
	// The expiration date for loyalty points.
	ExpiryDate *time.Time `json:"ExpiryDate,omitempty"`
}

type _AddedDeductedPointsBalancesAction AddedDeductedPointsBalancesAction

// NewAddedDeductedPointsBalancesAction instantiates a new AddedDeductedPointsBalancesAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildAddedDeductedPointsBalancesAction(amount float32, reason string, operation string) *AddedDeductedPointsBalancesAction {
	this := AddedDeductedPointsBalancesAction{}
	this.Amount = amount
	this.Reason = reason
	this.Operation = operation
	return &this
}

// NewAddedDeductedPointsBalancesActionWithDefaults instantiates a new AddedDeductedPointsBalancesAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddedDeductedPointsBalancesActionWithDefaults() *AddedDeductedPointsBalancesAction {
	this := AddedDeductedPointsBalancesAction{}
	return &this
}

// GetAmount returns the Amount field value
func (o *AddedDeductedPointsBalancesAction) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AddedDeductedPointsBalancesAction) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AddedDeductedPointsBalancesAction) SetAmount(v float32) {
	o.Amount = v
}

// GetReason returns the Reason field value
func (o *AddedDeductedPointsBalancesAction) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *AddedDeductedPointsBalancesAction) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *AddedDeductedPointsBalancesAction) SetReason(v string) {
	o.Reason = v
}

// GetOperation returns the Operation field value
func (o *AddedDeductedPointsBalancesAction) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *AddedDeductedPointsBalancesAction) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *AddedDeductedPointsBalancesAction) SetOperation(v string) {
	o.Operation = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *AddedDeductedPointsBalancesAction) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddedDeductedPointsBalancesAction) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *AddedDeductedPointsBalancesAction) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *AddedDeductedPointsBalancesAction) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *AddedDeductedPointsBalancesAction) GetExpiryDate() time.Time {
	if o == nil || IsNil(o.ExpiryDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddedDeductedPointsBalancesAction) GetExpiryDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiryDate) {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *AddedDeductedPointsBalancesAction) HasExpiryDate() bool {
	if o != nil && !IsNil(o.ExpiryDate) {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given time.Time and assigns it to the ExpiryDate field.
func (o *AddedDeductedPointsBalancesAction) SetExpiryDate(v time.Time) {
	o.ExpiryDate = &v
}

func (o AddedDeductedPointsBalancesAction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddedDeductedPointsBalancesAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Amount"] = o.Amount
	toSerialize["Reason"] = o.Reason
	toSerialize["Operation"] = o.Operation
	if !IsNil(o.StartDate) {
		toSerialize["StartDate"] = o.StartDate
	}
	if !IsNil(o.ExpiryDate) {
		toSerialize["ExpiryDate"] = o.ExpiryDate
	}
	return toSerialize, nil
}

func (o *AddedDeductedPointsBalancesAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Amount",
		"Reason",
		"Operation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddedDeductedPointsBalancesAction := _AddedDeductedPointsBalancesAction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddedDeductedPointsBalancesAction)

	if err != nil {
		return err
	}

	*o = AddedDeductedPointsBalancesAction(varAddedDeductedPointsBalancesAction)

	return err
}

type NullableAddedDeductedPointsBalancesAction struct {
	value *AddedDeductedPointsBalancesAction
	isSet bool
}

func (v NullableAddedDeductedPointsBalancesAction) Get() *AddedDeductedPointsBalancesAction {
	return v.value
}

func (v *NullableAddedDeductedPointsBalancesAction) Set(val *AddedDeductedPointsBalancesAction) {
	v.value = val
	v.isSet = true
}

func (v NullableAddedDeductedPointsBalancesAction) IsSet() bool {
	return v.isSet
}

func (v *NullableAddedDeductedPointsBalancesAction) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableAddedDeductedPointsBalancesAction(val *AddedDeductedPointsBalancesAction) *NullableAddedDeductedPointsBalancesAction {
	return &NullableAddedDeductedPointsBalancesAction{value: val, isSet: true}
}

func (v NullableAddedDeductedPointsBalancesAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddedDeductedPointsBalancesAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
