/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the MCPOAuthToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MCPOAuthToken{}

// MCPOAuthToken struct for MCPOAuthToken
type MCPOAuthToken struct {
	// Bearer access token.
	AccessToken string `json:"access_token"`
	// Token type. Always \"Bearer\".
	TokenType string `json:"token_type"`
	// Seconds until the access token expires.
	ExpiresIn int64 `json:"expires_in"`
	// Refresh token for obtaining a new access token.
	RefreshToken string `json:"refresh_token"`
	// Seconds until the refresh token expires.
	RefreshTokenExpiresIn int64 `json:"refresh_token_expires_in"`
	AdditionalProperties  map[string]interface{}
}

type _MCPOAuthToken MCPOAuthToken

// NewMCPOAuthToken instantiates a new MCPOAuthToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildMCPOAuthToken(accessToken string, tokenType string, expiresIn int64, refreshToken string, refreshTokenExpiresIn int64) *MCPOAuthToken {
	this := MCPOAuthToken{}
	this.AccessToken = accessToken
	this.TokenType = tokenType
	this.ExpiresIn = expiresIn
	this.RefreshToken = refreshToken
	this.RefreshTokenExpiresIn = refreshTokenExpiresIn
	return &this
}

// NewMCPOAuthTokenWithDefaults instantiates a new MCPOAuthToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMCPOAuthTokenWithDefaults() *MCPOAuthToken {
	this := MCPOAuthToken{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *MCPOAuthToken) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *MCPOAuthToken) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *MCPOAuthToken) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetTokenType returns the TokenType field value
func (o *MCPOAuthToken) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *MCPOAuthToken) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *MCPOAuthToken) SetTokenType(v string) {
	o.TokenType = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *MCPOAuthToken) GetExpiresIn() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *MCPOAuthToken) GetExpiresInOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *MCPOAuthToken) SetExpiresIn(v int64) {
	o.ExpiresIn = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *MCPOAuthToken) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *MCPOAuthToken) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *MCPOAuthToken) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetRefreshTokenExpiresIn returns the RefreshTokenExpiresIn field value
func (o *MCPOAuthToken) GetRefreshTokenExpiresIn() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RefreshTokenExpiresIn
}

// GetRefreshTokenExpiresInOk returns a tuple with the RefreshTokenExpiresIn field value
// and a boolean to check if the value has been set.
func (o *MCPOAuthToken) GetRefreshTokenExpiresInOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshTokenExpiresIn, true
}

// SetRefreshTokenExpiresIn sets field value
func (o *MCPOAuthToken) SetRefreshTokenExpiresIn(v int64) {
	o.RefreshTokenExpiresIn = v
}

func (o MCPOAuthToken) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MCPOAuthToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["token_type"] = o.TokenType
	toSerialize["expires_in"] = o.ExpiresIn
	toSerialize["refresh_token"] = o.RefreshToken
	toSerialize["refresh_token_expires_in"] = o.RefreshTokenExpiresIn

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MCPOAuthToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"token_type",
		"expires_in",
		"refresh_token",
		"refresh_token_expires_in",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMCPOAuthToken := _MCPOAuthToken{}

	err = json.Unmarshal(data, &varMCPOAuthToken)

	if err != nil {
		return err
	}

	*o = MCPOAuthToken(varMCPOAuthToken)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "access_token")
		delete(additionalProperties, "token_type")
		delete(additionalProperties, "expires_in")
		delete(additionalProperties, "refresh_token")
		delete(additionalProperties, "refresh_token_expires_in")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMCPOAuthToken struct {
	value *MCPOAuthToken
	isSet bool
}

func (v NullableMCPOAuthToken) Get() *MCPOAuthToken {
	return v.value
}

func (v *NullableMCPOAuthToken) Set(val *MCPOAuthToken) {
	v.value = val
	v.isSet = true
}

func (v NullableMCPOAuthToken) IsSet() bool {
	return v.isSet
}

func (v *NullableMCPOAuthToken) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableMCPOAuthToken(val *MCPOAuthToken) *NullableMCPOAuthToken {
	return &NullableMCPOAuthToken{value: val, isSet: true}
}

func (v NullableMCPOAuthToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMCPOAuthToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
