/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Effect - A generic effect that is fired by a triggered campaign. The `effectType` field selects the concrete effect variant and the shape of `props`.
type Effect struct {
	EffectAcceptCoupon                         *EffectAcceptCoupon
	EffectAcceptReferral                       *EffectAcceptReferral
	EffectAddFreeItem                          *EffectAddFreeItem
	EffectAddLoyaltyPoints                     *EffectAddLoyaltyPoints
	EffectAddNegativeLoyaltyPoints             *EffectAddNegativeLoyaltyPoints
	EffectAddToAudience                        *EffectAddToAudience
	EffectAwardGiveaway                        *EffectAwardGiveaway
	EffectBoostLoyaltyTier                     *EffectBoostLoyaltyTier
	EffectCallApi                              *EffectCallApi
	EffectChangeLoyaltyTierLevel               *EffectChangeLoyaltyTierLevel
	EffectCouponCreated                        *EffectCouponCreated
	EffectCustomEffect                         *EffectCustomEffect
	EffectDeductLoyaltyPoints                  *EffectDeductLoyaltyPoints
	EffectError                                *EffectError
	EffectExtendLoyaltyPointsExpiryDate        *EffectExtendLoyaltyPointsExpiryDate
	EffectIncreaseAchievementProgress          *EffectIncreaseAchievementProgress
	EffectJoinLoyaltyProgram                   *EffectJoinLoyaltyProgram
	EffectOffsetNegativeLoyaltyPoints          *EffectOffsetNegativeLoyaltyPoints
	EffectRedeemReferral                       *EffectRedeemReferral
	EffectReferralCreated                      *EffectReferralCreated
	EffectRejectCoupon                         *EffectRejectCoupon
	EffectRejectReferral                       *EffectRejectReferral
	EffectRemoveFromAudience                   *EffectRemoveFromAudience
	EffectReserveCoupon                        *EffectReserveCoupon
	EffectRollbackAddedLoyaltyPoints           *EffectRollbackAddedLoyaltyPoints
	EffectRollbackCoupon                       *EffectRollbackCoupon
	EffectRollbackDeductedLoyaltyPoints        *EffectRollbackDeductedLoyaltyPoints
	EffectRollbackDiscount                     *EffectRollbackDiscount
	EffectRollbackIncreasedAchievementProgress *EffectRollbackIncreasedAchievementProgress
	EffectRollbackReferral                     *EffectRollbackReferral
	EffectRollbackUseReward                    *EffectRollbackUseReward
	EffectSet                                  *EffectSet
	EffectSetDiscount                          *EffectSetDiscount
	EffectSetDiscountPerAdditionalCost         *EffectSetDiscountPerAdditionalCost
	EffectSetDiscountPerAdditionalCostPerItem  *EffectSetDiscountPerAdditionalCostPerItem
	EffectSetDiscountPerItem                   *EffectSetDiscountPerItem
	EffectSetLoyaltyPointsExpiryDate           *EffectSetLoyaltyPointsExpiryDate
	EffectShowBundleMetadata                   *EffectShowBundleMetadata
	EffectShowNotification                     *EffectShowNotification
	EffectStartAchievementProgress             *EffectStartAchievementProgress
	EffectUnlockReward                         *EffectUnlockReward
	EffectUseReward                            *EffectUseReward
	EffectWillAwardGiveaway                    *EffectWillAwardGiveaway
}

// EffectAcceptCouponAsEffect is a convenience function that returns EffectAcceptCoupon wrapped in Effect
func EffectAcceptCouponAsEffect(v *EffectAcceptCoupon) Effect {
	return Effect{
		EffectAcceptCoupon: v,
	}
}

// EffectAcceptReferralAsEffect is a convenience function that returns EffectAcceptReferral wrapped in Effect
func EffectAcceptReferralAsEffect(v *EffectAcceptReferral) Effect {
	return Effect{
		EffectAcceptReferral: v,
	}
}

// EffectAddFreeItemAsEffect is a convenience function that returns EffectAddFreeItem wrapped in Effect
func EffectAddFreeItemAsEffect(v *EffectAddFreeItem) Effect {
	return Effect{
		EffectAddFreeItem: v,
	}
}

// EffectAddLoyaltyPointsAsEffect is a convenience function that returns EffectAddLoyaltyPoints wrapped in Effect
func EffectAddLoyaltyPointsAsEffect(v *EffectAddLoyaltyPoints) Effect {
	return Effect{
		EffectAddLoyaltyPoints: v,
	}
}

// EffectAddNegativeLoyaltyPointsAsEffect is a convenience function that returns EffectAddNegativeLoyaltyPoints wrapped in Effect
func EffectAddNegativeLoyaltyPointsAsEffect(v *EffectAddNegativeLoyaltyPoints) Effect {
	return Effect{
		EffectAddNegativeLoyaltyPoints: v,
	}
}

// EffectAddToAudienceAsEffect is a convenience function that returns EffectAddToAudience wrapped in Effect
func EffectAddToAudienceAsEffect(v *EffectAddToAudience) Effect {
	return Effect{
		EffectAddToAudience: v,
	}
}

// EffectAwardGiveawayAsEffect is a convenience function that returns EffectAwardGiveaway wrapped in Effect
func EffectAwardGiveawayAsEffect(v *EffectAwardGiveaway) Effect {
	return Effect{
		EffectAwardGiveaway: v,
	}
}

// EffectBoostLoyaltyTierAsEffect is a convenience function that returns EffectBoostLoyaltyTier wrapped in Effect
func EffectBoostLoyaltyTierAsEffect(v *EffectBoostLoyaltyTier) Effect {
	return Effect{
		EffectBoostLoyaltyTier: v,
	}
}

// EffectCallApiAsEffect is a convenience function that returns EffectCallApi wrapped in Effect
func EffectCallApiAsEffect(v *EffectCallApi) Effect {
	return Effect{
		EffectCallApi: v,
	}
}

// EffectChangeLoyaltyTierLevelAsEffect is a convenience function that returns EffectChangeLoyaltyTierLevel wrapped in Effect
func EffectChangeLoyaltyTierLevelAsEffect(v *EffectChangeLoyaltyTierLevel) Effect {
	return Effect{
		EffectChangeLoyaltyTierLevel: v,
	}
}

// EffectCouponCreatedAsEffect is a convenience function that returns EffectCouponCreated wrapped in Effect
func EffectCouponCreatedAsEffect(v *EffectCouponCreated) Effect {
	return Effect{
		EffectCouponCreated: v,
	}
}

// EffectCustomEffectAsEffect is a convenience function that returns EffectCustomEffect wrapped in Effect
func EffectCustomEffectAsEffect(v *EffectCustomEffect) Effect {
	return Effect{
		EffectCustomEffect: v,
	}
}

// EffectDeductLoyaltyPointsAsEffect is a convenience function that returns EffectDeductLoyaltyPoints wrapped in Effect
func EffectDeductLoyaltyPointsAsEffect(v *EffectDeductLoyaltyPoints) Effect {
	return Effect{
		EffectDeductLoyaltyPoints: v,
	}
}

// EffectErrorAsEffect is a convenience function that returns EffectError wrapped in Effect
func EffectErrorAsEffect(v *EffectError) Effect {
	return Effect{
		EffectError: v,
	}
}

// EffectExtendLoyaltyPointsExpiryDateAsEffect is a convenience function that returns EffectExtendLoyaltyPointsExpiryDate wrapped in Effect
func EffectExtendLoyaltyPointsExpiryDateAsEffect(v *EffectExtendLoyaltyPointsExpiryDate) Effect {
	return Effect{
		EffectExtendLoyaltyPointsExpiryDate: v,
	}
}

// EffectIncreaseAchievementProgressAsEffect is a convenience function that returns EffectIncreaseAchievementProgress wrapped in Effect
func EffectIncreaseAchievementProgressAsEffect(v *EffectIncreaseAchievementProgress) Effect {
	return Effect{
		EffectIncreaseAchievementProgress: v,
	}
}

// EffectJoinLoyaltyProgramAsEffect is a convenience function that returns EffectJoinLoyaltyProgram wrapped in Effect
func EffectJoinLoyaltyProgramAsEffect(v *EffectJoinLoyaltyProgram) Effect {
	return Effect{
		EffectJoinLoyaltyProgram: v,
	}
}

// EffectOffsetNegativeLoyaltyPointsAsEffect is a convenience function that returns EffectOffsetNegativeLoyaltyPoints wrapped in Effect
func EffectOffsetNegativeLoyaltyPointsAsEffect(v *EffectOffsetNegativeLoyaltyPoints) Effect {
	return Effect{
		EffectOffsetNegativeLoyaltyPoints: v,
	}
}

// EffectRedeemReferralAsEffect is a convenience function that returns EffectRedeemReferral wrapped in Effect
func EffectRedeemReferralAsEffect(v *EffectRedeemReferral) Effect {
	return Effect{
		EffectRedeemReferral: v,
	}
}

// EffectReferralCreatedAsEffect is a convenience function that returns EffectReferralCreated wrapped in Effect
func EffectReferralCreatedAsEffect(v *EffectReferralCreated) Effect {
	return Effect{
		EffectReferralCreated: v,
	}
}

// EffectRejectCouponAsEffect is a convenience function that returns EffectRejectCoupon wrapped in Effect
func EffectRejectCouponAsEffect(v *EffectRejectCoupon) Effect {
	return Effect{
		EffectRejectCoupon: v,
	}
}

// EffectRejectReferralAsEffect is a convenience function that returns EffectRejectReferral wrapped in Effect
func EffectRejectReferralAsEffect(v *EffectRejectReferral) Effect {
	return Effect{
		EffectRejectReferral: v,
	}
}

// EffectRemoveFromAudienceAsEffect is a convenience function that returns EffectRemoveFromAudience wrapped in Effect
func EffectRemoveFromAudienceAsEffect(v *EffectRemoveFromAudience) Effect {
	return Effect{
		EffectRemoveFromAudience: v,
	}
}

// EffectReserveCouponAsEffect is a convenience function that returns EffectReserveCoupon wrapped in Effect
func EffectReserveCouponAsEffect(v *EffectReserveCoupon) Effect {
	return Effect{
		EffectReserveCoupon: v,
	}
}

// EffectRollbackAddedLoyaltyPointsAsEffect is a convenience function that returns EffectRollbackAddedLoyaltyPoints wrapped in Effect
func EffectRollbackAddedLoyaltyPointsAsEffect(v *EffectRollbackAddedLoyaltyPoints) Effect {
	return Effect{
		EffectRollbackAddedLoyaltyPoints: v,
	}
}

// EffectRollbackCouponAsEffect is a convenience function that returns EffectRollbackCoupon wrapped in Effect
func EffectRollbackCouponAsEffect(v *EffectRollbackCoupon) Effect {
	return Effect{
		EffectRollbackCoupon: v,
	}
}

// EffectRollbackDeductedLoyaltyPointsAsEffect is a convenience function that returns EffectRollbackDeductedLoyaltyPoints wrapped in Effect
func EffectRollbackDeductedLoyaltyPointsAsEffect(v *EffectRollbackDeductedLoyaltyPoints) Effect {
	return Effect{
		EffectRollbackDeductedLoyaltyPoints: v,
	}
}

// EffectRollbackDiscountAsEffect is a convenience function that returns EffectRollbackDiscount wrapped in Effect
func EffectRollbackDiscountAsEffect(v *EffectRollbackDiscount) Effect {
	return Effect{
		EffectRollbackDiscount: v,
	}
}

// EffectRollbackIncreasedAchievementProgressAsEffect is a convenience function that returns EffectRollbackIncreasedAchievementProgress wrapped in Effect
func EffectRollbackIncreasedAchievementProgressAsEffect(v *EffectRollbackIncreasedAchievementProgress) Effect {
	return Effect{
		EffectRollbackIncreasedAchievementProgress: v,
	}
}

// EffectRollbackReferralAsEffect is a convenience function that returns EffectRollbackReferral wrapped in Effect
func EffectRollbackReferralAsEffect(v *EffectRollbackReferral) Effect {
	return Effect{
		EffectRollbackReferral: v,
	}
}

// EffectRollbackUseRewardAsEffect is a convenience function that returns EffectRollbackUseReward wrapped in Effect
func EffectRollbackUseRewardAsEffect(v *EffectRollbackUseReward) Effect {
	return Effect{
		EffectRollbackUseReward: v,
	}
}

// EffectSetAsEffect is a convenience function that returns EffectSet wrapped in Effect
func EffectSetAsEffect(v *EffectSet) Effect {
	return Effect{
		EffectSet: v,
	}
}

// EffectSetDiscountAsEffect is a convenience function that returns EffectSetDiscount wrapped in Effect
func EffectSetDiscountAsEffect(v *EffectSetDiscount) Effect {
	return Effect{
		EffectSetDiscount: v,
	}
}

// EffectSetDiscountPerAdditionalCostAsEffect is a convenience function that returns EffectSetDiscountPerAdditionalCost wrapped in Effect
func EffectSetDiscountPerAdditionalCostAsEffect(v *EffectSetDiscountPerAdditionalCost) Effect {
	return Effect{
		EffectSetDiscountPerAdditionalCost: v,
	}
}

// EffectSetDiscountPerAdditionalCostPerItemAsEffect is a convenience function that returns EffectSetDiscountPerAdditionalCostPerItem wrapped in Effect
func EffectSetDiscountPerAdditionalCostPerItemAsEffect(v *EffectSetDiscountPerAdditionalCostPerItem) Effect {
	return Effect{
		EffectSetDiscountPerAdditionalCostPerItem: v,
	}
}

// EffectSetDiscountPerItemAsEffect is a convenience function that returns EffectSetDiscountPerItem wrapped in Effect
func EffectSetDiscountPerItemAsEffect(v *EffectSetDiscountPerItem) Effect {
	return Effect{
		EffectSetDiscountPerItem: v,
	}
}

// EffectSetLoyaltyPointsExpiryDateAsEffect is a convenience function that returns EffectSetLoyaltyPointsExpiryDate wrapped in Effect
func EffectSetLoyaltyPointsExpiryDateAsEffect(v *EffectSetLoyaltyPointsExpiryDate) Effect {
	return Effect{
		EffectSetLoyaltyPointsExpiryDate: v,
	}
}

// EffectShowBundleMetadataAsEffect is a convenience function that returns EffectShowBundleMetadata wrapped in Effect
func EffectShowBundleMetadataAsEffect(v *EffectShowBundleMetadata) Effect {
	return Effect{
		EffectShowBundleMetadata: v,
	}
}

// EffectShowNotificationAsEffect is a convenience function that returns EffectShowNotification wrapped in Effect
func EffectShowNotificationAsEffect(v *EffectShowNotification) Effect {
	return Effect{
		EffectShowNotification: v,
	}
}

// EffectStartAchievementProgressAsEffect is a convenience function that returns EffectStartAchievementProgress wrapped in Effect
func EffectStartAchievementProgressAsEffect(v *EffectStartAchievementProgress) Effect {
	return Effect{
		EffectStartAchievementProgress: v,
	}
}

// EffectUnlockRewardAsEffect is a convenience function that returns EffectUnlockReward wrapped in Effect
func EffectUnlockRewardAsEffect(v *EffectUnlockReward) Effect {
	return Effect{
		EffectUnlockReward: v,
	}
}

// EffectUseRewardAsEffect is a convenience function that returns EffectUseReward wrapped in Effect
func EffectUseRewardAsEffect(v *EffectUseReward) Effect {
	return Effect{
		EffectUseReward: v,
	}
}

// EffectWillAwardGiveawayAsEffect is a convenience function that returns EffectWillAwardGiveaway wrapped in Effect
func EffectWillAwardGiveawayAsEffect(v *EffectWillAwardGiveaway) Effect {
	return Effect{
		EffectWillAwardGiveaway: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Effect) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EffectAcceptCoupon
	err = newStrictDecoder(data).Decode(&dst.EffectAcceptCoupon)
	if err == nil {
		jsonEffectAcceptCoupon, _ := json.Marshal(dst.EffectAcceptCoupon)
		if string(jsonEffectAcceptCoupon) == "{}" { // empty struct
			dst.EffectAcceptCoupon = nil
		} else {
			if err = validator.Validate(dst.EffectAcceptCoupon); err != nil {
				dst.EffectAcceptCoupon = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectAcceptCoupon = nil
	}

	// try to unmarshal data into EffectAcceptReferral
	err = newStrictDecoder(data).Decode(&dst.EffectAcceptReferral)
	if err == nil {
		jsonEffectAcceptReferral, _ := json.Marshal(dst.EffectAcceptReferral)
		if string(jsonEffectAcceptReferral) == "{}" { // empty struct
			dst.EffectAcceptReferral = nil
		} else {
			if err = validator.Validate(dst.EffectAcceptReferral); err != nil {
				dst.EffectAcceptReferral = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectAcceptReferral = nil
	}

	// try to unmarshal data into EffectAddFreeItem
	err = newStrictDecoder(data).Decode(&dst.EffectAddFreeItem)
	if err == nil {
		jsonEffectAddFreeItem, _ := json.Marshal(dst.EffectAddFreeItem)
		if string(jsonEffectAddFreeItem) == "{}" { // empty struct
			dst.EffectAddFreeItem = nil
		} else {
			if err = validator.Validate(dst.EffectAddFreeItem); err != nil {
				dst.EffectAddFreeItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectAddFreeItem = nil
	}

	// try to unmarshal data into EffectAddLoyaltyPoints
	err = newStrictDecoder(data).Decode(&dst.EffectAddLoyaltyPoints)
	if err == nil {
		jsonEffectAddLoyaltyPoints, _ := json.Marshal(dst.EffectAddLoyaltyPoints)
		if string(jsonEffectAddLoyaltyPoints) == "{}" { // empty struct
			dst.EffectAddLoyaltyPoints = nil
		} else {
			if err = validator.Validate(dst.EffectAddLoyaltyPoints); err != nil {
				dst.EffectAddLoyaltyPoints = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectAddLoyaltyPoints = nil
	}

	// try to unmarshal data into EffectAddNegativeLoyaltyPoints
	err = newStrictDecoder(data).Decode(&dst.EffectAddNegativeLoyaltyPoints)
	if err == nil {
		jsonEffectAddNegativeLoyaltyPoints, _ := json.Marshal(dst.EffectAddNegativeLoyaltyPoints)
		if string(jsonEffectAddNegativeLoyaltyPoints) == "{}" { // empty struct
			dst.EffectAddNegativeLoyaltyPoints = nil
		} else {
			if err = validator.Validate(dst.EffectAddNegativeLoyaltyPoints); err != nil {
				dst.EffectAddNegativeLoyaltyPoints = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectAddNegativeLoyaltyPoints = nil
	}

	// try to unmarshal data into EffectAddToAudience
	err = newStrictDecoder(data).Decode(&dst.EffectAddToAudience)
	if err == nil {
		jsonEffectAddToAudience, _ := json.Marshal(dst.EffectAddToAudience)
		if string(jsonEffectAddToAudience) == "{}" { // empty struct
			dst.EffectAddToAudience = nil
		} else {
			if err = validator.Validate(dst.EffectAddToAudience); err != nil {
				dst.EffectAddToAudience = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectAddToAudience = nil
	}

	// try to unmarshal data into EffectAwardGiveaway
	err = newStrictDecoder(data).Decode(&dst.EffectAwardGiveaway)
	if err == nil {
		jsonEffectAwardGiveaway, _ := json.Marshal(dst.EffectAwardGiveaway)
		if string(jsonEffectAwardGiveaway) == "{}" { // empty struct
			dst.EffectAwardGiveaway = nil
		} else {
			if err = validator.Validate(dst.EffectAwardGiveaway); err != nil {
				dst.EffectAwardGiveaway = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectAwardGiveaway = nil
	}

	// try to unmarshal data into EffectBoostLoyaltyTier
	err = newStrictDecoder(data).Decode(&dst.EffectBoostLoyaltyTier)
	if err == nil {
		jsonEffectBoostLoyaltyTier, _ := json.Marshal(dst.EffectBoostLoyaltyTier)
		if string(jsonEffectBoostLoyaltyTier) == "{}" { // empty struct
			dst.EffectBoostLoyaltyTier = nil
		} else {
			if err = validator.Validate(dst.EffectBoostLoyaltyTier); err != nil {
				dst.EffectBoostLoyaltyTier = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectBoostLoyaltyTier = nil
	}

	// try to unmarshal data into EffectCallApi
	err = newStrictDecoder(data).Decode(&dst.EffectCallApi)
	if err == nil {
		jsonEffectCallApi, _ := json.Marshal(dst.EffectCallApi)
		if string(jsonEffectCallApi) == "{}" { // empty struct
			dst.EffectCallApi = nil
		} else {
			if err = validator.Validate(dst.EffectCallApi); err != nil {
				dst.EffectCallApi = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectCallApi = nil
	}

	// try to unmarshal data into EffectChangeLoyaltyTierLevel
	err = newStrictDecoder(data).Decode(&dst.EffectChangeLoyaltyTierLevel)
	if err == nil {
		jsonEffectChangeLoyaltyTierLevel, _ := json.Marshal(dst.EffectChangeLoyaltyTierLevel)
		if string(jsonEffectChangeLoyaltyTierLevel) == "{}" { // empty struct
			dst.EffectChangeLoyaltyTierLevel = nil
		} else {
			if err = validator.Validate(dst.EffectChangeLoyaltyTierLevel); err != nil {
				dst.EffectChangeLoyaltyTierLevel = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectChangeLoyaltyTierLevel = nil
	}

	// try to unmarshal data into EffectCouponCreated
	err = newStrictDecoder(data).Decode(&dst.EffectCouponCreated)
	if err == nil {
		jsonEffectCouponCreated, _ := json.Marshal(dst.EffectCouponCreated)
		if string(jsonEffectCouponCreated) == "{}" { // empty struct
			dst.EffectCouponCreated = nil
		} else {
			if err = validator.Validate(dst.EffectCouponCreated); err != nil {
				dst.EffectCouponCreated = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectCouponCreated = nil
	}

	// try to unmarshal data into EffectCustomEffect
	err = newStrictDecoder(data).Decode(&dst.EffectCustomEffect)
	if err == nil {
		jsonEffectCustomEffect, _ := json.Marshal(dst.EffectCustomEffect)
		if string(jsonEffectCustomEffect) == "{}" { // empty struct
			dst.EffectCustomEffect = nil
		} else {
			if err = validator.Validate(dst.EffectCustomEffect); err != nil {
				dst.EffectCustomEffect = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectCustomEffect = nil
	}

	// try to unmarshal data into EffectDeductLoyaltyPoints
	err = newStrictDecoder(data).Decode(&dst.EffectDeductLoyaltyPoints)
	if err == nil {
		jsonEffectDeductLoyaltyPoints, _ := json.Marshal(dst.EffectDeductLoyaltyPoints)
		if string(jsonEffectDeductLoyaltyPoints) == "{}" { // empty struct
			dst.EffectDeductLoyaltyPoints = nil
		} else {
			if err = validator.Validate(dst.EffectDeductLoyaltyPoints); err != nil {
				dst.EffectDeductLoyaltyPoints = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectDeductLoyaltyPoints = nil
	}

	// try to unmarshal data into EffectError
	err = newStrictDecoder(data).Decode(&dst.EffectError)
	if err == nil {
		jsonEffectError, _ := json.Marshal(dst.EffectError)
		if string(jsonEffectError) == "{}" { // empty struct
			dst.EffectError = nil
		} else {
			if err = validator.Validate(dst.EffectError); err != nil {
				dst.EffectError = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectError = nil
	}

	// try to unmarshal data into EffectExtendLoyaltyPointsExpiryDate
	err = newStrictDecoder(data).Decode(&dst.EffectExtendLoyaltyPointsExpiryDate)
	if err == nil {
		jsonEffectExtendLoyaltyPointsExpiryDate, _ := json.Marshal(dst.EffectExtendLoyaltyPointsExpiryDate)
		if string(jsonEffectExtendLoyaltyPointsExpiryDate) == "{}" { // empty struct
			dst.EffectExtendLoyaltyPointsExpiryDate = nil
		} else {
			if err = validator.Validate(dst.EffectExtendLoyaltyPointsExpiryDate); err != nil {
				dst.EffectExtendLoyaltyPointsExpiryDate = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectExtendLoyaltyPointsExpiryDate = nil
	}

	// try to unmarshal data into EffectIncreaseAchievementProgress
	err = newStrictDecoder(data).Decode(&dst.EffectIncreaseAchievementProgress)
	if err == nil {
		jsonEffectIncreaseAchievementProgress, _ := json.Marshal(dst.EffectIncreaseAchievementProgress)
		if string(jsonEffectIncreaseAchievementProgress) == "{}" { // empty struct
			dst.EffectIncreaseAchievementProgress = nil
		} else {
			if err = validator.Validate(dst.EffectIncreaseAchievementProgress); err != nil {
				dst.EffectIncreaseAchievementProgress = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectIncreaseAchievementProgress = nil
	}

	// try to unmarshal data into EffectJoinLoyaltyProgram
	err = newStrictDecoder(data).Decode(&dst.EffectJoinLoyaltyProgram)
	if err == nil {
		jsonEffectJoinLoyaltyProgram, _ := json.Marshal(dst.EffectJoinLoyaltyProgram)
		if string(jsonEffectJoinLoyaltyProgram) == "{}" { // empty struct
			dst.EffectJoinLoyaltyProgram = nil
		} else {
			if err = validator.Validate(dst.EffectJoinLoyaltyProgram); err != nil {
				dst.EffectJoinLoyaltyProgram = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectJoinLoyaltyProgram = nil
	}

	// try to unmarshal data into EffectOffsetNegativeLoyaltyPoints
	err = newStrictDecoder(data).Decode(&dst.EffectOffsetNegativeLoyaltyPoints)
	if err == nil {
		jsonEffectOffsetNegativeLoyaltyPoints, _ := json.Marshal(dst.EffectOffsetNegativeLoyaltyPoints)
		if string(jsonEffectOffsetNegativeLoyaltyPoints) == "{}" { // empty struct
			dst.EffectOffsetNegativeLoyaltyPoints = nil
		} else {
			if err = validator.Validate(dst.EffectOffsetNegativeLoyaltyPoints); err != nil {
				dst.EffectOffsetNegativeLoyaltyPoints = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectOffsetNegativeLoyaltyPoints = nil
	}

	// try to unmarshal data into EffectRedeemReferral
	err = newStrictDecoder(data).Decode(&dst.EffectRedeemReferral)
	if err == nil {
		jsonEffectRedeemReferral, _ := json.Marshal(dst.EffectRedeemReferral)
		if string(jsonEffectRedeemReferral) == "{}" { // empty struct
			dst.EffectRedeemReferral = nil
		} else {
			if err = validator.Validate(dst.EffectRedeemReferral); err != nil {
				dst.EffectRedeemReferral = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRedeemReferral = nil
	}

	// try to unmarshal data into EffectReferralCreated
	err = newStrictDecoder(data).Decode(&dst.EffectReferralCreated)
	if err == nil {
		jsonEffectReferralCreated, _ := json.Marshal(dst.EffectReferralCreated)
		if string(jsonEffectReferralCreated) == "{}" { // empty struct
			dst.EffectReferralCreated = nil
		} else {
			if err = validator.Validate(dst.EffectReferralCreated); err != nil {
				dst.EffectReferralCreated = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectReferralCreated = nil
	}

	// try to unmarshal data into EffectRejectCoupon
	err = newStrictDecoder(data).Decode(&dst.EffectRejectCoupon)
	if err == nil {
		jsonEffectRejectCoupon, _ := json.Marshal(dst.EffectRejectCoupon)
		if string(jsonEffectRejectCoupon) == "{}" { // empty struct
			dst.EffectRejectCoupon = nil
		} else {
			if err = validator.Validate(dst.EffectRejectCoupon); err != nil {
				dst.EffectRejectCoupon = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRejectCoupon = nil
	}

	// try to unmarshal data into EffectRejectReferral
	err = newStrictDecoder(data).Decode(&dst.EffectRejectReferral)
	if err == nil {
		jsonEffectRejectReferral, _ := json.Marshal(dst.EffectRejectReferral)
		if string(jsonEffectRejectReferral) == "{}" { // empty struct
			dst.EffectRejectReferral = nil
		} else {
			if err = validator.Validate(dst.EffectRejectReferral); err != nil {
				dst.EffectRejectReferral = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRejectReferral = nil
	}

	// try to unmarshal data into EffectRemoveFromAudience
	err = newStrictDecoder(data).Decode(&dst.EffectRemoveFromAudience)
	if err == nil {
		jsonEffectRemoveFromAudience, _ := json.Marshal(dst.EffectRemoveFromAudience)
		if string(jsonEffectRemoveFromAudience) == "{}" { // empty struct
			dst.EffectRemoveFromAudience = nil
		} else {
			if err = validator.Validate(dst.EffectRemoveFromAudience); err != nil {
				dst.EffectRemoveFromAudience = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRemoveFromAudience = nil
	}

	// try to unmarshal data into EffectReserveCoupon
	err = newStrictDecoder(data).Decode(&dst.EffectReserveCoupon)
	if err == nil {
		jsonEffectReserveCoupon, _ := json.Marshal(dst.EffectReserveCoupon)
		if string(jsonEffectReserveCoupon) == "{}" { // empty struct
			dst.EffectReserveCoupon = nil
		} else {
			if err = validator.Validate(dst.EffectReserveCoupon); err != nil {
				dst.EffectReserveCoupon = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectReserveCoupon = nil
	}

	// try to unmarshal data into EffectRollbackAddedLoyaltyPoints
	err = newStrictDecoder(data).Decode(&dst.EffectRollbackAddedLoyaltyPoints)
	if err == nil {
		jsonEffectRollbackAddedLoyaltyPoints, _ := json.Marshal(dst.EffectRollbackAddedLoyaltyPoints)
		if string(jsonEffectRollbackAddedLoyaltyPoints) == "{}" { // empty struct
			dst.EffectRollbackAddedLoyaltyPoints = nil
		} else {
			if err = validator.Validate(dst.EffectRollbackAddedLoyaltyPoints); err != nil {
				dst.EffectRollbackAddedLoyaltyPoints = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRollbackAddedLoyaltyPoints = nil
	}

	// try to unmarshal data into EffectRollbackCoupon
	err = newStrictDecoder(data).Decode(&dst.EffectRollbackCoupon)
	if err == nil {
		jsonEffectRollbackCoupon, _ := json.Marshal(dst.EffectRollbackCoupon)
		if string(jsonEffectRollbackCoupon) == "{}" { // empty struct
			dst.EffectRollbackCoupon = nil
		} else {
			if err = validator.Validate(dst.EffectRollbackCoupon); err != nil {
				dst.EffectRollbackCoupon = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRollbackCoupon = nil
	}

	// try to unmarshal data into EffectRollbackDeductedLoyaltyPoints
	err = newStrictDecoder(data).Decode(&dst.EffectRollbackDeductedLoyaltyPoints)
	if err == nil {
		jsonEffectRollbackDeductedLoyaltyPoints, _ := json.Marshal(dst.EffectRollbackDeductedLoyaltyPoints)
		if string(jsonEffectRollbackDeductedLoyaltyPoints) == "{}" { // empty struct
			dst.EffectRollbackDeductedLoyaltyPoints = nil
		} else {
			if err = validator.Validate(dst.EffectRollbackDeductedLoyaltyPoints); err != nil {
				dst.EffectRollbackDeductedLoyaltyPoints = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRollbackDeductedLoyaltyPoints = nil
	}

	// try to unmarshal data into EffectRollbackDiscount
	err = newStrictDecoder(data).Decode(&dst.EffectRollbackDiscount)
	if err == nil {
		jsonEffectRollbackDiscount, _ := json.Marshal(dst.EffectRollbackDiscount)
		if string(jsonEffectRollbackDiscount) == "{}" { // empty struct
			dst.EffectRollbackDiscount = nil
		} else {
			if err = validator.Validate(dst.EffectRollbackDiscount); err != nil {
				dst.EffectRollbackDiscount = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRollbackDiscount = nil
	}

	// try to unmarshal data into EffectRollbackIncreasedAchievementProgress
	err = newStrictDecoder(data).Decode(&dst.EffectRollbackIncreasedAchievementProgress)
	if err == nil {
		jsonEffectRollbackIncreasedAchievementProgress, _ := json.Marshal(dst.EffectRollbackIncreasedAchievementProgress)
		if string(jsonEffectRollbackIncreasedAchievementProgress) == "{}" { // empty struct
			dst.EffectRollbackIncreasedAchievementProgress = nil
		} else {
			if err = validator.Validate(dst.EffectRollbackIncreasedAchievementProgress); err != nil {
				dst.EffectRollbackIncreasedAchievementProgress = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRollbackIncreasedAchievementProgress = nil
	}

	// try to unmarshal data into EffectRollbackReferral
	err = newStrictDecoder(data).Decode(&dst.EffectRollbackReferral)
	if err == nil {
		jsonEffectRollbackReferral, _ := json.Marshal(dst.EffectRollbackReferral)
		if string(jsonEffectRollbackReferral) == "{}" { // empty struct
			dst.EffectRollbackReferral = nil
		} else {
			if err = validator.Validate(dst.EffectRollbackReferral); err != nil {
				dst.EffectRollbackReferral = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRollbackReferral = nil
	}

	// try to unmarshal data into EffectRollbackUseReward
	err = newStrictDecoder(data).Decode(&dst.EffectRollbackUseReward)
	if err == nil {
		jsonEffectRollbackUseReward, _ := json.Marshal(dst.EffectRollbackUseReward)
		if string(jsonEffectRollbackUseReward) == "{}" { // empty struct
			dst.EffectRollbackUseReward = nil
		} else {
			if err = validator.Validate(dst.EffectRollbackUseReward); err != nil {
				dst.EffectRollbackUseReward = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectRollbackUseReward = nil
	}

	// try to unmarshal data into EffectSet
	err = newStrictDecoder(data).Decode(&dst.EffectSet)
	if err == nil {
		jsonEffectSet, _ := json.Marshal(dst.EffectSet)
		if string(jsonEffectSet) == "{}" { // empty struct
			dst.EffectSet = nil
		} else {
			if err = validator.Validate(dst.EffectSet); err != nil {
				dst.EffectSet = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectSet = nil
	}

	// try to unmarshal data into EffectSetDiscount
	err = newStrictDecoder(data).Decode(&dst.EffectSetDiscount)
	if err == nil {
		jsonEffectSetDiscount, _ := json.Marshal(dst.EffectSetDiscount)
		if string(jsonEffectSetDiscount) == "{}" { // empty struct
			dst.EffectSetDiscount = nil
		} else {
			if err = validator.Validate(dst.EffectSetDiscount); err != nil {
				dst.EffectSetDiscount = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectSetDiscount = nil
	}

	// try to unmarshal data into EffectSetDiscountPerAdditionalCost
	err = newStrictDecoder(data).Decode(&dst.EffectSetDiscountPerAdditionalCost)
	if err == nil {
		jsonEffectSetDiscountPerAdditionalCost, _ := json.Marshal(dst.EffectSetDiscountPerAdditionalCost)
		if string(jsonEffectSetDiscountPerAdditionalCost) == "{}" { // empty struct
			dst.EffectSetDiscountPerAdditionalCost = nil
		} else {
			if err = validator.Validate(dst.EffectSetDiscountPerAdditionalCost); err != nil {
				dst.EffectSetDiscountPerAdditionalCost = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectSetDiscountPerAdditionalCost = nil
	}

	// try to unmarshal data into EffectSetDiscountPerAdditionalCostPerItem
	err = newStrictDecoder(data).Decode(&dst.EffectSetDiscountPerAdditionalCostPerItem)
	if err == nil {
		jsonEffectSetDiscountPerAdditionalCostPerItem, _ := json.Marshal(dst.EffectSetDiscountPerAdditionalCostPerItem)
		if string(jsonEffectSetDiscountPerAdditionalCostPerItem) == "{}" { // empty struct
			dst.EffectSetDiscountPerAdditionalCostPerItem = nil
		} else {
			if err = validator.Validate(dst.EffectSetDiscountPerAdditionalCostPerItem); err != nil {
				dst.EffectSetDiscountPerAdditionalCostPerItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectSetDiscountPerAdditionalCostPerItem = nil
	}

	// try to unmarshal data into EffectSetDiscountPerItem
	err = newStrictDecoder(data).Decode(&dst.EffectSetDiscountPerItem)
	if err == nil {
		jsonEffectSetDiscountPerItem, _ := json.Marshal(dst.EffectSetDiscountPerItem)
		if string(jsonEffectSetDiscountPerItem) == "{}" { // empty struct
			dst.EffectSetDiscountPerItem = nil
		} else {
			if err = validator.Validate(dst.EffectSetDiscountPerItem); err != nil {
				dst.EffectSetDiscountPerItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectSetDiscountPerItem = nil
	}

	// try to unmarshal data into EffectSetLoyaltyPointsExpiryDate
	err = newStrictDecoder(data).Decode(&dst.EffectSetLoyaltyPointsExpiryDate)
	if err == nil {
		jsonEffectSetLoyaltyPointsExpiryDate, _ := json.Marshal(dst.EffectSetLoyaltyPointsExpiryDate)
		if string(jsonEffectSetLoyaltyPointsExpiryDate) == "{}" { // empty struct
			dst.EffectSetLoyaltyPointsExpiryDate = nil
		} else {
			if err = validator.Validate(dst.EffectSetLoyaltyPointsExpiryDate); err != nil {
				dst.EffectSetLoyaltyPointsExpiryDate = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectSetLoyaltyPointsExpiryDate = nil
	}

	// try to unmarshal data into EffectShowBundleMetadata
	err = newStrictDecoder(data).Decode(&dst.EffectShowBundleMetadata)
	if err == nil {
		jsonEffectShowBundleMetadata, _ := json.Marshal(dst.EffectShowBundleMetadata)
		if string(jsonEffectShowBundleMetadata) == "{}" { // empty struct
			dst.EffectShowBundleMetadata = nil
		} else {
			if err = validator.Validate(dst.EffectShowBundleMetadata); err != nil {
				dst.EffectShowBundleMetadata = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectShowBundleMetadata = nil
	}

	// try to unmarshal data into EffectShowNotification
	err = newStrictDecoder(data).Decode(&dst.EffectShowNotification)
	if err == nil {
		jsonEffectShowNotification, _ := json.Marshal(dst.EffectShowNotification)
		if string(jsonEffectShowNotification) == "{}" { // empty struct
			dst.EffectShowNotification = nil
		} else {
			if err = validator.Validate(dst.EffectShowNotification); err != nil {
				dst.EffectShowNotification = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectShowNotification = nil
	}

	// try to unmarshal data into EffectStartAchievementProgress
	err = newStrictDecoder(data).Decode(&dst.EffectStartAchievementProgress)
	if err == nil {
		jsonEffectStartAchievementProgress, _ := json.Marshal(dst.EffectStartAchievementProgress)
		if string(jsonEffectStartAchievementProgress) == "{}" { // empty struct
			dst.EffectStartAchievementProgress = nil
		} else {
			if err = validator.Validate(dst.EffectStartAchievementProgress); err != nil {
				dst.EffectStartAchievementProgress = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectStartAchievementProgress = nil
	}

	// try to unmarshal data into EffectUnlockReward
	err = newStrictDecoder(data).Decode(&dst.EffectUnlockReward)
	if err == nil {
		jsonEffectUnlockReward, _ := json.Marshal(dst.EffectUnlockReward)
		if string(jsonEffectUnlockReward) == "{}" { // empty struct
			dst.EffectUnlockReward = nil
		} else {
			if err = validator.Validate(dst.EffectUnlockReward); err != nil {
				dst.EffectUnlockReward = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectUnlockReward = nil
	}

	// try to unmarshal data into EffectUseReward
	err = newStrictDecoder(data).Decode(&dst.EffectUseReward)
	if err == nil {
		jsonEffectUseReward, _ := json.Marshal(dst.EffectUseReward)
		if string(jsonEffectUseReward) == "{}" { // empty struct
			dst.EffectUseReward = nil
		} else {
			if err = validator.Validate(dst.EffectUseReward); err != nil {
				dst.EffectUseReward = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectUseReward = nil
	}

	// try to unmarshal data into EffectWillAwardGiveaway
	err = newStrictDecoder(data).Decode(&dst.EffectWillAwardGiveaway)
	if err == nil {
		jsonEffectWillAwardGiveaway, _ := json.Marshal(dst.EffectWillAwardGiveaway)
		if string(jsonEffectWillAwardGiveaway) == "{}" { // empty struct
			dst.EffectWillAwardGiveaway = nil
		} else {
			if err = validator.Validate(dst.EffectWillAwardGiveaway); err != nil {
				dst.EffectWillAwardGiveaway = nil
			} else {
				match++
			}
		}
	} else {
		dst.EffectWillAwardGiveaway = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EffectAcceptCoupon = nil
		dst.EffectAcceptReferral = nil
		dst.EffectAddFreeItem = nil
		dst.EffectAddLoyaltyPoints = nil
		dst.EffectAddNegativeLoyaltyPoints = nil
		dst.EffectAddToAudience = nil
		dst.EffectAwardGiveaway = nil
		dst.EffectBoostLoyaltyTier = nil
		dst.EffectCallApi = nil
		dst.EffectChangeLoyaltyTierLevel = nil
		dst.EffectCouponCreated = nil
		dst.EffectCustomEffect = nil
		dst.EffectDeductLoyaltyPoints = nil
		dst.EffectError = nil
		dst.EffectExtendLoyaltyPointsExpiryDate = nil
		dst.EffectIncreaseAchievementProgress = nil
		dst.EffectJoinLoyaltyProgram = nil
		dst.EffectOffsetNegativeLoyaltyPoints = nil
		dst.EffectRedeemReferral = nil
		dst.EffectReferralCreated = nil
		dst.EffectRejectCoupon = nil
		dst.EffectRejectReferral = nil
		dst.EffectRemoveFromAudience = nil
		dst.EffectReserveCoupon = nil
		dst.EffectRollbackAddedLoyaltyPoints = nil
		dst.EffectRollbackCoupon = nil
		dst.EffectRollbackDeductedLoyaltyPoints = nil
		dst.EffectRollbackDiscount = nil
		dst.EffectRollbackIncreasedAchievementProgress = nil
		dst.EffectRollbackReferral = nil
		dst.EffectRollbackUseReward = nil
		dst.EffectSet = nil
		dst.EffectSetDiscount = nil
		dst.EffectSetDiscountPerAdditionalCost = nil
		dst.EffectSetDiscountPerAdditionalCostPerItem = nil
		dst.EffectSetDiscountPerItem = nil
		dst.EffectSetLoyaltyPointsExpiryDate = nil
		dst.EffectShowBundleMetadata = nil
		dst.EffectShowNotification = nil
		dst.EffectStartAchievementProgress = nil
		dst.EffectUnlockReward = nil
		dst.EffectUseReward = nil
		dst.EffectWillAwardGiveaway = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Effect)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(Effect): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(Effect)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Effect) MarshalJSON() ([]byte, error) {
	if src.EffectAcceptCoupon != nil {
		return json.Marshal(&src.EffectAcceptCoupon)
	}

	if src.EffectAcceptReferral != nil {
		return json.Marshal(&src.EffectAcceptReferral)
	}

	if src.EffectAddFreeItem != nil {
		return json.Marshal(&src.EffectAddFreeItem)
	}

	if src.EffectAddLoyaltyPoints != nil {
		return json.Marshal(&src.EffectAddLoyaltyPoints)
	}

	if src.EffectAddNegativeLoyaltyPoints != nil {
		return json.Marshal(&src.EffectAddNegativeLoyaltyPoints)
	}

	if src.EffectAddToAudience != nil {
		return json.Marshal(&src.EffectAddToAudience)
	}

	if src.EffectAwardGiveaway != nil {
		return json.Marshal(&src.EffectAwardGiveaway)
	}

	if src.EffectBoostLoyaltyTier != nil {
		return json.Marshal(&src.EffectBoostLoyaltyTier)
	}

	if src.EffectCallApi != nil {
		return json.Marshal(&src.EffectCallApi)
	}

	if src.EffectChangeLoyaltyTierLevel != nil {
		return json.Marshal(&src.EffectChangeLoyaltyTierLevel)
	}

	if src.EffectCouponCreated != nil {
		return json.Marshal(&src.EffectCouponCreated)
	}

	if src.EffectCustomEffect != nil {
		return json.Marshal(&src.EffectCustomEffect)
	}

	if src.EffectDeductLoyaltyPoints != nil {
		return json.Marshal(&src.EffectDeductLoyaltyPoints)
	}

	if src.EffectError != nil {
		return json.Marshal(&src.EffectError)
	}

	if src.EffectExtendLoyaltyPointsExpiryDate != nil {
		return json.Marshal(&src.EffectExtendLoyaltyPointsExpiryDate)
	}

	if src.EffectIncreaseAchievementProgress != nil {
		return json.Marshal(&src.EffectIncreaseAchievementProgress)
	}

	if src.EffectJoinLoyaltyProgram != nil {
		return json.Marshal(&src.EffectJoinLoyaltyProgram)
	}

	if src.EffectOffsetNegativeLoyaltyPoints != nil {
		return json.Marshal(&src.EffectOffsetNegativeLoyaltyPoints)
	}

	if src.EffectRedeemReferral != nil {
		return json.Marshal(&src.EffectRedeemReferral)
	}

	if src.EffectReferralCreated != nil {
		return json.Marshal(&src.EffectReferralCreated)
	}

	if src.EffectRejectCoupon != nil {
		return json.Marshal(&src.EffectRejectCoupon)
	}

	if src.EffectRejectReferral != nil {
		return json.Marshal(&src.EffectRejectReferral)
	}

	if src.EffectRemoveFromAudience != nil {
		return json.Marshal(&src.EffectRemoveFromAudience)
	}

	if src.EffectReserveCoupon != nil {
		return json.Marshal(&src.EffectReserveCoupon)
	}

	if src.EffectRollbackAddedLoyaltyPoints != nil {
		return json.Marshal(&src.EffectRollbackAddedLoyaltyPoints)
	}

	if src.EffectRollbackCoupon != nil {
		return json.Marshal(&src.EffectRollbackCoupon)
	}

	if src.EffectRollbackDeductedLoyaltyPoints != nil {
		return json.Marshal(&src.EffectRollbackDeductedLoyaltyPoints)
	}

	if src.EffectRollbackDiscount != nil {
		return json.Marshal(&src.EffectRollbackDiscount)
	}

	if src.EffectRollbackIncreasedAchievementProgress != nil {
		return json.Marshal(&src.EffectRollbackIncreasedAchievementProgress)
	}

	if src.EffectRollbackReferral != nil {
		return json.Marshal(&src.EffectRollbackReferral)
	}

	if src.EffectRollbackUseReward != nil {
		return json.Marshal(&src.EffectRollbackUseReward)
	}

	if src.EffectSet != nil {
		return json.Marshal(&src.EffectSet)
	}

	if src.EffectSetDiscount != nil {
		return json.Marshal(&src.EffectSetDiscount)
	}

	if src.EffectSetDiscountPerAdditionalCost != nil {
		return json.Marshal(&src.EffectSetDiscountPerAdditionalCost)
	}

	if src.EffectSetDiscountPerAdditionalCostPerItem != nil {
		return json.Marshal(&src.EffectSetDiscountPerAdditionalCostPerItem)
	}

	if src.EffectSetDiscountPerItem != nil {
		return json.Marshal(&src.EffectSetDiscountPerItem)
	}

	if src.EffectSetLoyaltyPointsExpiryDate != nil {
		return json.Marshal(&src.EffectSetLoyaltyPointsExpiryDate)
	}

	if src.EffectShowBundleMetadata != nil {
		return json.Marshal(&src.EffectShowBundleMetadata)
	}

	if src.EffectShowNotification != nil {
		return json.Marshal(&src.EffectShowNotification)
	}

	if src.EffectStartAchievementProgress != nil {
		return json.Marshal(&src.EffectStartAchievementProgress)
	}

	if src.EffectUnlockReward != nil {
		return json.Marshal(&src.EffectUnlockReward)
	}

	if src.EffectUseReward != nil {
		return json.Marshal(&src.EffectUseReward)
	}

	if src.EffectWillAwardGiveaway != nil {
		return json.Marshal(&src.EffectWillAwardGiveaway)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Effect) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.EffectAcceptCoupon != nil {
		return obj.EffectAcceptCoupon
	}

	if obj.EffectAcceptReferral != nil {
		return obj.EffectAcceptReferral
	}

	if obj.EffectAddFreeItem != nil {
		return obj.EffectAddFreeItem
	}

	if obj.EffectAddLoyaltyPoints != nil {
		return obj.EffectAddLoyaltyPoints
	}

	if obj.EffectAddNegativeLoyaltyPoints != nil {
		return obj.EffectAddNegativeLoyaltyPoints
	}

	if obj.EffectAddToAudience != nil {
		return obj.EffectAddToAudience
	}

	if obj.EffectAwardGiveaway != nil {
		return obj.EffectAwardGiveaway
	}

	if obj.EffectBoostLoyaltyTier != nil {
		return obj.EffectBoostLoyaltyTier
	}

	if obj.EffectCallApi != nil {
		return obj.EffectCallApi
	}

	if obj.EffectChangeLoyaltyTierLevel != nil {
		return obj.EffectChangeLoyaltyTierLevel
	}

	if obj.EffectCouponCreated != nil {
		return obj.EffectCouponCreated
	}

	if obj.EffectCustomEffect != nil {
		return obj.EffectCustomEffect
	}

	if obj.EffectDeductLoyaltyPoints != nil {
		return obj.EffectDeductLoyaltyPoints
	}

	if obj.EffectError != nil {
		return obj.EffectError
	}

	if obj.EffectExtendLoyaltyPointsExpiryDate != nil {
		return obj.EffectExtendLoyaltyPointsExpiryDate
	}

	if obj.EffectIncreaseAchievementProgress != nil {
		return obj.EffectIncreaseAchievementProgress
	}

	if obj.EffectJoinLoyaltyProgram != nil {
		return obj.EffectJoinLoyaltyProgram
	}

	if obj.EffectOffsetNegativeLoyaltyPoints != nil {
		return obj.EffectOffsetNegativeLoyaltyPoints
	}

	if obj.EffectRedeemReferral != nil {
		return obj.EffectRedeemReferral
	}

	if obj.EffectReferralCreated != nil {
		return obj.EffectReferralCreated
	}

	if obj.EffectRejectCoupon != nil {
		return obj.EffectRejectCoupon
	}

	if obj.EffectRejectReferral != nil {
		return obj.EffectRejectReferral
	}

	if obj.EffectRemoveFromAudience != nil {
		return obj.EffectRemoveFromAudience
	}

	if obj.EffectReserveCoupon != nil {
		return obj.EffectReserveCoupon
	}

	if obj.EffectRollbackAddedLoyaltyPoints != nil {
		return obj.EffectRollbackAddedLoyaltyPoints
	}

	if obj.EffectRollbackCoupon != nil {
		return obj.EffectRollbackCoupon
	}

	if obj.EffectRollbackDeductedLoyaltyPoints != nil {
		return obj.EffectRollbackDeductedLoyaltyPoints
	}

	if obj.EffectRollbackDiscount != nil {
		return obj.EffectRollbackDiscount
	}

	if obj.EffectRollbackIncreasedAchievementProgress != nil {
		return obj.EffectRollbackIncreasedAchievementProgress
	}

	if obj.EffectRollbackReferral != nil {
		return obj.EffectRollbackReferral
	}

	if obj.EffectRollbackUseReward != nil {
		return obj.EffectRollbackUseReward
	}

	if obj.EffectSet != nil {
		return obj.EffectSet
	}

	if obj.EffectSetDiscount != nil {
		return obj.EffectSetDiscount
	}

	if obj.EffectSetDiscountPerAdditionalCost != nil {
		return obj.EffectSetDiscountPerAdditionalCost
	}

	if obj.EffectSetDiscountPerAdditionalCostPerItem != nil {
		return obj.EffectSetDiscountPerAdditionalCostPerItem
	}

	if obj.EffectSetDiscountPerItem != nil {
		return obj.EffectSetDiscountPerItem
	}

	if obj.EffectSetLoyaltyPointsExpiryDate != nil {
		return obj.EffectSetLoyaltyPointsExpiryDate
	}

	if obj.EffectShowBundleMetadata != nil {
		return obj.EffectShowBundleMetadata
	}

	if obj.EffectShowNotification != nil {
		return obj.EffectShowNotification
	}

	if obj.EffectStartAchievementProgress != nil {
		return obj.EffectStartAchievementProgress
	}

	if obj.EffectUnlockReward != nil {
		return obj.EffectUnlockReward
	}

	if obj.EffectUseReward != nil {
		return obj.EffectUseReward
	}

	if obj.EffectWillAwardGiveaway != nil {
		return obj.EffectWillAwardGiveaway
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Effect) GetActualInstanceValue() interface{} {
	if obj.EffectAcceptCoupon != nil {
		return *obj.EffectAcceptCoupon
	}

	if obj.EffectAcceptReferral != nil {
		return *obj.EffectAcceptReferral
	}

	if obj.EffectAddFreeItem != nil {
		return *obj.EffectAddFreeItem
	}

	if obj.EffectAddLoyaltyPoints != nil {
		return *obj.EffectAddLoyaltyPoints
	}

	if obj.EffectAddNegativeLoyaltyPoints != nil {
		return *obj.EffectAddNegativeLoyaltyPoints
	}

	if obj.EffectAddToAudience != nil {
		return *obj.EffectAddToAudience
	}

	if obj.EffectAwardGiveaway != nil {
		return *obj.EffectAwardGiveaway
	}

	if obj.EffectBoostLoyaltyTier != nil {
		return *obj.EffectBoostLoyaltyTier
	}

	if obj.EffectCallApi != nil {
		return *obj.EffectCallApi
	}

	if obj.EffectChangeLoyaltyTierLevel != nil {
		return *obj.EffectChangeLoyaltyTierLevel
	}

	if obj.EffectCouponCreated != nil {
		return *obj.EffectCouponCreated
	}

	if obj.EffectCustomEffect != nil {
		return *obj.EffectCustomEffect
	}

	if obj.EffectDeductLoyaltyPoints != nil {
		return *obj.EffectDeductLoyaltyPoints
	}

	if obj.EffectError != nil {
		return *obj.EffectError
	}

	if obj.EffectExtendLoyaltyPointsExpiryDate != nil {
		return *obj.EffectExtendLoyaltyPointsExpiryDate
	}

	if obj.EffectIncreaseAchievementProgress != nil {
		return *obj.EffectIncreaseAchievementProgress
	}

	if obj.EffectJoinLoyaltyProgram != nil {
		return *obj.EffectJoinLoyaltyProgram
	}

	if obj.EffectOffsetNegativeLoyaltyPoints != nil {
		return *obj.EffectOffsetNegativeLoyaltyPoints
	}

	if obj.EffectRedeemReferral != nil {
		return *obj.EffectRedeemReferral
	}

	if obj.EffectReferralCreated != nil {
		return *obj.EffectReferralCreated
	}

	if obj.EffectRejectCoupon != nil {
		return *obj.EffectRejectCoupon
	}

	if obj.EffectRejectReferral != nil {
		return *obj.EffectRejectReferral
	}

	if obj.EffectRemoveFromAudience != nil {
		return *obj.EffectRemoveFromAudience
	}

	if obj.EffectReserveCoupon != nil {
		return *obj.EffectReserveCoupon
	}

	if obj.EffectRollbackAddedLoyaltyPoints != nil {
		return *obj.EffectRollbackAddedLoyaltyPoints
	}

	if obj.EffectRollbackCoupon != nil {
		return *obj.EffectRollbackCoupon
	}

	if obj.EffectRollbackDeductedLoyaltyPoints != nil {
		return *obj.EffectRollbackDeductedLoyaltyPoints
	}

	if obj.EffectRollbackDiscount != nil {
		return *obj.EffectRollbackDiscount
	}

	if obj.EffectRollbackIncreasedAchievementProgress != nil {
		return *obj.EffectRollbackIncreasedAchievementProgress
	}

	if obj.EffectRollbackReferral != nil {
		return *obj.EffectRollbackReferral
	}

	if obj.EffectRollbackUseReward != nil {
		return *obj.EffectRollbackUseReward
	}

	if obj.EffectSet != nil {
		return *obj.EffectSet
	}

	if obj.EffectSetDiscount != nil {
		return *obj.EffectSetDiscount
	}

	if obj.EffectSetDiscountPerAdditionalCost != nil {
		return *obj.EffectSetDiscountPerAdditionalCost
	}

	if obj.EffectSetDiscountPerAdditionalCostPerItem != nil {
		return *obj.EffectSetDiscountPerAdditionalCostPerItem
	}

	if obj.EffectSetDiscountPerItem != nil {
		return *obj.EffectSetDiscountPerItem
	}

	if obj.EffectSetLoyaltyPointsExpiryDate != nil {
		return *obj.EffectSetLoyaltyPointsExpiryDate
	}

	if obj.EffectShowBundleMetadata != nil {
		return *obj.EffectShowBundleMetadata
	}

	if obj.EffectShowNotification != nil {
		return *obj.EffectShowNotification
	}

	if obj.EffectStartAchievementProgress != nil {
		return *obj.EffectStartAchievementProgress
	}

	if obj.EffectUnlockReward != nil {
		return *obj.EffectUnlockReward
	}

	if obj.EffectUseReward != nil {
		return *obj.EffectUseReward
	}

	if obj.EffectWillAwardGiveaway != nil {
		return *obj.EffectWillAwardGiveaway
	}

	// all schemas are nil
	return nil
}

type NullableEffect struct {
	value *Effect
	isSet bool
}

func (v NullableEffect) Get() *Effect {
	return v.value
}

func (v *NullableEffect) Set(val *Effect) {
	v.value = val
	v.isSet = true
}

func (v NullableEffect) IsSet() bool {
	return v.isSet
}

func (v *NullableEffect) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableEffect(val *Effect) *NullableEffect {
	return &NullableEffect{value: val, isSet: true}
}

func (v NullableEffect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEffect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
