/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetLoyaltyProgramTransactions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLoyaltyProgramTransactions200Response{}

// GetLoyaltyProgramTransactions200Response struct for GetLoyaltyProgramTransactions200Response
type GetLoyaltyProgramTransactions200Response struct {
	HasMore bool `json:"hasMore"`
	Data []LoyaltyProgramTransaction `json:"data"`
}

type _GetLoyaltyProgramTransactions200Response GetLoyaltyProgramTransactions200Response

// NewGetLoyaltyProgramTransactions200Response instantiates a new GetLoyaltyProgramTransactions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildGetLoyaltyProgramTransactions200Response(hasMore bool, data []LoyaltyProgramTransaction) *GetLoyaltyProgramTransactions200Response {
	this := GetLoyaltyProgramTransactions200Response{}
	this.HasMore = hasMore
	this.Data = data
	return &this
}

// NewGetLoyaltyProgramTransactions200ResponseWithDefaults instantiates a new GetLoyaltyProgramTransactions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLoyaltyProgramTransactions200ResponseWithDefaults() *GetLoyaltyProgramTransactions200Response {
	this := GetLoyaltyProgramTransactions200Response{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *GetLoyaltyProgramTransactions200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *GetLoyaltyProgramTransactions200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *GetLoyaltyProgramTransactions200Response) SetHasMore(v bool) {
	o.HasMore = v
}

// GetData returns the Data field value
func (o *GetLoyaltyProgramTransactions200Response) GetData() []LoyaltyProgramTransaction {
	if o == nil {
		var ret []LoyaltyProgramTransaction
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetLoyaltyProgramTransactions200Response) GetDataOk() ([]LoyaltyProgramTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetLoyaltyProgramTransactions200Response) SetData(v []LoyaltyProgramTransaction) {
	o.Data = v
}

func (o GetLoyaltyProgramTransactions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLoyaltyProgramTransactions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hasMore"] = o.HasMore
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetLoyaltyProgramTransactions200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hasMore",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetLoyaltyProgramTransactions200Response := _GetLoyaltyProgramTransactions200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetLoyaltyProgramTransactions200Response)

	if err != nil {
		return err
	}

	*o = GetLoyaltyProgramTransactions200Response(varGetLoyaltyProgramTransactions200Response)

	return err
}

type NullableGetLoyaltyProgramTransactions200Response struct {
	value *GetLoyaltyProgramTransactions200Response
	isSet bool
}

func (v NullableGetLoyaltyProgramTransactions200Response) Get() *GetLoyaltyProgramTransactions200Response {
	return v.value
}

func (v *NullableGetLoyaltyProgramTransactions200Response) Set(val *GetLoyaltyProgramTransactions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLoyaltyProgramTransactions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLoyaltyProgramTransactions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableGetLoyaltyProgramTransactions200Response(val *GetLoyaltyProgramTransactions200Response) *NullableGetLoyaltyProgramTransactions200Response {
	return &NullableGetLoyaltyProgramTransactions200Response{value: val, isSet: true}
}

func (v NullableGetLoyaltyProgramTransactions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLoyaltyProgramTransactions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


