/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateAttributeValueBlock1Attribute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAttributeValueBlock1Attribute{}

// UpdateAttributeValueBlock1Attribute The attribute being updated.
type UpdateAttributeValueBlock1Attribute struct {
	// The internal ID of the attribute. Reverts to `0` when the attribute is deleted or does not exist.
	Id int64 `json:"id"`
	// The entity type that owns the attribute. Reverts to an empty string when the attribute is deleted or does not exist.
	Entity string `json:"entity"`
	// The attribute name as used in API requests.
	Name string `json:"name"`
	// The human-readable name of the attribute.
	Title string `json:"title"`
	// The data type of the attribute.
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAttributeValueBlock1Attribute UpdateAttributeValueBlock1Attribute

// NewUpdateAttributeValueBlock1Attribute instantiates a new UpdateAttributeValueBlock1Attribute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildUpdateAttributeValueBlock1Attribute(id int64, entity string, name string, title string, type_ string) *UpdateAttributeValueBlock1Attribute {
	this := UpdateAttributeValueBlock1Attribute{}
	this.Id = id
	this.Entity = entity
	this.Name = name
	this.Title = title
	this.Type = type_
	return &this
}

// NewUpdateAttributeValueBlock1AttributeWithDefaults instantiates a new UpdateAttributeValueBlock1Attribute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAttributeValueBlock1AttributeWithDefaults() *UpdateAttributeValueBlock1Attribute {
	this := UpdateAttributeValueBlock1Attribute{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateAttributeValueBlock1Attribute) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateAttributeValueBlock1Attribute) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateAttributeValueBlock1Attribute) SetId(v int64) {
	o.Id = v
}

// GetEntity returns the Entity field value
func (o *UpdateAttributeValueBlock1Attribute) GetEntity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *UpdateAttributeValueBlock1Attribute) GetEntityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *UpdateAttributeValueBlock1Attribute) SetEntity(v string) {
	o.Entity = v
}

// GetName returns the Name field value
func (o *UpdateAttributeValueBlock1Attribute) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateAttributeValueBlock1Attribute) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateAttributeValueBlock1Attribute) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *UpdateAttributeValueBlock1Attribute) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *UpdateAttributeValueBlock1Attribute) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *UpdateAttributeValueBlock1Attribute) SetTitle(v string) {
	o.Title = v
}

// GetType returns the Type field value
func (o *UpdateAttributeValueBlock1Attribute) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateAttributeValueBlock1Attribute) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateAttributeValueBlock1Attribute) SetType(v string) {
	o.Type = v
}

func (o UpdateAttributeValueBlock1Attribute) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAttributeValueBlock1Attribute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["entity"] = o.Entity
	toSerialize["name"] = o.Name
	toSerialize["title"] = o.Title
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAttributeValueBlock1Attribute) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"entity",
		"name",
		"title",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAttributeValueBlock1Attribute := _UpdateAttributeValueBlock1Attribute{}

	err = json.Unmarshal(data, &varUpdateAttributeValueBlock1Attribute)

	if err != nil {
		return err
	}

	*o = UpdateAttributeValueBlock1Attribute(varUpdateAttributeValueBlock1Attribute)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "entity")
		delete(additionalProperties, "name")
		delete(additionalProperties, "title")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAttributeValueBlock1Attribute struct {
	value *UpdateAttributeValueBlock1Attribute
	isSet bool
}

func (v NullableUpdateAttributeValueBlock1Attribute) Get() *UpdateAttributeValueBlock1Attribute {
	return v.value
}

func (v *NullableUpdateAttributeValueBlock1Attribute) Set(val *UpdateAttributeValueBlock1Attribute) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAttributeValueBlock1Attribute) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAttributeValueBlock1Attribute) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableUpdateAttributeValueBlock1Attribute(val *UpdateAttributeValueBlock1Attribute) *NullableUpdateAttributeValueBlock1Attribute {
	return &NullableUpdateAttributeValueBlock1Attribute{value: val, isSet: true}
}

func (v NullableUpdateAttributeValueBlock1Attribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAttributeValueBlock1Attribute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
