/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NewPicklist type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewPicklist{}

// NewPicklist struct for NewPicklist
type NewPicklist struct {
	// The type of allowed values in the picklist. If the type `time` is chosen, it must be an RFC3339 timestamp string.
	Type string `json:"type"`
	// The list of allowed values provided by this picklist.
	Values []string `json:"values"`
}

type _NewPicklist NewPicklist

// NewNewPicklist instantiates a new NewPicklist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildNewPicklist(type_ string, values []string) *NewPicklist {
	this := NewPicklist{}
	this.Type = type_
	this.Values = values
	return &this
}

// NewNewPicklistWithDefaults instantiates a new NewPicklist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewPicklistWithDefaults() *NewPicklist {
	this := NewPicklist{}
	return &this
}

// GetType returns the Type field value
func (o *NewPicklist) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NewPicklist) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NewPicklist) SetType(v string) {
	o.Type = v
}

// GetValues returns the Values field value
func (o *NewPicklist) GetValues() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *NewPicklist) GetValuesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *NewPicklist) SetValues(v []string) {
	o.Values = v
}

func (o NewPicklist) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewPicklist) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["values"] = o.Values
	return toSerialize, nil
}

func (o *NewPicklist) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewPicklist := _NewPicklist{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewPicklist)

	if err != nil {
		return err
	}

	*o = NewPicklist(varNewPicklist)

	return err
}

type NullableNewPicklist struct {
	value *NewPicklist
	isSet bool
}

func (v NullableNewPicklist) Get() *NewPicklist {
	return v.value
}

func (v *NullableNewPicklist) Set(val *NewPicklist) {
	v.value = val
	v.isSet = true
}

func (v NullableNewPicklist) IsSet() bool {
	return v.isSet
}

func (v *NullableNewPicklist) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableNewPicklist(val *NewPicklist) *NullableNewPicklist {
	return &NullableNewPicklist{value: val, isSet: true}
}

func (v NullableNewPicklist) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewPicklist) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
