/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetCustomerAchievementHistory200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustomerAchievementHistory200Response{}

// GetCustomerAchievementHistory200Response struct for GetCustomerAchievementHistory200Response
type GetCustomerAchievementHistory200Response struct {
	TotalResultSize int64 `json:"totalResultSize"`
	Data []AchievementProgress `json:"data"`
}

type _GetCustomerAchievementHistory200Response GetCustomerAchievementHistory200Response

// NewGetCustomerAchievementHistory200Response instantiates a new GetCustomerAchievementHistory200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildGetCustomerAchievementHistory200Response(totalResultSize int64, data []AchievementProgress) *GetCustomerAchievementHistory200Response {
	this := GetCustomerAchievementHistory200Response{}
	this.TotalResultSize = totalResultSize
	this.Data = data
	return &this
}

// NewGetCustomerAchievementHistory200ResponseWithDefaults instantiates a new GetCustomerAchievementHistory200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomerAchievementHistory200ResponseWithDefaults() *GetCustomerAchievementHistory200Response {
	this := GetCustomerAchievementHistory200Response{}
	return &this
}

// GetTotalResultSize returns the TotalResultSize field value
func (o *GetCustomerAchievementHistory200Response) GetTotalResultSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalResultSize
}

// GetTotalResultSizeOk returns a tuple with the TotalResultSize field value
// and a boolean to check if the value has been set.
func (o *GetCustomerAchievementHistory200Response) GetTotalResultSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalResultSize, true
}

// SetTotalResultSize sets field value
func (o *GetCustomerAchievementHistory200Response) SetTotalResultSize(v int64) {
	o.TotalResultSize = v
}

// GetData returns the Data field value
func (o *GetCustomerAchievementHistory200Response) GetData() []AchievementProgress {
	if o == nil {
		var ret []AchievementProgress
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetCustomerAchievementHistory200Response) GetDataOk() ([]AchievementProgress, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetCustomerAchievementHistory200Response) SetData(v []AchievementProgress) {
	o.Data = v
}

func (o GetCustomerAchievementHistory200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustomerAchievementHistory200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalResultSize"] = o.TotalResultSize
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetCustomerAchievementHistory200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"totalResultSize",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCustomerAchievementHistory200Response := _GetCustomerAchievementHistory200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCustomerAchievementHistory200Response)

	if err != nil {
		return err
	}

	*o = GetCustomerAchievementHistory200Response(varGetCustomerAchievementHistory200Response)

	return err
}

type NullableGetCustomerAchievementHistory200Response struct {
	value *GetCustomerAchievementHistory200Response
	isSet bool
}

func (v NullableGetCustomerAchievementHistory200Response) Get() *GetCustomerAchievementHistory200Response {
	return v.value
}

func (v *NullableGetCustomerAchievementHistory200Response) Set(val *GetCustomerAchievementHistory200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomerAchievementHistory200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomerAchievementHistory200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableGetCustomerAchievementHistory200Response(val *GetCustomerAchievementHistory200Response) *NullableGetCustomerAchievementHistory200Response {
	return &NullableGetCustomerAchievementHistory200Response{value: val, isSet: true}
}

func (v NullableGetCustomerAchievementHistory200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomerAchievementHistory200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


