/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the CheckAttributeBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckAttributeBlock{}

// CheckAttributeBlock struct for CheckAttributeBlock
type CheckAttributeBlock struct {
	// Unique identifier for this block.
	Id string `json:"id"`
	// Identifies the block variant and determines which additional properties are present in it.
	Type string `json:"type"`
	// Semantic labels attached to this block.
	Tags []string `json:"tags,omitempty"`
	// The comparison operator applied to the attribute.
	Operator string `json:"operator"`
	// The attribute path identifier (e.g. \"$Session.Total\").
	Attribute            string      `json:"attribute"`
	Value                interface{} `json:"value,omitempty"`
	Min                  interface{} `json:"min,omitempty"`
	Max                  interface{} `json:"max,omitempty"`
	Values               interface{} `json:"values,omitempty"`
	Count                interface{} `json:"count,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CheckAttributeBlock CheckAttributeBlock

// NewCheckAttributeBlock instantiates a new CheckAttributeBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCheckAttributeBlock(id string, type_ string, operator string, attribute string) *CheckAttributeBlock {
	this := CheckAttributeBlock{}
	this.Id = id
	this.Type = type_
	this.Operator = operator
	this.Attribute = attribute
	return &this
}

// NewCheckAttributeBlockWithDefaults instantiates a new CheckAttributeBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckAttributeBlockWithDefaults() *CheckAttributeBlock {
	this := CheckAttributeBlock{}
	return &this
}

// GetId returns the Id field value
func (o *CheckAttributeBlock) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CheckAttributeBlock) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CheckAttributeBlock) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CheckAttributeBlock) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CheckAttributeBlock) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CheckAttributeBlock) SetType(v string) {
	o.Type = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CheckAttributeBlock) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAttributeBlock) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CheckAttributeBlock) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CheckAttributeBlock) SetTags(v []string) {
	o.Tags = v
}

// GetOperator returns the Operator field value
func (o *CheckAttributeBlock) GetOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *CheckAttributeBlock) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *CheckAttributeBlock) SetOperator(v string) {
	o.Operator = v
}

// GetAttribute returns the Attribute field value
func (o *CheckAttributeBlock) GetAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attribute
}

// GetAttributeOk returns a tuple with the Attribute field value
// and a boolean to check if the value has been set.
func (o *CheckAttributeBlock) GetAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attribute, true
}

// SetAttribute sets field value
func (o *CheckAttributeBlock) SetAttribute(v string) {
	o.Attribute = v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckAttributeBlock) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckAttributeBlock) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CheckAttributeBlock) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *CheckAttributeBlock) SetValue(v interface{}) {
	o.Value = v
}

// GetMin returns the Min field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckAttributeBlock) GetMin() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckAttributeBlock) GetMinOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return &o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *CheckAttributeBlock) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given interface{} and assigns it to the Min field.
func (o *CheckAttributeBlock) SetMin(v interface{}) {
	o.Min = v
}

// GetMax returns the Max field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckAttributeBlock) GetMax() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckAttributeBlock) GetMaxOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return &o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *CheckAttributeBlock) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given interface{} and assigns it to the Max field.
func (o *CheckAttributeBlock) SetMax(v interface{}) {
	o.Max = v
}

// GetValues returns the Values field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckAttributeBlock) GetValues() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckAttributeBlock) GetValuesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return &o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *CheckAttributeBlock) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given interface{} and assigns it to the Values field.
func (o *CheckAttributeBlock) SetValues(v interface{}) {
	o.Values = v
}

// GetCount returns the Count field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CheckAttributeBlock) GetCount() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CheckAttributeBlock) GetCountOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return &o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *CheckAttributeBlock) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given interface{} and assigns it to the Count field.
func (o *CheckAttributeBlock) SetCount(v interface{}) {
	o.Count = v
}

func (o CheckAttributeBlock) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckAttributeBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["operator"] = o.Operator
	toSerialize["attribute"] = o.Attribute
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.Min != nil {
		toSerialize["min"] = o.Min
	}
	if o.Max != nil {
		toSerialize["max"] = o.Max
	}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CheckAttributeBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"operator",
		"attribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckAttributeBlock := _CheckAttributeBlock{}

	err = json.Unmarshal(data, &varCheckAttributeBlock)

	if err != nil {
		return err
	}

	*o = CheckAttributeBlock(varCheckAttributeBlock)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "operator")
		delete(additionalProperties, "attribute")
		delete(additionalProperties, "value")
		delete(additionalProperties, "min")
		delete(additionalProperties, "max")
		delete(additionalProperties, "values")
		delete(additionalProperties, "count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCheckAttributeBlock struct {
	value *CheckAttributeBlock
	isSet bool
}

func (v NullableCheckAttributeBlock) Get() *CheckAttributeBlock {
	return v.value
}

func (v *NullableCheckAttributeBlock) Set(val *CheckAttributeBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckAttributeBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckAttributeBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCheckAttributeBlock(val *CheckAttributeBlock) *NullableCheckAttributeBlock {
	return &NullableCheckAttributeBlock{value: val, isSet: true}
}

func (v NullableCheckAttributeBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckAttributeBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
