/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// checks if the UpdateLoyaltyCardRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateLoyaltyCardRequest{}

// UpdateLoyaltyCardRequest struct for UpdateLoyaltyCardRequest
type UpdateLoyaltyCardRequest struct {
	// Status of the loyalty card. Can be `active` or `inactive`.
	Status *string `json:"status,omitempty"`
}

// NewUpdateLoyaltyCardRequest instantiates a new UpdateLoyaltyCardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildUpdateLoyaltyCardRequest() *UpdateLoyaltyCardRequest {
	this := UpdateLoyaltyCardRequest{}
	return &this
}

// NewUpdateLoyaltyCardRequestWithDefaults instantiates a new UpdateLoyaltyCardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLoyaltyCardRequestWithDefaults() *UpdateLoyaltyCardRequest {
	this := UpdateLoyaltyCardRequest{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdateLoyaltyCardRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLoyaltyCardRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateLoyaltyCardRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *UpdateLoyaltyCardRequest) SetStatus(v string) {
	o.Status = &v
}

func (o UpdateLoyaltyCardRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateLoyaltyCardRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableUpdateLoyaltyCardRequest struct {
	value *UpdateLoyaltyCardRequest
	isSet bool
}

func (v NullableUpdateLoyaltyCardRequest) Get() *UpdateLoyaltyCardRequest {
	return v.value
}

func (v *NullableUpdateLoyaltyCardRequest) Set(val *UpdateLoyaltyCardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLoyaltyCardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLoyaltyCardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableUpdateLoyaltyCardRequest(val *UpdateLoyaltyCardRequest) *NullableUpdateLoyaltyCardRequest {
	return &NullableUpdateLoyaltyCardRequest{value: val, isSet: true}
}

func (v NullableUpdateLoyaltyCardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLoyaltyCardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
