/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the ReviewRisksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewRisksRequest{}

// ReviewRisksRequest struct for ReviewRisksRequest
type ReviewRisksRequest struct {
	// The IDs of the risks to move to `In review` status.
	RiskIds              []int64 `json:"riskIds"`
	AdditionalProperties map[string]interface{}
}

type _ReviewRisksRequest ReviewRisksRequest

// NewReviewRisksRequest instantiates a new ReviewRisksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildReviewRisksRequest(riskIds []int64) *ReviewRisksRequest {
	this := ReviewRisksRequest{}
	this.RiskIds = riskIds
	return &this
}

// NewReviewRisksRequestWithDefaults instantiates a new ReviewRisksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewRisksRequestWithDefaults() *ReviewRisksRequest {
	this := ReviewRisksRequest{}
	return &this
}

// GetRiskIds returns the RiskIds field value
func (o *ReviewRisksRequest) GetRiskIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.RiskIds
}

// GetRiskIdsOk returns a tuple with the RiskIds field value
// and a boolean to check if the value has been set.
func (o *ReviewRisksRequest) GetRiskIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RiskIds, true
}

// SetRiskIds sets field value
func (o *ReviewRisksRequest) SetRiskIds(v []int64) {
	o.RiskIds = v
}

func (o ReviewRisksRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewRisksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["riskIds"] = o.RiskIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReviewRisksRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"riskIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReviewRisksRequest := _ReviewRisksRequest{}

	err = json.Unmarshal(data, &varReviewRisksRequest)

	if err != nil {
		return err
	}

	*o = ReviewRisksRequest(varReviewRisksRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "riskIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReviewRisksRequest struct {
	value *ReviewRisksRequest
	isSet bool
}

func (v NullableReviewRisksRequest) Get() *ReviewRisksRequest {
	return v.value
}

func (v *NullableReviewRisksRequest) Set(val *ReviewRisksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewRisksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewRisksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableReviewRisksRequest(val *ReviewRisksRequest) *NullableReviewRisksRequest {
	return &NullableReviewRisksRequest{value: val, isSet: true}
}

func (v NullableReviewRisksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewRisksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
