/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction{}

// PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction struct for PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction
type PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction struct {
	Amount     float32    `json:"Amount"`
	Reason     *string    `json:"Reason,omitempty"`
	Operation  string     `json:"Operation"`
	StartDate  *time.Time `json:"StartDate,omitempty"`
	ExpiryDate *time.Time `json:"ExpiryDate,omitempty"`
}

type _PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction

// NewPrismaticEventPayloadLoyaltyProfileBasedNotificationsAction instantiates a new PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildPrismaticEventPayloadLoyaltyProfileBasedNotificationsAction(amount float32, operation string) *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction {
	this := PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction{}
	this.Amount = amount
	this.Operation = operation
	return &this
}

// NewPrismaticEventPayloadLoyaltyProfileBasedNotificationsActionWithDefaults instantiates a new PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrismaticEventPayloadLoyaltyProfileBasedNotificationsActionWithDefaults() *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction {
	this := PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction{}
	return &this
}

// GetAmount returns the Amount field value
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) SetAmount(v float32) {
	o.Amount = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) SetReason(v string) {
	o.Reason = &v
}

// GetOperation returns the Operation field value
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) SetOperation(v string) {
	o.Operation = v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetExpiryDate() time.Time {
	if o == nil || IsNil(o.ExpiryDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) GetExpiryDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiryDate) {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) HasExpiryDate() bool {
	if o != nil && !IsNil(o.ExpiryDate) {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given time.Time and assigns it to the ExpiryDate field.
func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) SetExpiryDate(v time.Time) {
	o.ExpiryDate = &v
}

func (o PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Amount"] = o.Amount
	if !IsNil(o.Reason) {
		toSerialize["Reason"] = o.Reason
	}
	toSerialize["Operation"] = o.Operation
	if !IsNil(o.StartDate) {
		toSerialize["StartDate"] = o.StartDate
	}
	if !IsNil(o.ExpiryDate) {
		toSerialize["ExpiryDate"] = o.ExpiryDate
	}
	return toSerialize, nil
}

func (o *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Amount",
		"Operation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrismaticEventPayloadLoyaltyProfileBasedNotificationsAction := _PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrismaticEventPayloadLoyaltyProfileBasedNotificationsAction)

	if err != nil {
		return err
	}

	*o = PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction(varPrismaticEventPayloadLoyaltyProfileBasedNotificationsAction)

	return err
}

type NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction struct {
	value *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction
	isSet bool
}

func (v NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) Get() *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction {
	return v.value
}

func (v *NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) Set(val *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) {
	v.value = val
	v.isSet = true
}

func (v NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) IsSet() bool {
	return v.isSet
}

func (v *NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction(val *PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) *NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction {
	return &NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction{value: val, isSet: true}
}

func (v NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrismaticEventPayloadLoyaltyProfileBasedNotificationsAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
