/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectedTier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectedTier{}

// ProjectedTier struct for ProjectedTier
type ProjectedTier struct {
	// The active points of the customer when their current tier expires.
	ProjectedActivePoints float32 `json:"projectedActivePoints"`
	// The number of points the customer needs to stay in the current tier.  **Note**: This is included in the response when the customer is projected to be downgraded. 
	StayInTierPoints *float32 `json:"stayInTierPoints,omitempty"`
	// The name of the tier the user will enter once their current tier expires.
	ProjectedTierName *string `json:"projectedTierName,omitempty"`
}

type _ProjectedTier ProjectedTier

// NewProjectedTier instantiates a new ProjectedTier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildProjectedTier(projectedActivePoints float32) *ProjectedTier {
	this := ProjectedTier{}
	this.ProjectedActivePoints = projectedActivePoints
	return &this
}

// NewProjectedTierWithDefaults instantiates a new ProjectedTier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectedTierWithDefaults() *ProjectedTier {
	this := ProjectedTier{}
	return &this
}

// GetProjectedActivePoints returns the ProjectedActivePoints field value
func (o *ProjectedTier) GetProjectedActivePoints() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProjectedActivePoints
}

// GetProjectedActivePointsOk returns a tuple with the ProjectedActivePoints field value
// and a boolean to check if the value has been set.
func (o *ProjectedTier) GetProjectedActivePointsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectedActivePoints, true
}

// SetProjectedActivePoints sets field value
func (o *ProjectedTier) SetProjectedActivePoints(v float32) {
	o.ProjectedActivePoints = v
}

// GetStayInTierPoints returns the StayInTierPoints field value if set, zero value otherwise.
func (o *ProjectedTier) GetStayInTierPoints() float32 {
	if o == nil || IsNil(o.StayInTierPoints) {
		var ret float32
		return ret
	}
	return *o.StayInTierPoints
}

// GetStayInTierPointsOk returns a tuple with the StayInTierPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectedTier) GetStayInTierPointsOk() (*float32, bool) {
	if o == nil || IsNil(o.StayInTierPoints) {
		return nil, false
	}
	return o.StayInTierPoints, true
}

// HasStayInTierPoints returns a boolean if a field has been set.
func (o *ProjectedTier) HasStayInTierPoints() bool {
	if o != nil && !IsNil(o.StayInTierPoints) {
		return true
	}

	return false
}

// SetStayInTierPoints gets a reference to the given float32 and assigns it to the StayInTierPoints field.
func (o *ProjectedTier) SetStayInTierPoints(v float32) {
	o.StayInTierPoints = &v
}

// GetProjectedTierName returns the ProjectedTierName field value if set, zero value otherwise.
func (o *ProjectedTier) GetProjectedTierName() string {
	if o == nil || IsNil(o.ProjectedTierName) {
		var ret string
		return ret
	}
	return *o.ProjectedTierName
}

// GetProjectedTierNameOk returns a tuple with the ProjectedTierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectedTier) GetProjectedTierNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectedTierName) {
		return nil, false
	}
	return o.ProjectedTierName, true
}

// HasProjectedTierName returns a boolean if a field has been set.
func (o *ProjectedTier) HasProjectedTierName() bool {
	if o != nil && !IsNil(o.ProjectedTierName) {
		return true
	}

	return false
}

// SetProjectedTierName gets a reference to the given string and assigns it to the ProjectedTierName field.
func (o *ProjectedTier) SetProjectedTierName(v string) {
	o.ProjectedTierName = &v
}

func (o ProjectedTier) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectedTier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectedActivePoints"] = o.ProjectedActivePoints
	if !IsNil(o.StayInTierPoints) {
		toSerialize["stayInTierPoints"] = o.StayInTierPoints
	}
	if !IsNil(o.ProjectedTierName) {
		toSerialize["projectedTierName"] = o.ProjectedTierName
	}
	return toSerialize, nil
}

func (o *ProjectedTier) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectedActivePoints",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectedTier := _ProjectedTier{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectedTier)

	if err != nil {
		return err
	}

	*o = ProjectedTier(varProjectedTier)

	return err
}

type NullableProjectedTier struct {
	value *ProjectedTier
	isSet bool
}

func (v NullableProjectedTier) Get() *ProjectedTier {
	return v.value
}

func (v *NullableProjectedTier) Set(val *ProjectedTier) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectedTier) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectedTier) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableProjectedTier(val *ProjectedTier) *NullableProjectedTier {
	return &NullableProjectedTier{value: val, isSet: true}
}

func (v NullableProjectedTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectedTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


