/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the IntegrationCampaignBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationCampaignBase{}

// IntegrationCampaignBase struct for IntegrationCampaignBase
type IntegrationCampaignBase struct {
	// The ID of the Application that owns this entity.
	ApplicationId int64 `json:"applicationId"`
	// Unique ID of Campaign.
	Id int64 `json:"id"`
	// The name of the campaign.
	Name string `json:"name"`
	// A detailed description of the campaign.
	Description *string `json:"description,omitempty"`
	// Timestamp when the campaign will become active.
	StartTime *time.Time `json:"startTime,omitempty"`
	// Timestamp when the campaign will become inactive.
	EndTime *time.Time `json:"endTime,omitempty"`
	// Arbitrary properties associated with this campaign.
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	// The state of the campaign.
	State string `json:"state"`
	// A list of tags for the campaign.
	Tags []string `json:"tags"`
	// The features enabled in this campaign.
	Features             []string `json:"features"`
	AdditionalProperties map[string]interface{}
}

type _IntegrationCampaignBase IntegrationCampaignBase

// NewIntegrationCampaignBase instantiates a new IntegrationCampaignBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildIntegrationCampaignBase(applicationId int64, id int64, name string, state string, tags []string, features []string) *IntegrationCampaignBase {
	this := IntegrationCampaignBase{}
	this.ApplicationId = applicationId
	this.Id = id
	this.Name = name
	this.State = state
	this.Tags = tags
	this.Features = features
	return &this
}

// NewIntegrationCampaignBaseWithDefaults instantiates a new IntegrationCampaignBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationCampaignBaseWithDefaults() *IntegrationCampaignBase {
	this := IntegrationCampaignBase{}
	var state string = "enabled"
	this.State = state
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *IntegrationCampaignBase) GetApplicationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetApplicationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *IntegrationCampaignBase) SetApplicationId(v int64) {
	o.ApplicationId = v
}

// GetId returns the Id field value
func (o *IntegrationCampaignBase) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IntegrationCampaignBase) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *IntegrationCampaignBase) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IntegrationCampaignBase) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IntegrationCampaignBase) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IntegrationCampaignBase) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IntegrationCampaignBase) SetDescription(v string) {
	o.Description = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *IntegrationCampaignBase) GetStartTime() time.Time {
	if o == nil || IsNil(o.StartTime) {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *IntegrationCampaignBase) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *IntegrationCampaignBase) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *IntegrationCampaignBase) GetEndTime() time.Time {
	if o == nil || IsNil(o.EndTime) {
		var ret time.Time
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetEndTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *IntegrationCampaignBase) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given time.Time and assigns it to the EndTime field.
func (o *IntegrationCampaignBase) SetEndTime(v time.Time) {
	o.EndTime = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *IntegrationCampaignBase) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *IntegrationCampaignBase) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *IntegrationCampaignBase) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetState returns the State field value
func (o *IntegrationCampaignBase) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *IntegrationCampaignBase) SetState(v string) {
	o.State = v
}

// GetTags returns the Tags field value
func (o *IntegrationCampaignBase) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *IntegrationCampaignBase) SetTags(v []string) {
	o.Tags = v
}

// GetFeatures returns the Features field value
func (o *IntegrationCampaignBase) GetFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *IntegrationCampaignBase) GetFeaturesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *IntegrationCampaignBase) SetFeatures(v []string) {
	o.Features = v
}

func (o IntegrationCampaignBase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationCampaignBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applicationId"] = o.ApplicationId
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	if !IsNil(o.EndTime) {
		toSerialize["endTime"] = o.EndTime
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	toSerialize["state"] = o.State
	toSerialize["tags"] = o.Tags
	toSerialize["features"] = o.Features

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IntegrationCampaignBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applicationId",
		"id",
		"name",
		"state",
		"tags",
		"features",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrationCampaignBase := _IntegrationCampaignBase{}

	err = json.Unmarshal(data, &varIntegrationCampaignBase)

	if err != nil {
		return err
	}

	*o = IntegrationCampaignBase(varIntegrationCampaignBase)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "applicationId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "startTime")
		delete(additionalProperties, "endTime")
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "state")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "features")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIntegrationCampaignBase struct {
	value *IntegrationCampaignBase
	isSet bool
}

func (v NullableIntegrationCampaignBase) Get() *IntegrationCampaignBase {
	return v.value
}

func (v *NullableIntegrationCampaignBase) Set(val *IntegrationCampaignBase) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationCampaignBase) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationCampaignBase) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableIntegrationCampaignBase(val *IntegrationCampaignBase) *NullableIntegrationCampaignBase {
	return &NullableIntegrationCampaignBase{value: val, isSet: true}
}

func (v NullableIntegrationCampaignBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationCampaignBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
