/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NewCouponCreationJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewCouponCreationJob{}

// NewCouponCreationJob struct for NewCouponCreationJob
type NewCouponCreationJob struct {
	// The number of times the coupon code can be redeemed. `0` means unlimited redemptions but any campaign usage limits will still apply. 
	UsageLimit *int64 `json:"usageLimit,omitempty"`
	// The total discount value that the code can give. Typically used to represent a gift card value. 
	DiscountLimit *float32 `json:"discountLimit,omitempty"`
	// The number of reservations that can be made with this coupon code. 
	ReservationLimit *int64 `json:"reservationLimit,omitempty"`
	// Timestamp at which point the coupon becomes valid.
	StartDate *time.Time `json:"startDate,omitempty"`
	// Expiration date of the coupon. Coupon never expires if this is omitted.
	ExpiryDate *time.Time `json:"expiryDate,omitempty"`
	// The number of new coupon codes to generate for the campaign.
	NumberOfCoupons int64 `json:"numberOfCoupons"`
	CouponSettings *CodeGeneratorSettings `json:"couponSettings,omitempty"`
	// Arbitrary properties associated with coupons.
	Attributes map[string]interface{} `json:"attributes"`
}

type _NewCouponCreationJob NewCouponCreationJob

// NewNewCouponCreationJob instantiates a new NewCouponCreationJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewCouponCreationJob(numberOfCoupons int64, attributes map[string]interface{}) *NewCouponCreationJob {
	this := NewCouponCreationJob{}
	this.NumberOfCoupons = numberOfCoupons
	this.Attributes = attributes
	return &this
}

// NewNewCouponCreationJobWithDefaults instantiates a new NewCouponCreationJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewCouponCreationJobWithDefaults() *NewCouponCreationJob {
	this := NewCouponCreationJob{}
	return &this
}

// GetUsageLimit returns the UsageLimit field value if set, zero value otherwise.
func (o *NewCouponCreationJob) GetUsageLimit() int64 {
	if o == nil || IsNil(o.UsageLimit) {
		var ret int64
		return ret
	}
	return *o.UsageLimit
}

// GetUsageLimitOk returns a tuple with the UsageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetUsageLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.UsageLimit) {
		return nil, false
	}
	return o.UsageLimit, true
}

// HasUsageLimit returns a boolean if a field has been set.
func (o *NewCouponCreationJob) HasUsageLimit() bool {
	if o != nil && !IsNil(o.UsageLimit) {
		return true
	}

	return false
}

// SetUsageLimit gets a reference to the given int64 and assigns it to the UsageLimit field.
func (o *NewCouponCreationJob) SetUsageLimit(v int64) {
	o.UsageLimit = &v
}

// GetDiscountLimit returns the DiscountLimit field value if set, zero value otherwise.
func (o *NewCouponCreationJob) GetDiscountLimit() float32 {
	if o == nil || IsNil(o.DiscountLimit) {
		var ret float32
		return ret
	}
	return *o.DiscountLimit
}

// GetDiscountLimitOk returns a tuple with the DiscountLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetDiscountLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.DiscountLimit) {
		return nil, false
	}
	return o.DiscountLimit, true
}

// HasDiscountLimit returns a boolean if a field has been set.
func (o *NewCouponCreationJob) HasDiscountLimit() bool {
	if o != nil && !IsNil(o.DiscountLimit) {
		return true
	}

	return false
}

// SetDiscountLimit gets a reference to the given float32 and assigns it to the DiscountLimit field.
func (o *NewCouponCreationJob) SetDiscountLimit(v float32) {
	o.DiscountLimit = &v
}

// GetReservationLimit returns the ReservationLimit field value if set, zero value otherwise.
func (o *NewCouponCreationJob) GetReservationLimit() int64 {
	if o == nil || IsNil(o.ReservationLimit) {
		var ret int64
		return ret
	}
	return *o.ReservationLimit
}

// GetReservationLimitOk returns a tuple with the ReservationLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetReservationLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.ReservationLimit) {
		return nil, false
	}
	return o.ReservationLimit, true
}

// HasReservationLimit returns a boolean if a field has been set.
func (o *NewCouponCreationJob) HasReservationLimit() bool {
	if o != nil && !IsNil(o.ReservationLimit) {
		return true
	}

	return false
}

// SetReservationLimit gets a reference to the given int64 and assigns it to the ReservationLimit field.
func (o *NewCouponCreationJob) SetReservationLimit(v int64) {
	o.ReservationLimit = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *NewCouponCreationJob) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *NewCouponCreationJob) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *NewCouponCreationJob) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *NewCouponCreationJob) GetExpiryDate() time.Time {
	if o == nil || IsNil(o.ExpiryDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetExpiryDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiryDate) {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *NewCouponCreationJob) HasExpiryDate() bool {
	if o != nil && !IsNil(o.ExpiryDate) {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given time.Time and assigns it to the ExpiryDate field.
func (o *NewCouponCreationJob) SetExpiryDate(v time.Time) {
	o.ExpiryDate = &v
}

// GetNumberOfCoupons returns the NumberOfCoupons field value
func (o *NewCouponCreationJob) GetNumberOfCoupons() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NumberOfCoupons
}

// GetNumberOfCouponsOk returns a tuple with the NumberOfCoupons field value
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetNumberOfCouponsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumberOfCoupons, true
}

// SetNumberOfCoupons sets field value
func (o *NewCouponCreationJob) SetNumberOfCoupons(v int64) {
	o.NumberOfCoupons = v
}

// GetCouponSettings returns the CouponSettings field value if set, zero value otherwise.
func (o *NewCouponCreationJob) GetCouponSettings() CodeGeneratorSettings {
	if o == nil || IsNil(o.CouponSettings) {
		var ret CodeGeneratorSettings
		return ret
	}
	return *o.CouponSettings
}

// GetCouponSettingsOk returns a tuple with the CouponSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetCouponSettingsOk() (*CodeGeneratorSettings, bool) {
	if o == nil || IsNil(o.CouponSettings) {
		return nil, false
	}
	return o.CouponSettings, true
}

// HasCouponSettings returns a boolean if a field has been set.
func (o *NewCouponCreationJob) HasCouponSettings() bool {
	if o != nil && !IsNil(o.CouponSettings) {
		return true
	}

	return false
}

// SetCouponSettings gets a reference to the given CodeGeneratorSettings and assigns it to the CouponSettings field.
func (o *NewCouponCreationJob) SetCouponSettings(v CodeGeneratorSettings) {
	o.CouponSettings = &v
}

// GetAttributes returns the Attributes field value
func (o *NewCouponCreationJob) GetAttributes() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *NewCouponCreationJob) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// SetAttributes sets field value
func (o *NewCouponCreationJob) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

func (o NewCouponCreationJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewCouponCreationJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UsageLimit) {
		toSerialize["usageLimit"] = o.UsageLimit
	}
	if !IsNil(o.DiscountLimit) {
		toSerialize["discountLimit"] = o.DiscountLimit
	}
	if !IsNil(o.ReservationLimit) {
		toSerialize["reservationLimit"] = o.ReservationLimit
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.ExpiryDate) {
		toSerialize["expiryDate"] = o.ExpiryDate
	}
	toSerialize["numberOfCoupons"] = o.NumberOfCoupons
	if !IsNil(o.CouponSettings) {
		toSerialize["couponSettings"] = o.CouponSettings
	}
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *NewCouponCreationJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"numberOfCoupons",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewCouponCreationJob := _NewCouponCreationJob{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewCouponCreationJob)

	if err != nil {
		return err
	}

	*o = NewCouponCreationJob(varNewCouponCreationJob)

	return err
}

type NullableNewCouponCreationJob struct {
	value *NewCouponCreationJob
	isSet bool
}

func (v NullableNewCouponCreationJob) Get() *NewCouponCreationJob {
	return v.value
}

func (v *NullableNewCouponCreationJob) Set(val *NewCouponCreationJob) {
	v.value = val
	v.isSet = true
}

func (v NullableNewCouponCreationJob) IsSet() bool {
	return v.isSet
}

func (v *NullableNewCouponCreationJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewCouponCreationJob(val *NewCouponCreationJob) *NullableNewCouponCreationJob {
	return &NullableNewCouponCreationJob{value: val, isSet: true}
}

func (v NullableNewCouponCreationJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewCouponCreationJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


