/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the LoyaltyMembership type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoyaltyMembership{}

// LoyaltyMembership struct for LoyaltyMembership
type LoyaltyMembership struct {
	// The moment in which the loyalty program was joined.
	Joined *time.Time `json:"joined,omitempty"`
	// The ID of the loyalty program belonging to this entity.
	LoyaltyProgramId int64 `json:"loyaltyProgramId"`
}

type _LoyaltyMembership LoyaltyMembership

// NewLoyaltyMembership instantiates a new LoyaltyMembership object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoyaltyMembership(loyaltyProgramId int64) *LoyaltyMembership {
	this := LoyaltyMembership{}
	this.LoyaltyProgramId = loyaltyProgramId
	return &this
}

// NewLoyaltyMembershipWithDefaults instantiates a new LoyaltyMembership object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoyaltyMembershipWithDefaults() *LoyaltyMembership {
	this := LoyaltyMembership{}
	return &this
}

// GetJoined returns the Joined field value if set, zero value otherwise.
func (o *LoyaltyMembership) GetJoined() time.Time {
	if o == nil || IsNil(o.Joined) {
		var ret time.Time
		return ret
	}
	return *o.Joined
}

// GetJoinedOk returns a tuple with the Joined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoyaltyMembership) GetJoinedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Joined) {
		return nil, false
	}
	return o.Joined, true
}

// HasJoined returns a boolean if a field has been set.
func (o *LoyaltyMembership) HasJoined() bool {
	if o != nil && !IsNil(o.Joined) {
		return true
	}

	return false
}

// SetJoined gets a reference to the given time.Time and assigns it to the Joined field.
func (o *LoyaltyMembership) SetJoined(v time.Time) {
	o.Joined = &v
}

// GetLoyaltyProgramId returns the LoyaltyProgramId field value
func (o *LoyaltyMembership) GetLoyaltyProgramId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LoyaltyProgramId
}

// GetLoyaltyProgramIdOk returns a tuple with the LoyaltyProgramId field value
// and a boolean to check if the value has been set.
func (o *LoyaltyMembership) GetLoyaltyProgramIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoyaltyProgramId, true
}

// SetLoyaltyProgramId sets field value
func (o *LoyaltyMembership) SetLoyaltyProgramId(v int64) {
	o.LoyaltyProgramId = v
}

func (o LoyaltyMembership) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoyaltyMembership) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Joined) {
		toSerialize["joined"] = o.Joined
	}
	toSerialize["loyaltyProgramId"] = o.LoyaltyProgramId
	return toSerialize, nil
}

func (o *LoyaltyMembership) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"loyaltyProgramId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoyaltyMembership := _LoyaltyMembership{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoyaltyMembership)

	if err != nil {
		return err
	}

	*o = LoyaltyMembership(varLoyaltyMembership)

	return err
}

type NullableLoyaltyMembership struct {
	value *LoyaltyMembership
	isSet bool
}

func (v NullableLoyaltyMembership) Get() *LoyaltyMembership {
	return v.value
}

func (v *NullableLoyaltyMembership) Set(val *LoyaltyMembership) {
	v.value = val
	v.isSet = true
}

func (v NullableLoyaltyMembership) IsSet() bool {
	return v.isSet
}

func (v *NullableLoyaltyMembership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoyaltyMembership(val *LoyaltyMembership) *NullableLoyaltyMembership {
	return &NullableLoyaltyMembership{value: val, isSet: true}
}

func (v NullableLoyaltyMembership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoyaltyMembership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


