/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GenerateAuditLogSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateAuditLogSummary{}

// GenerateAuditLogSummary struct for GenerateAuditLogSummary
type GenerateAuditLogSummary struct {
	// The ID of the audit log.
	LogID int64 `json:"logID"`
}

type _GenerateAuditLogSummary GenerateAuditLogSummary

// NewGenerateAuditLogSummary instantiates a new GenerateAuditLogSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateAuditLogSummary(logID int64) *GenerateAuditLogSummary {
	this := GenerateAuditLogSummary{}
	this.LogID = logID
	return &this
}

// NewGenerateAuditLogSummaryWithDefaults instantiates a new GenerateAuditLogSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateAuditLogSummaryWithDefaults() *GenerateAuditLogSummary {
	this := GenerateAuditLogSummary{}
	return &this
}

// GetLogID returns the LogID field value
func (o *GenerateAuditLogSummary) GetLogID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LogID
}

// GetLogIDOk returns a tuple with the LogID field value
// and a boolean to check if the value has been set.
func (o *GenerateAuditLogSummary) GetLogIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogID, true
}

// SetLogID sets field value
func (o *GenerateAuditLogSummary) SetLogID(v int64) {
	o.LogID = v
}

func (o GenerateAuditLogSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateAuditLogSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logID"] = o.LogID
	return toSerialize, nil
}

func (o *GenerateAuditLogSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenerateAuditLogSummary := _GenerateAuditLogSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenerateAuditLogSummary)

	if err != nil {
		return err
	}

	*o = GenerateAuditLogSummary(varGenerateAuditLogSummary)

	return err
}

type NullableGenerateAuditLogSummary struct {
	value *GenerateAuditLogSummary
	isSet bool
}

func (v NullableGenerateAuditLogSummary) Get() *GenerateAuditLogSummary {
	return v.value
}

func (v *NullableGenerateAuditLogSummary) Set(val *GenerateAuditLogSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateAuditLogSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateAuditLogSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateAuditLogSummary(val *GenerateAuditLogSummary) *NullableGenerateAuditLogSummary {
	return &NullableGenerateAuditLogSummary{value: val, isSet: true}
}

func (v NullableGenerateAuditLogSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateAuditLogSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


