/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AudienceReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudienceReference{}

// AudienceReference struct for AudienceReference
type AudienceReference struct {
	// The ID of this audience in the third-party integration.
	IntegrationId *string `json:"integrationId,omitempty"`
	// The ID of the audience.
	Id int64 `json:"id"`
	// The third-party integration of the audience.
	Integration *string `json:"integration,omitempty"`
}

type _AudienceReference AudienceReference

// NewAudienceReference instantiates a new AudienceReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildAudienceReference(id int64) *AudienceReference {
	this := AudienceReference{}
	this.Id = id
	return &this
}

// NewAudienceReferenceWithDefaults instantiates a new AudienceReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceReferenceWithDefaults() *AudienceReference {
	this := AudienceReference{}
	return &this
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise.
func (o *AudienceReference) GetIntegrationId() string {
	if o == nil || IsNil(o.IntegrationId) {
		var ret string
		return ret
	}
	return *o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceReference) GetIntegrationIdOk() (*string, bool) {
	if o == nil || IsNil(o.IntegrationId) {
		return nil, false
	}
	return o.IntegrationId, true
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *AudienceReference) HasIntegrationId() bool {
	if o != nil && !IsNil(o.IntegrationId) {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given string and assigns it to the IntegrationId field.
func (o *AudienceReference) SetIntegrationId(v string) {
	o.IntegrationId = &v
}

// GetId returns the Id field value
func (o *AudienceReference) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AudienceReference) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AudienceReference) SetId(v int64) {
	o.Id = v
}

// GetIntegration returns the Integration field value if set, zero value otherwise.
func (o *AudienceReference) GetIntegration() string {
	if o == nil || IsNil(o.Integration) {
		var ret string
		return ret
	}
	return *o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceReference) GetIntegrationOk() (*string, bool) {
	if o == nil || IsNil(o.Integration) {
		return nil, false
	}
	return o.Integration, true
}

// HasIntegration returns a boolean if a field has been set.
func (o *AudienceReference) HasIntegration() bool {
	if o != nil && !IsNil(o.Integration) {
		return true
	}

	return false
}

// SetIntegration gets a reference to the given string and assigns it to the Integration field.
func (o *AudienceReference) SetIntegration(v string) {
	o.Integration = &v
}

func (o AudienceReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudienceReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IntegrationId) {
		toSerialize["integrationId"] = o.IntegrationId
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Integration) {
		toSerialize["integration"] = o.Integration
	}
	return toSerialize, nil
}

func (o *AudienceReference) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAudienceReference := _AudienceReference{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAudienceReference)

	if err != nil {
		return err
	}

	*o = AudienceReference(varAudienceReference)

	return err
}

type NullableAudienceReference struct {
	value *AudienceReference
	isSet bool
}

func (v NullableAudienceReference) Get() *AudienceReference {
	return v.value
}

func (v *NullableAudienceReference) Set(val *AudienceReference) {
	v.value = val
	v.isSet = true
}

func (v NullableAudienceReference) IsSet() bool {
	return v.isSet
}

func (v *NullableAudienceReference) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableAudienceReference(val *AudienceReference) *NullableAudienceReference {
	return &NullableAudienceReference{value: val, isSet: true}
}

func (v NullableAudienceReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudienceReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
