/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the IntegrationRewardsCatalog200ResponseCatalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationRewardsCatalog200ResponseCatalog{}

// IntegrationRewardsCatalog200ResponseCatalog The paginated rewards catalog.
type IntegrationRewardsCatalog200ResponseCatalog struct {
	// Whether more pages exist after the current one.
	HasMore              bool                `json:"hasMore"`
	Data                 []RewardCatalogItem `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _IntegrationRewardsCatalog200ResponseCatalog IntegrationRewardsCatalog200ResponseCatalog

// NewIntegrationRewardsCatalog200ResponseCatalog instantiates a new IntegrationRewardsCatalog200ResponseCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildIntegrationRewardsCatalog200ResponseCatalog(hasMore bool, data []RewardCatalogItem) *IntegrationRewardsCatalog200ResponseCatalog {
	this := IntegrationRewardsCatalog200ResponseCatalog{}
	this.HasMore = hasMore
	this.Data = data
	return &this
}

// NewIntegrationRewardsCatalog200ResponseCatalogWithDefaults instantiates a new IntegrationRewardsCatalog200ResponseCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationRewardsCatalog200ResponseCatalogWithDefaults() *IntegrationRewardsCatalog200ResponseCatalog {
	this := IntegrationRewardsCatalog200ResponseCatalog{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *IntegrationRewardsCatalog200ResponseCatalog) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *IntegrationRewardsCatalog200ResponseCatalog) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *IntegrationRewardsCatalog200ResponseCatalog) SetHasMore(v bool) {
	o.HasMore = v
}

// GetData returns the Data field value
func (o *IntegrationRewardsCatalog200ResponseCatalog) GetData() []RewardCatalogItem {
	if o == nil {
		var ret []RewardCatalogItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *IntegrationRewardsCatalog200ResponseCatalog) GetDataOk() ([]RewardCatalogItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *IntegrationRewardsCatalog200ResponseCatalog) SetData(v []RewardCatalogItem) {
	o.Data = v
}

func (o IntegrationRewardsCatalog200ResponseCatalog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationRewardsCatalog200ResponseCatalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hasMore"] = o.HasMore
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IntegrationRewardsCatalog200ResponseCatalog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hasMore",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrationRewardsCatalog200ResponseCatalog := _IntegrationRewardsCatalog200ResponseCatalog{}

	err = json.Unmarshal(data, &varIntegrationRewardsCatalog200ResponseCatalog)

	if err != nil {
		return err
	}

	*o = IntegrationRewardsCatalog200ResponseCatalog(varIntegrationRewardsCatalog200ResponseCatalog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "hasMore")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIntegrationRewardsCatalog200ResponseCatalog struct {
	value *IntegrationRewardsCatalog200ResponseCatalog
	isSet bool
}

func (v NullableIntegrationRewardsCatalog200ResponseCatalog) Get() *IntegrationRewardsCatalog200ResponseCatalog {
	return v.value
}

func (v *NullableIntegrationRewardsCatalog200ResponseCatalog) Set(val *IntegrationRewardsCatalog200ResponseCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationRewardsCatalog200ResponseCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationRewardsCatalog200ResponseCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableIntegrationRewardsCatalog200ResponseCatalog(val *IntegrationRewardsCatalog200ResponseCatalog) *NullableIntegrationRewardsCatalog200ResponseCatalog {
	return &NullableIntegrationRewardsCatalog200ResponseCatalog{value: val, isSet: true}
}

func (v NullableIntegrationRewardsCatalog200ResponseCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationRewardsCatalog200ResponseCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
