/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the TriggerCustomEffectBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerCustomEffectBlock{}

// TriggerCustomEffectBlock struct for TriggerCustomEffectBlock
type TriggerCustomEffectBlock struct {
	// Unique identifier for this block.
	Id *string `json:"id,omitempty"`
	// Identifies the block variant and determines which additional properties are present in it.
	Type string `json:"type"`
	// Semantic labels attached to this block.
	Tags         []string                              `json:"tags,omitempty"`
	CustomEffect TriggerCustomEffectBlock1CustomEffect `json:"customEffect"`
	// The custom effect's parameters, in configured order. Each property name is the parameter's title, lowercased with spaces replaced by underscores (for example, `Order ID` becomes `order_id`); falls back to `param_0`, `param_1`, and so on if a title is blank or collides with another.
	Params map[string]interface{}          `json:"params,omitempty"`
	Target TriggerCustomEffectBlock1Target `json:"target"`
	// Named error handlers evaluated when a specific error occurs.
	OnError              map[string][]Block `json:"onError,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TriggerCustomEffectBlock TriggerCustomEffectBlock

// NewTriggerCustomEffectBlock instantiates a new TriggerCustomEffectBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildTriggerCustomEffectBlock(type_ string, customEffect TriggerCustomEffectBlock1CustomEffect, target TriggerCustomEffectBlock1Target) *TriggerCustomEffectBlock {
	this := TriggerCustomEffectBlock{}
	this.Type = type_
	this.CustomEffect = customEffect
	this.Target = target
	return &this
}

// NewTriggerCustomEffectBlockWithDefaults instantiates a new TriggerCustomEffectBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerCustomEffectBlockWithDefaults() *TriggerCustomEffectBlock {
	this := TriggerCustomEffectBlock{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TriggerCustomEffectBlock) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerCustomEffectBlock) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TriggerCustomEffectBlock) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TriggerCustomEffectBlock) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value
func (o *TriggerCustomEffectBlock) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TriggerCustomEffectBlock) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TriggerCustomEffectBlock) SetType(v string) {
	o.Type = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *TriggerCustomEffectBlock) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerCustomEffectBlock) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *TriggerCustomEffectBlock) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *TriggerCustomEffectBlock) SetTags(v []string) {
	o.Tags = v
}

// GetCustomEffect returns the CustomEffect field value
func (o *TriggerCustomEffectBlock) GetCustomEffect() TriggerCustomEffectBlock1CustomEffect {
	if o == nil {
		var ret TriggerCustomEffectBlock1CustomEffect
		return ret
	}

	return o.CustomEffect
}

// GetCustomEffectOk returns a tuple with the CustomEffect field value
// and a boolean to check if the value has been set.
func (o *TriggerCustomEffectBlock) GetCustomEffectOk() (*TriggerCustomEffectBlock1CustomEffect, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomEffect, true
}

// SetCustomEffect sets field value
func (o *TriggerCustomEffectBlock) SetCustomEffect(v TriggerCustomEffectBlock1CustomEffect) {
	o.CustomEffect = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *TriggerCustomEffectBlock) GetParams() map[string]interface{} {
	if o == nil || IsNil(o.Params) {
		var ret map[string]interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerCustomEffectBlock) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *TriggerCustomEffectBlock) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]interface{} and assigns it to the Params field.
func (o *TriggerCustomEffectBlock) SetParams(v map[string]interface{}) {
	o.Params = v
}

// GetTarget returns the Target field value
func (o *TriggerCustomEffectBlock) GetTarget() TriggerCustomEffectBlock1Target {
	if o == nil {
		var ret TriggerCustomEffectBlock1Target
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *TriggerCustomEffectBlock) GetTargetOk() (*TriggerCustomEffectBlock1Target, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *TriggerCustomEffectBlock) SetTarget(v TriggerCustomEffectBlock1Target) {
	o.Target = v
}

// GetOnError returns the OnError field value if set, zero value otherwise.
func (o *TriggerCustomEffectBlock) GetOnError() map[string][]Block {
	if o == nil || IsNil(o.OnError) {
		var ret map[string][]Block
		return ret
	}
	return o.OnError
}

// GetOnErrorOk returns a tuple with the OnError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerCustomEffectBlock) GetOnErrorOk() (map[string][]Block, bool) {
	if o == nil || IsNil(o.OnError) {
		return map[string][]Block{}, false
	}
	return o.OnError, true
}

// HasOnError returns a boolean if a field has been set.
func (o *TriggerCustomEffectBlock) HasOnError() bool {
	if o != nil && !IsNil(o.OnError) {
		return true
	}

	return false
}

// SetOnError gets a reference to the given map[string][]Block and assigns it to the OnError field.
func (o *TriggerCustomEffectBlock) SetOnError(v map[string][]Block) {
	o.OnError = v
}

func (o TriggerCustomEffectBlock) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerCustomEffectBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["customEffect"] = o.CustomEffect
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	toSerialize["target"] = o.Target
	if !IsNil(o.OnError) {
		toSerialize["onError"] = o.OnError
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TriggerCustomEffectBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"customEffect",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTriggerCustomEffectBlock := _TriggerCustomEffectBlock{}

	err = json.Unmarshal(data, &varTriggerCustomEffectBlock)

	if err != nil {
		return err
	}

	*o = TriggerCustomEffectBlock(varTriggerCustomEffectBlock)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "customEffect")
		delete(additionalProperties, "params")
		delete(additionalProperties, "target")
		delete(additionalProperties, "onError")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTriggerCustomEffectBlock struct {
	value *TriggerCustomEffectBlock
	isSet bool
}

func (v NullableTriggerCustomEffectBlock) Get() *TriggerCustomEffectBlock {
	return v.value
}

func (v *NullableTriggerCustomEffectBlock) Set(val *TriggerCustomEffectBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerCustomEffectBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerCustomEffectBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableTriggerCustomEffectBlock(val *TriggerCustomEffectBlock) *NullableTriggerCustomEffectBlock {
	return &NullableTriggerCustomEffectBlock{value: val, isSet: true}
}

func (v NullableTriggerCustomEffectBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerCustomEffectBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
