/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SamlConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SamlConnection{}

// SamlConnection struct for SamlConnection
type SamlConnection struct {
	// The ID of the account that owns this entity.
	AccountId int64 `json:"accountId"`
	// ID of the SAML service.
	Name string `json:"name"`
	// Determines if this SAML connection active.
	Enabled bool `json:"enabled"`
	// Identity Provider Entity ID.
	Issuer string `json:"issuer"`
	// Single Sign-On URL.
	SignOnURL string `json:"signOnURL"`
	// Single Sign-Out URL.
	SignOutURL *string `json:"signOutURL,omitempty"`
	// Metadata URL.
	MetadataURL *string `json:"metadataURL,omitempty"`
	// The application-defined unique identifier that is the intended audience of the SAML assertion. This is most often the SP Entity ID of your application. When not specified, the ACS URL will be used.
	AudienceURI string `json:"audienceURI"`
	// The internal ID of this entity.
	Id int64 `json:"id"`
	// The time this entity was created.
	Created time.Time `json:"created"`
	// The location where the SAML assertion is sent with a HTTP POST.
	AssertionConsumerServiceURL string `json:"assertionConsumerServiceURL"`
}

type _SamlConnection SamlConnection

// NewSamlConnection instantiates a new SamlConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildSamlConnection(accountId int64, name string, enabled bool, issuer string, signOnURL string, audienceURI string, id int64, created time.Time, assertionConsumerServiceURL string) *SamlConnection {
	this := SamlConnection{}
	this.AccountId = accountId
	this.Name = name
	this.Enabled = enabled
	this.Issuer = issuer
	this.SignOnURL = signOnURL
	this.AudienceURI = audienceURI
	this.Id = id
	this.Created = created
	this.AssertionConsumerServiceURL = assertionConsumerServiceURL
	return &this
}

// NewSamlConnectionWithDefaults instantiates a new SamlConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSamlConnectionWithDefaults() *SamlConnection {
	this := SamlConnection{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *SamlConnection) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *SamlConnection) SetAccountId(v int64) {
	o.AccountId = v
}

// GetName returns the Name field value
func (o *SamlConnection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SamlConnection) SetName(v string) {
	o.Name = v
}

// GetEnabled returns the Enabled field value
func (o *SamlConnection) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *SamlConnection) SetEnabled(v bool) {
	o.Enabled = v
}

// GetIssuer returns the Issuer field value
func (o *SamlConnection) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *SamlConnection) SetIssuer(v string) {
	o.Issuer = v
}

// GetSignOnURL returns the SignOnURL field value
func (o *SamlConnection) GetSignOnURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignOnURL
}

// GetSignOnURLOk returns a tuple with the SignOnURL field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetSignOnURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignOnURL, true
}

// SetSignOnURL sets field value
func (o *SamlConnection) SetSignOnURL(v string) {
	o.SignOnURL = v
}

// GetSignOutURL returns the SignOutURL field value if set, zero value otherwise.
func (o *SamlConnection) GetSignOutURL() string {
	if o == nil || IsNil(o.SignOutURL) {
		var ret string
		return ret
	}
	return *o.SignOutURL
}

// GetSignOutURLOk returns a tuple with the SignOutURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetSignOutURLOk() (*string, bool) {
	if o == nil || IsNil(o.SignOutURL) {
		return nil, false
	}
	return o.SignOutURL, true
}

// HasSignOutURL returns a boolean if a field has been set.
func (o *SamlConnection) HasSignOutURL() bool {
	if o != nil && !IsNil(o.SignOutURL) {
		return true
	}

	return false
}

// SetSignOutURL gets a reference to the given string and assigns it to the SignOutURL field.
func (o *SamlConnection) SetSignOutURL(v string) {
	o.SignOutURL = &v
}

// GetMetadataURL returns the MetadataURL field value if set, zero value otherwise.
func (o *SamlConnection) GetMetadataURL() string {
	if o == nil || IsNil(o.MetadataURL) {
		var ret string
		return ret
	}
	return *o.MetadataURL
}

// GetMetadataURLOk returns a tuple with the MetadataURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetMetadataURLOk() (*string, bool) {
	if o == nil || IsNil(o.MetadataURL) {
		return nil, false
	}
	return o.MetadataURL, true
}

// HasMetadataURL returns a boolean if a field has been set.
func (o *SamlConnection) HasMetadataURL() bool {
	if o != nil && !IsNil(o.MetadataURL) {
		return true
	}

	return false
}

// SetMetadataURL gets a reference to the given string and assigns it to the MetadataURL field.
func (o *SamlConnection) SetMetadataURL(v string) {
	o.MetadataURL = &v
}

// GetAudienceURI returns the AudienceURI field value
func (o *SamlConnection) GetAudienceURI() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AudienceURI
}

// GetAudienceURIOk returns a tuple with the AudienceURI field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetAudienceURIOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudienceURI, true
}

// SetAudienceURI sets field value
func (o *SamlConnection) SetAudienceURI(v string) {
	o.AudienceURI = v
}

// GetId returns the Id field value
func (o *SamlConnection) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SamlConnection) SetId(v int64) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *SamlConnection) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *SamlConnection) SetCreated(v time.Time) {
	o.Created = v
}

// GetAssertionConsumerServiceURL returns the AssertionConsumerServiceURL field value
func (o *SamlConnection) GetAssertionConsumerServiceURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssertionConsumerServiceURL
}

// GetAssertionConsumerServiceURLOk returns a tuple with the AssertionConsumerServiceURL field value
// and a boolean to check if the value has been set.
func (o *SamlConnection) GetAssertionConsumerServiceURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssertionConsumerServiceURL, true
}

// SetAssertionConsumerServiceURL sets field value
func (o *SamlConnection) SetAssertionConsumerServiceURL(v string) {
	o.AssertionConsumerServiceURL = v
}

func (o SamlConnection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SamlConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["name"] = o.Name
	toSerialize["enabled"] = o.Enabled
	toSerialize["issuer"] = o.Issuer
	toSerialize["signOnURL"] = o.SignOnURL
	if !IsNil(o.SignOutURL) {
		toSerialize["signOutURL"] = o.SignOutURL
	}
	if !IsNil(o.MetadataURL) {
		toSerialize["metadataURL"] = o.MetadataURL
	}
	toSerialize["audienceURI"] = o.AudienceURI
	toSerialize["id"] = o.Id
	toSerialize["created"] = o.Created
	toSerialize["assertionConsumerServiceURL"] = o.AssertionConsumerServiceURL
	return toSerialize, nil
}

func (o *SamlConnection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"name",
		"enabled",
		"issuer",
		"signOnURL",
		"audienceURI",
		"id",
		"created",
		"assertionConsumerServiceURL",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSamlConnection := _SamlConnection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSamlConnection)

	if err != nil {
		return err
	}

	*o = SamlConnection(varSamlConnection)

	return err
}

type NullableSamlConnection struct {
	value *SamlConnection
	isSet bool
}

func (v NullableSamlConnection) Get() *SamlConnection {
	return v.value
}

func (v *NullableSamlConnection) Set(val *SamlConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableSamlConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableSamlConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableSamlConnection(val *SamlConnection) *NullableSamlConnection {
	return &NullableSamlConnection{value: val, isSet: true}
}

func (v NullableSamlConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSamlConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
