/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the CampaignEligibilityDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignEligibilityDetails{}

// CampaignEligibilityDetails struct for CampaignEligibilityDetails
type CampaignEligibilityDetails struct {
	// Indicates whether the customer was eligible for the campaign in the current session.
	Passed bool `json:"passed"`
	// The coupon code used to check a customer's eligibility for the campaign in the current session, if applicable.
	CouponCode *string `json:"couponCode,omitempty"`
	// The details about why the customer was not eligible for the campaign in the current session. Only returned when `passed` is `false`.
	Details              *CampaignEligibilityFailureDetails `json:"details,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CampaignEligibilityDetails CampaignEligibilityDetails

// NewCampaignEligibilityDetails instantiates a new CampaignEligibilityDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCampaignEligibilityDetails(passed bool) *CampaignEligibilityDetails {
	this := CampaignEligibilityDetails{}
	this.Passed = passed
	return &this
}

// NewCampaignEligibilityDetailsWithDefaults instantiates a new CampaignEligibilityDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignEligibilityDetailsWithDefaults() *CampaignEligibilityDetails {
	this := CampaignEligibilityDetails{}
	return &this
}

// GetPassed returns the Passed field value
func (o *CampaignEligibilityDetails) GetPassed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Passed
}

// GetPassedOk returns a tuple with the Passed field value
// and a boolean to check if the value has been set.
func (o *CampaignEligibilityDetails) GetPassedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passed, true
}

// SetPassed sets field value
func (o *CampaignEligibilityDetails) SetPassed(v bool) {
	o.Passed = v
}

// GetCouponCode returns the CouponCode field value if set, zero value otherwise.
func (o *CampaignEligibilityDetails) GetCouponCode() string {
	if o == nil || IsNil(o.CouponCode) {
		var ret string
		return ret
	}
	return *o.CouponCode
}

// GetCouponCodeOk returns a tuple with the CouponCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignEligibilityDetails) GetCouponCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CouponCode) {
		return nil, false
	}
	return o.CouponCode, true
}

// HasCouponCode returns a boolean if a field has been set.
func (o *CampaignEligibilityDetails) HasCouponCode() bool {
	if o != nil && !IsNil(o.CouponCode) {
		return true
	}

	return false
}

// SetCouponCode gets a reference to the given string and assigns it to the CouponCode field.
func (o *CampaignEligibilityDetails) SetCouponCode(v string) {
	o.CouponCode = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *CampaignEligibilityDetails) GetDetails() CampaignEligibilityFailureDetails {
	if o == nil || IsNil(o.Details) {
		var ret CampaignEligibilityFailureDetails
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignEligibilityDetails) GetDetailsOk() (*CampaignEligibilityFailureDetails, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *CampaignEligibilityDetails) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given CampaignEligibilityFailureDetails and assigns it to the Details field.
func (o *CampaignEligibilityDetails) SetDetails(v CampaignEligibilityFailureDetails) {
	o.Details = &v
}

func (o CampaignEligibilityDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignEligibilityDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passed"] = o.Passed
	if !IsNil(o.CouponCode) {
		toSerialize["couponCode"] = o.CouponCode
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CampaignEligibilityDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaignEligibilityDetails := _CampaignEligibilityDetails{}

	err = json.Unmarshal(data, &varCampaignEligibilityDetails)

	if err != nil {
		return err
	}

	*o = CampaignEligibilityDetails(varCampaignEligibilityDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "passed")
		delete(additionalProperties, "couponCode")
		delete(additionalProperties, "details")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCampaignEligibilityDetails struct {
	value *CampaignEligibilityDetails
	isSet bool
}

func (v NullableCampaignEligibilityDetails) Get() *CampaignEligibilityDetails {
	return v.value
}

func (v *NullableCampaignEligibilityDetails) Set(val *CampaignEligibilityDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignEligibilityDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignEligibilityDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCampaignEligibilityDetails(val *CampaignEligibilityDetails) *NullableCampaignEligibilityDetails {
	return &NullableCampaignEligibilityDetails{value: val, isSet: true}
}

func (v NullableCampaignEligibilityDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignEligibilityDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
