/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CouponDeletedEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CouponDeletedEventRequest{}

// CouponDeletedEventRequest struct for CouponDeletedEventRequest
type CouponDeletedEventRequest struct {
	TotalResultSize int64 `json:"TotalResultSize"`
	// Timestamp when the batch was created.
	BatchedAt *time.Time    `json:"BatchedAt,omitempty"`
	EventType string        `json:"EventType"`
	Data      []interface{} `json:"Data"`
}

type _CouponDeletedEventRequest CouponDeletedEventRequest

// NewCouponDeletedEventRequest instantiates a new CouponDeletedEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildCouponDeletedEventRequest(totalResultSize int64, eventType string, data []interface{}) *CouponDeletedEventRequest {
	this := CouponDeletedEventRequest{}
	this.TotalResultSize = totalResultSize
	this.EventType = eventType
	this.Data = data
	return &this
}

// NewCouponDeletedEventRequestWithDefaults instantiates a new CouponDeletedEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCouponDeletedEventRequestWithDefaults() *CouponDeletedEventRequest {
	this := CouponDeletedEventRequest{}
	return &this
}

// GetTotalResultSize returns the TotalResultSize field value
func (o *CouponDeletedEventRequest) GetTotalResultSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalResultSize
}

// GetTotalResultSizeOk returns a tuple with the TotalResultSize field value
// and a boolean to check if the value has been set.
func (o *CouponDeletedEventRequest) GetTotalResultSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalResultSize, true
}

// SetTotalResultSize sets field value
func (o *CouponDeletedEventRequest) SetTotalResultSize(v int64) {
	o.TotalResultSize = v
}

// GetBatchedAt returns the BatchedAt field value if set, zero value otherwise.
func (o *CouponDeletedEventRequest) GetBatchedAt() time.Time {
	if o == nil || IsNil(o.BatchedAt) {
		var ret time.Time
		return ret
	}
	return *o.BatchedAt
}

// GetBatchedAtOk returns a tuple with the BatchedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponDeletedEventRequest) GetBatchedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.BatchedAt) {
		return nil, false
	}
	return o.BatchedAt, true
}

// HasBatchedAt returns a boolean if a field has been set.
func (o *CouponDeletedEventRequest) HasBatchedAt() bool {
	if o != nil && !IsNil(o.BatchedAt) {
		return true
	}

	return false
}

// SetBatchedAt gets a reference to the given time.Time and assigns it to the BatchedAt field.
func (o *CouponDeletedEventRequest) SetBatchedAt(v time.Time) {
	o.BatchedAt = &v
}

// GetEventType returns the EventType field value
func (o *CouponDeletedEventRequest) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *CouponDeletedEventRequest) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *CouponDeletedEventRequest) SetEventType(v string) {
	o.EventType = v
}

// GetData returns the Data field value
func (o *CouponDeletedEventRequest) GetData() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CouponDeletedEventRequest) GetDataOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CouponDeletedEventRequest) SetData(v []interface{}) {
	o.Data = v
}

func (o CouponDeletedEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CouponDeletedEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["TotalResultSize"] = o.TotalResultSize
	if !IsNil(o.BatchedAt) {
		toSerialize["BatchedAt"] = o.BatchedAt
	}
	toSerialize["EventType"] = o.EventType
	toSerialize["Data"] = o.Data
	return toSerialize, nil
}

func (o *CouponDeletedEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TotalResultSize",
		"EventType",
		"Data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCouponDeletedEventRequest := _CouponDeletedEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCouponDeletedEventRequest)

	if err != nil {
		return err
	}

	*o = CouponDeletedEventRequest(varCouponDeletedEventRequest)

	return err
}

type NullableCouponDeletedEventRequest struct {
	value *CouponDeletedEventRequest
	isSet bool
}

func (v NullableCouponDeletedEventRequest) Get() *CouponDeletedEventRequest {
	return v.value
}

func (v *NullableCouponDeletedEventRequest) Set(val *CouponDeletedEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCouponDeletedEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCouponDeletedEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableCouponDeletedEventRequest(val *CouponDeletedEventRequest) *NullableCouponDeletedEventRequest {
	return &NullableCouponDeletedEventRequest{value: val, isSet: true}
}

func (v NullableCouponDeletedEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCouponDeletedEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
