/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewSamlConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewSamlConnection{}

// NewSamlConnection struct for NewSamlConnection
type NewSamlConnection struct {
	// The ID of the account that owns this entity.
	AccountId int64 `json:"accountId"`
	// ID of the SAML service.
	Name string `json:"name"`
	// Determines if this SAML connection active.
	Enabled bool `json:"enabled"`
	// Identity Provider Entity ID.
	Issuer string `json:"issuer"`
	// Single Sign-On URL.
	SignOnURL string `json:"signOnURL"`
	// Single Sign-Out URL.
	SignOutURL *string `json:"signOutURL,omitempty"`
	// Metadata URL.
	MetadataURL *string `json:"metadataURL,omitempty"`
	// The application-defined unique identifier that is the intended audience of the SAML assertion. This is most often the SP Entity ID of your application. When not specified, the ACS URL will be used. 
	AudienceURI *string `json:"audienceURI,omitempty"`
	// X.509 Certificate.
	X509certificate string `json:"x509certificate"`
}

type _NewSamlConnection NewSamlConnection

// NewNewSamlConnection instantiates a new NewSamlConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewSamlConnection(accountId int64, name string, enabled bool, issuer string, signOnURL string, x509certificate string) *NewSamlConnection {
	this := NewSamlConnection{}
	this.AccountId = accountId
	this.Name = name
	this.Enabled = enabled
	this.Issuer = issuer
	this.SignOnURL = signOnURL
	this.X509certificate = x509certificate
	return &this
}

// NewNewSamlConnectionWithDefaults instantiates a new NewSamlConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewSamlConnectionWithDefaults() *NewSamlConnection {
	this := NewSamlConnection{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *NewSamlConnection) GetAccountId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetAccountIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *NewSamlConnection) SetAccountId(v int64) {
	o.AccountId = v
}

// GetName returns the Name field value
func (o *NewSamlConnection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewSamlConnection) SetName(v string) {
	o.Name = v
}

// GetEnabled returns the Enabled field value
func (o *NewSamlConnection) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *NewSamlConnection) SetEnabled(v bool) {
	o.Enabled = v
}

// GetIssuer returns the Issuer field value
func (o *NewSamlConnection) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *NewSamlConnection) SetIssuer(v string) {
	o.Issuer = v
}

// GetSignOnURL returns the SignOnURL field value
func (o *NewSamlConnection) GetSignOnURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignOnURL
}

// GetSignOnURLOk returns a tuple with the SignOnURL field value
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetSignOnURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignOnURL, true
}

// SetSignOnURL sets field value
func (o *NewSamlConnection) SetSignOnURL(v string) {
	o.SignOnURL = v
}

// GetSignOutURL returns the SignOutURL field value if set, zero value otherwise.
func (o *NewSamlConnection) GetSignOutURL() string {
	if o == nil || IsNil(o.SignOutURL) {
		var ret string
		return ret
	}
	return *o.SignOutURL
}

// GetSignOutURLOk returns a tuple with the SignOutURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetSignOutURLOk() (*string, bool) {
	if o == nil || IsNil(o.SignOutURL) {
		return nil, false
	}
	return o.SignOutURL, true
}

// HasSignOutURL returns a boolean if a field has been set.
func (o *NewSamlConnection) HasSignOutURL() bool {
	if o != nil && !IsNil(o.SignOutURL) {
		return true
	}

	return false
}

// SetSignOutURL gets a reference to the given string and assigns it to the SignOutURL field.
func (o *NewSamlConnection) SetSignOutURL(v string) {
	o.SignOutURL = &v
}

// GetMetadataURL returns the MetadataURL field value if set, zero value otherwise.
func (o *NewSamlConnection) GetMetadataURL() string {
	if o == nil || IsNil(o.MetadataURL) {
		var ret string
		return ret
	}
	return *o.MetadataURL
}

// GetMetadataURLOk returns a tuple with the MetadataURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetMetadataURLOk() (*string, bool) {
	if o == nil || IsNil(o.MetadataURL) {
		return nil, false
	}
	return o.MetadataURL, true
}

// HasMetadataURL returns a boolean if a field has been set.
func (o *NewSamlConnection) HasMetadataURL() bool {
	if o != nil && !IsNil(o.MetadataURL) {
		return true
	}

	return false
}

// SetMetadataURL gets a reference to the given string and assigns it to the MetadataURL field.
func (o *NewSamlConnection) SetMetadataURL(v string) {
	o.MetadataURL = &v
}

// GetAudienceURI returns the AudienceURI field value if set, zero value otherwise.
func (o *NewSamlConnection) GetAudienceURI() string {
	if o == nil || IsNil(o.AudienceURI) {
		var ret string
		return ret
	}
	return *o.AudienceURI
}

// GetAudienceURIOk returns a tuple with the AudienceURI field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetAudienceURIOk() (*string, bool) {
	if o == nil || IsNil(o.AudienceURI) {
		return nil, false
	}
	return o.AudienceURI, true
}

// HasAudienceURI returns a boolean if a field has been set.
func (o *NewSamlConnection) HasAudienceURI() bool {
	if o != nil && !IsNil(o.AudienceURI) {
		return true
	}

	return false
}

// SetAudienceURI gets a reference to the given string and assigns it to the AudienceURI field.
func (o *NewSamlConnection) SetAudienceURI(v string) {
	o.AudienceURI = &v
}

// GetX509certificate returns the X509certificate field value
func (o *NewSamlConnection) GetX509certificate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.X509certificate
}

// GetX509certificateOk returns a tuple with the X509certificate field value
// and a boolean to check if the value has been set.
func (o *NewSamlConnection) GetX509certificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X509certificate, true
}

// SetX509certificate sets field value
func (o *NewSamlConnection) SetX509certificate(v string) {
	o.X509certificate = v
}

func (o NewSamlConnection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewSamlConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["name"] = o.Name
	toSerialize["enabled"] = o.Enabled
	toSerialize["issuer"] = o.Issuer
	toSerialize["signOnURL"] = o.SignOnURL
	if !IsNil(o.SignOutURL) {
		toSerialize["signOutURL"] = o.SignOutURL
	}
	if !IsNil(o.MetadataURL) {
		toSerialize["metadataURL"] = o.MetadataURL
	}
	if !IsNil(o.AudienceURI) {
		toSerialize["audienceURI"] = o.AudienceURI
	}
	toSerialize["x509certificate"] = o.X509certificate
	return toSerialize, nil
}

func (o *NewSamlConnection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"name",
		"enabled",
		"issuer",
		"signOnURL",
		"x509certificate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewSamlConnection := _NewSamlConnection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewSamlConnection)

	if err != nil {
		return err
	}

	*o = NewSamlConnection(varNewSamlConnection)

	return err
}

type NullableNewSamlConnection struct {
	value *NewSamlConnection
	isSet bool
}

func (v NullableNewSamlConnection) Get() *NewSamlConnection {
	return v.value
}

func (v *NullableNewSamlConnection) Set(val *NewSamlConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableNewSamlConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableNewSamlConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewSamlConnection(val *NewSamlConnection) *NullableNewSamlConnection {
	return &NullableNewSamlConnection{value: val, isSet: true}
}

func (v NullableNewSamlConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewSamlConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


