/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NewBaseNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewBaseNotification{}

// NewBaseNotification struct for NewBaseNotification
type NewBaseNotification struct {
	// Indicates which notification properties to apply.
	Policy map[string]interface{} `json:"policy"`
	// Indicates whether the notification is activated.
	Enabled *bool                  `json:"enabled,omitempty"`
	Webhook NewNotificationWebhook `json:"webhook"`
}

type _NewBaseNotification NewBaseNotification

// NewNewBaseNotification instantiates a new NewBaseNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildNewBaseNotification(policy map[string]interface{}, webhook NewNotificationWebhook) *NewBaseNotification {
	this := NewBaseNotification{}
	this.Policy = policy
	var enabled bool = true
	this.Enabled = &enabled
	this.Webhook = webhook
	return &this
}

// NewNewBaseNotificationWithDefaults instantiates a new NewBaseNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewBaseNotificationWithDefaults() *NewBaseNotification {
	this := NewBaseNotification{}
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// GetPolicy returns the Policy field value
func (o *NewBaseNotification) GetPolicy() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *NewBaseNotification) GetPolicyOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Policy, true
}

// SetPolicy sets field value
func (o *NewBaseNotification) SetPolicy(v map[string]interface{}) {
	o.Policy = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *NewBaseNotification) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewBaseNotification) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *NewBaseNotification) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *NewBaseNotification) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetWebhook returns the Webhook field value
func (o *NewBaseNotification) GetWebhook() NewNotificationWebhook {
	if o == nil {
		var ret NewNotificationWebhook
		return ret
	}

	return o.Webhook
}

// GetWebhookOk returns a tuple with the Webhook field value
// and a boolean to check if the value has been set.
func (o *NewBaseNotification) GetWebhookOk() (*NewNotificationWebhook, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Webhook, true
}

// SetWebhook sets field value
func (o *NewBaseNotification) SetWebhook(v NewNotificationWebhook) {
	o.Webhook = v
}

func (o NewBaseNotification) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewBaseNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	toSerialize["webhook"] = o.Webhook
	return toSerialize, nil
}

func (o *NewBaseNotification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy",
		"webhook",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewBaseNotification := _NewBaseNotification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewBaseNotification)

	if err != nil {
		return err
	}

	*o = NewBaseNotification(varNewBaseNotification)

	return err
}

type NullableNewBaseNotification struct {
	value *NewBaseNotification
	isSet bool
}

func (v NullableNewBaseNotification) Get() *NewBaseNotification {
	return v.value
}

func (v *NullableNewBaseNotification) Set(val *NewBaseNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableNewBaseNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableNewBaseNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableNewBaseNotification(val *NewBaseNotification) *NullableNewBaseNotification {
	return &NullableNewBaseNotification{value: val, isSet: true}
}

func (v NullableNewBaseNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewBaseNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
