/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateApplicationAPIKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApplicationAPIKey{}

// CreateApplicationAPIKey struct for CreateApplicationAPIKey
type CreateApplicationAPIKey struct {
	// Title of the API key.
	Title string `json:"title"`
	// The date the API key expires.
	Expires time.Time `json:"expires"`
	// The third-party platform the API key is valid for. Use `none` for a generic API key to be used from your own integration layer. 
	Platform *string `json:"platform,omitempty"`
	// The API key type. Can be empty or `staging`.  Staging API keys can only be used for dry requests with the [Update customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint, [Update customer profile](https://docs.talon.one/integration-api#tag/Customer-profiles/operation/updateCustomerProfileV2) endpoint, and [Track event](https://docs.talon.one/integration-api#tag/Events/operation/trackEventV2) endpoint.  When using the _Update customer profile_ endpoint with a staging API key, the query parameter `runRuleEngine` must be `true`. 
	Type *string `json:"type,omitempty"`
	// A time offset in nanoseconds associated with the API key. When making a request using the API key, rule evaluation is based on a date that is calculated by adding the offset to the current date. 
	TimeOffset *int64 `json:"timeOffset,omitempty"`
}

type _CreateApplicationAPIKey CreateApplicationAPIKey

// NewCreateApplicationAPIKey instantiates a new CreateApplicationAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApplicationAPIKey(title string, expires time.Time) *CreateApplicationAPIKey {
	this := CreateApplicationAPIKey{}
	this.Title = title
	this.Expires = expires
	return &this
}

// NewCreateApplicationAPIKeyWithDefaults instantiates a new CreateApplicationAPIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApplicationAPIKeyWithDefaults() *CreateApplicationAPIKey {
	this := CreateApplicationAPIKey{}
	return &this
}

// GetTitle returns the Title field value
func (o *CreateApplicationAPIKey) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationAPIKey) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreateApplicationAPIKey) SetTitle(v string) {
	o.Title = v
}

// GetExpires returns the Expires field value
func (o *CreateApplicationAPIKey) GetExpires() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value
// and a boolean to check if the value has been set.
func (o *CreateApplicationAPIKey) GetExpiresOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expires, true
}

// SetExpires sets field value
func (o *CreateApplicationAPIKey) SetExpires(v time.Time) {
	o.Expires = v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *CreateApplicationAPIKey) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationAPIKey) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *CreateApplicationAPIKey) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *CreateApplicationAPIKey) SetPlatform(v string) {
	o.Platform = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateApplicationAPIKey) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationAPIKey) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateApplicationAPIKey) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateApplicationAPIKey) SetType(v string) {
	o.Type = &v
}

// GetTimeOffset returns the TimeOffset field value if set, zero value otherwise.
func (o *CreateApplicationAPIKey) GetTimeOffset() int64 {
	if o == nil || IsNil(o.TimeOffset) {
		var ret int64
		return ret
	}
	return *o.TimeOffset
}

// GetTimeOffsetOk returns a tuple with the TimeOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApplicationAPIKey) GetTimeOffsetOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeOffset) {
		return nil, false
	}
	return o.TimeOffset, true
}

// HasTimeOffset returns a boolean if a field has been set.
func (o *CreateApplicationAPIKey) HasTimeOffset() bool {
	if o != nil && !IsNil(o.TimeOffset) {
		return true
	}

	return false
}

// SetTimeOffset gets a reference to the given int64 and assigns it to the TimeOffset field.
func (o *CreateApplicationAPIKey) SetTimeOffset(v int64) {
	o.TimeOffset = &v
}

func (o CreateApplicationAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApplicationAPIKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["expires"] = o.Expires
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.TimeOffset) {
		toSerialize["timeOffset"] = o.TimeOffset
	}
	return toSerialize, nil
}

func (o *CreateApplicationAPIKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"expires",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApplicationAPIKey := _CreateApplicationAPIKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApplicationAPIKey)

	if err != nil {
		return err
	}

	*o = CreateApplicationAPIKey(varCreateApplicationAPIKey)

	return err
}

type NullableCreateApplicationAPIKey struct {
	value *CreateApplicationAPIKey
	isSet bool
}

func (v NullableCreateApplicationAPIKey) Get() *CreateApplicationAPIKey {
	return v.value
}

func (v *NullableCreateApplicationAPIKey) Set(val *CreateApplicationAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApplicationAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApplicationAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApplicationAPIKey(val *CreateApplicationAPIKey) *NullableCreateApplicationAPIKey {
	return &NullableCreateApplicationAPIKey{value: val, isSet: true}
}

func (v NullableCreateApplicationAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApplicationAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


