/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoyaltyLedger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoyaltyLedger{}

// LoyaltyLedger Ledger of Balance in Loyalty Program for a Customer.
type LoyaltyLedger struct {
	// The balance of the main ledger in the loyalty program.
	Ledger LoyaltySubLedger `json:"ledger"`
	// A map containing a list of all loyalty subledger balances.
	SubLedgers map[string]LoyaltySubLedger `json:"subLedgers,omitempty"`
}

type _LoyaltyLedger LoyaltyLedger

// NewLoyaltyLedger instantiates a new LoyaltyLedger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoyaltyLedger(ledger LoyaltySubLedger) *LoyaltyLedger {
	this := LoyaltyLedger{}
	this.Ledger = ledger
	return &this
}

// NewLoyaltyLedgerWithDefaults instantiates a new LoyaltyLedger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoyaltyLedgerWithDefaults() *LoyaltyLedger {
	this := LoyaltyLedger{}
	return &this
}

// GetLedger returns the Ledger field value
func (o *LoyaltyLedger) GetLedger() LoyaltySubLedger {
	if o == nil {
		var ret LoyaltySubLedger
		return ret
	}

	return o.Ledger
}

// GetLedgerOk returns a tuple with the Ledger field value
// and a boolean to check if the value has been set.
func (o *LoyaltyLedger) GetLedgerOk() (*LoyaltySubLedger, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ledger, true
}

// SetLedger sets field value
func (o *LoyaltyLedger) SetLedger(v LoyaltySubLedger) {
	o.Ledger = v
}

// GetSubLedgers returns the SubLedgers field value if set, zero value otherwise.
func (o *LoyaltyLedger) GetSubLedgers() map[string]LoyaltySubLedger {
	if o == nil || IsNil(o.SubLedgers) {
		var ret map[string]LoyaltySubLedger
		return ret
	}
	return o.SubLedgers
}

// GetSubLedgersOk returns a tuple with the SubLedgers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoyaltyLedger) GetSubLedgersOk() (map[string]LoyaltySubLedger, bool) {
	if o == nil || IsNil(o.SubLedgers) {
		return map[string]LoyaltySubLedger{}, false
	}
	return o.SubLedgers, true
}

// HasSubLedgers returns a boolean if a field has been set.
func (o *LoyaltyLedger) HasSubLedgers() bool {
	if o != nil && !IsNil(o.SubLedgers) {
		return true
	}

	return false
}

// SetSubLedgers gets a reference to the given map[string]LoyaltySubLedger and assigns it to the SubLedgers field.
func (o *LoyaltyLedger) SetSubLedgers(v map[string]LoyaltySubLedger) {
	o.SubLedgers = v
}

func (o LoyaltyLedger) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoyaltyLedger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ledger"] = o.Ledger
	if !IsNil(o.SubLedgers) {
		toSerialize["subLedgers"] = o.SubLedgers
	}
	return toSerialize, nil
}

func (o *LoyaltyLedger) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ledger",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoyaltyLedger := _LoyaltyLedger{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoyaltyLedger)

	if err != nil {
		return err
	}

	*o = LoyaltyLedger(varLoyaltyLedger)

	return err
}

type NullableLoyaltyLedger struct {
	value *LoyaltyLedger
	isSet bool
}

func (v NullableLoyaltyLedger) Get() *LoyaltyLedger {
	return v.value
}

func (v *NullableLoyaltyLedger) Set(val *LoyaltyLedger) {
	v.value = val
	v.isSet = true
}

func (v NullableLoyaltyLedger) IsSet() bool {
	return v.isSet
}

func (v *NullableLoyaltyLedger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoyaltyLedger(val *LoyaltyLedger) *NullableLoyaltyLedger {
	return &NullableLoyaltyLedger{value: val, isSet: true}
}

func (v NullableLoyaltyLedger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoyaltyLedger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


