/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the DigitalPass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DigitalPass{}

// DigitalPass struct for DigitalPass
type DigitalPass struct {
	// The ID of the generated digital pass.
	PassId string `json:"passId"`
	// The ID of the digital pass template used to generate the pass.
	PassTemplateId string `json:"passTemplateId"`
	// The status of the digital pass.
	Status string `json:"status"`
	// The URL you can use to let the customer add the digital pass to their wallet.
	PassUrl              string `json:"passUrl"`
	AdditionalProperties map[string]interface{}
}

type _DigitalPass DigitalPass

// NewDigitalPass instantiates a new DigitalPass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildDigitalPass(passId string, passTemplateId string, status string, passUrl string) *DigitalPass {
	this := DigitalPass{}
	this.PassId = passId
	this.PassTemplateId = passTemplateId
	this.Status = status
	this.PassUrl = passUrl
	return &this
}

// NewDigitalPassWithDefaults instantiates a new DigitalPass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDigitalPassWithDefaults() *DigitalPass {
	this := DigitalPass{}
	return &this
}

// GetPassId returns the PassId field value
func (o *DigitalPass) GetPassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PassId
}

// GetPassIdOk returns a tuple with the PassId field value
// and a boolean to check if the value has been set.
func (o *DigitalPass) GetPassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PassId, true
}

// SetPassId sets field value
func (o *DigitalPass) SetPassId(v string) {
	o.PassId = v
}

// GetPassTemplateId returns the PassTemplateId field value
func (o *DigitalPass) GetPassTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PassTemplateId
}

// GetPassTemplateIdOk returns a tuple with the PassTemplateId field value
// and a boolean to check if the value has been set.
func (o *DigitalPass) GetPassTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PassTemplateId, true
}

// SetPassTemplateId sets field value
func (o *DigitalPass) SetPassTemplateId(v string) {
	o.PassTemplateId = v
}

// GetStatus returns the Status field value
func (o *DigitalPass) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DigitalPass) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DigitalPass) SetStatus(v string) {
	o.Status = v
}

// GetPassUrl returns the PassUrl field value
func (o *DigitalPass) GetPassUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PassUrl
}

// GetPassUrlOk returns a tuple with the PassUrl field value
// and a boolean to check if the value has been set.
func (o *DigitalPass) GetPassUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PassUrl, true
}

// SetPassUrl sets field value
func (o *DigitalPass) SetPassUrl(v string) {
	o.PassUrl = v
}

func (o DigitalPass) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DigitalPass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passId"] = o.PassId
	toSerialize["passTemplateId"] = o.PassTemplateId
	toSerialize["status"] = o.Status
	toSerialize["passUrl"] = o.PassUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DigitalPass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passId",
		"passTemplateId",
		"status",
		"passUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDigitalPass := _DigitalPass{}

	err = json.Unmarshal(data, &varDigitalPass)

	if err != nil {
		return err
	}

	*o = DigitalPass(varDigitalPass)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "passId")
		delete(additionalProperties, "passTemplateId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "passUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDigitalPass struct {
	value *DigitalPass
	isSet bool
}

func (v NullableDigitalPass) Get() *DigitalPass {
	return v.value
}

func (v *NullableDigitalPass) Set(val *DigitalPass) {
	v.value = val
	v.isSet = true
}

func (v NullableDigitalPass) IsSet() bool {
	return v.isSet
}

func (v *NullableDigitalPass) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableDigitalPass(val *DigitalPass) *NullableDigitalPass {
	return &NullableDigitalPass{value: val, isSet: true}
}

func (v NullableDigitalPass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDigitalPass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
