/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
)

// checks if the ScimBaseUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimBaseUser{}

// ScimBaseUser Schema definition for base user fields, provisioned using the SCIM protocol and used by Talon.One.
type ScimBaseUser struct {
	// Status of the user.
	Active *bool `json:"active,omitempty"`
	// Display name of the user.
	DisplayName *string `json:"displayName,omitempty"`
	// Unique identifier of the user. This is usually an email address.
	UserName *string `json:"userName,omitempty"`
	Name *ScimBaseUserName `json:"name,omitempty"`
}

// NewScimBaseUser instantiates a new ScimBaseUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildScimBaseUser() *ScimBaseUser {
	this := ScimBaseUser{}
	return &this
}

// NewScimBaseUserWithDefaults instantiates a new ScimBaseUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimBaseUserWithDefaults() *ScimBaseUser {
	this := ScimBaseUser{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ScimBaseUser) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimBaseUser) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ScimBaseUser) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ScimBaseUser) SetActive(v bool) {
	o.Active = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ScimBaseUser) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimBaseUser) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ScimBaseUser) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ScimBaseUser) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *ScimBaseUser) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimBaseUser) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *ScimBaseUser) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *ScimBaseUser) SetUserName(v string) {
	o.UserName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScimBaseUser) GetName() ScimBaseUserName {
	if o == nil || IsNil(o.Name) {
		var ret ScimBaseUserName
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimBaseUser) GetNameOk() (*ScimBaseUserName, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScimBaseUser) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given ScimBaseUserName and assigns it to the Name field.
func (o *ScimBaseUser) SetName(v ScimBaseUserName) {
	o.Name = &v
}

func (o ScimBaseUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimBaseUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.UserName) {
		toSerialize["userName"] = o.UserName
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableScimBaseUser struct {
	value *ScimBaseUser
	isSet bool
}

func (v NullableScimBaseUser) Get() *ScimBaseUser {
	return v.value
}

func (v *NullableScimBaseUser) Set(val *ScimBaseUser) {
	v.value = val
	v.isSet = true
}

func (v NullableScimBaseUser) IsSet() bool {
	return v.isSet
}

func (v *NullableScimBaseUser) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableScimBaseUser(val *ScimBaseUser) *NullableScimBaseUser {
	return &NullableScimBaseUser{value: val, isSet: true}
}

func (v NullableScimBaseUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimBaseUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


