/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RiskDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskDetail{}

// RiskDetail Details of a risk, including its most severely affected entities.
type RiskDetail struct {
	// The internal ID of this entity.
	Id int64 `json:"id"`
	// The time this entity was created.
	Created time.Time `json:"created"`
	// The ID of the risk notification rule that flagged this risk.
	NotificationId int64 `json:"notificationId"`
	// The date of the ML pipeline run that detected this risk.
	RunDate string `json:"runDate"`
	// The Application group this risk was detected in. Contains the Application ID, or `__GLOBAL__` for metrics that are not grouped by Application.
	GroupKey string `json:"groupKey"`
	// The ID of the Application this risk belongs to. Absent for global metrics.
	ApplicationId *int64 `json:"applicationId,omitempty"`
	// The triage lifecycle status of this risk.
	Status string `json:"status"`
	// The critical classification bucket of this risk.
	Criticality string `json:"criticality"`
	// The entity type the risk was detected in.
	Entity string `json:"entity"`
	// The activity metric the risk was detected in.
	Activity string `json:"activity"`
	// The rolling time window of the risk evaluation.
	TimeFrame string `json:"timeFrame"`
	// The time the ML service reported this risk.
	ReportedDate time.Time `json:"reportedDate"`
	// The total number of entities affected by this risk.
	AffectedEntityCount int64 `json:"affectedEntityCount"`
	// Human-readable description of the detected anomaly.
	Description *string `json:"description,omitempty"`
	// Timestamp of the most recent update.
	Modified time.Time `json:"modified"`
	// The affected entities with the highest severity ratios, in descending order.
	AffectedEntities     []RiskAffectedEntityItem `json:"affectedEntities"`
	AdditionalProperties map[string]interface{}
}

type _RiskDetail RiskDetail

// NewRiskDetail instantiates a new RiskDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildRiskDetail(id int64, created time.Time, notificationId int64, runDate string, groupKey string, status string, criticality string, entity string, activity string, timeFrame string, reportedDate time.Time, affectedEntityCount int64, modified time.Time, affectedEntities []RiskAffectedEntityItem) *RiskDetail {
	this := RiskDetail{}
	this.Id = id
	this.Created = created
	this.NotificationId = notificationId
	this.RunDate = runDate
	this.GroupKey = groupKey
	this.Status = status
	this.Criticality = criticality
	this.Entity = entity
	this.Activity = activity
	this.TimeFrame = timeFrame
	this.ReportedDate = reportedDate
	this.AffectedEntityCount = affectedEntityCount
	this.Modified = modified
	this.AffectedEntities = affectedEntities
	return &this
}

// NewRiskDetailWithDefaults instantiates a new RiskDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskDetailWithDefaults() *RiskDetail {
	this := RiskDetail{}
	return &this
}

// GetId returns the Id field value
func (o *RiskDetail) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RiskDetail) SetId(v int64) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *RiskDetail) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *RiskDetail) SetCreated(v time.Time) {
	o.Created = v
}

// GetNotificationId returns the NotificationId field value
func (o *RiskDetail) GetNotificationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NotificationId
}

// GetNotificationIdOk returns a tuple with the NotificationId field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetNotificationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotificationId, true
}

// SetNotificationId sets field value
func (o *RiskDetail) SetNotificationId(v int64) {
	o.NotificationId = v
}

// GetRunDate returns the RunDate field value
func (o *RiskDetail) GetRunDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunDate
}

// GetRunDateOk returns a tuple with the RunDate field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetRunDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunDate, true
}

// SetRunDate sets field value
func (o *RiskDetail) SetRunDate(v string) {
	o.RunDate = v
}

// GetGroupKey returns the GroupKey field value
func (o *RiskDetail) GetGroupKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupKey
}

// GetGroupKeyOk returns a tuple with the GroupKey field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetGroupKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupKey, true
}

// SetGroupKey sets field value
func (o *RiskDetail) SetGroupKey(v string) {
	o.GroupKey = v
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *RiskDetail) GetApplicationId() int64 {
	if o == nil || IsNil(o.ApplicationId) {
		var ret int64
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetApplicationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ApplicationId) {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *RiskDetail) HasApplicationId() bool {
	if o != nil && !IsNil(o.ApplicationId) {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given int64 and assigns it to the ApplicationId field.
func (o *RiskDetail) SetApplicationId(v int64) {
	o.ApplicationId = &v
}

// GetStatus returns the Status field value
func (o *RiskDetail) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RiskDetail) SetStatus(v string) {
	o.Status = v
}

// GetCriticality returns the Criticality field value
func (o *RiskDetail) GetCriticality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Criticality
}

// GetCriticalityOk returns a tuple with the Criticality field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetCriticalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Criticality, true
}

// SetCriticality sets field value
func (o *RiskDetail) SetCriticality(v string) {
	o.Criticality = v
}

// GetEntity returns the Entity field value
func (o *RiskDetail) GetEntity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Entity
}

// GetEntityOk returns a tuple with the Entity field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetEntityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entity, true
}

// SetEntity sets field value
func (o *RiskDetail) SetEntity(v string) {
	o.Entity = v
}

// GetActivity returns the Activity field value
func (o *RiskDetail) GetActivity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Activity
}

// GetActivityOk returns a tuple with the Activity field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetActivityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Activity, true
}

// SetActivity sets field value
func (o *RiskDetail) SetActivity(v string) {
	o.Activity = v
}

// GetTimeFrame returns the TimeFrame field value
func (o *RiskDetail) GetTimeFrame() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeFrame
}

// GetTimeFrameOk returns a tuple with the TimeFrame field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetTimeFrameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeFrame, true
}

// SetTimeFrame sets field value
func (o *RiskDetail) SetTimeFrame(v string) {
	o.TimeFrame = v
}

// GetReportedDate returns the ReportedDate field value
func (o *RiskDetail) GetReportedDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReportedDate
}

// GetReportedDateOk returns a tuple with the ReportedDate field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetReportedDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportedDate, true
}

// SetReportedDate sets field value
func (o *RiskDetail) SetReportedDate(v time.Time) {
	o.ReportedDate = v
}

// GetAffectedEntityCount returns the AffectedEntityCount field value
func (o *RiskDetail) GetAffectedEntityCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AffectedEntityCount
}

// GetAffectedEntityCountOk returns a tuple with the AffectedEntityCount field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetAffectedEntityCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AffectedEntityCount, true
}

// SetAffectedEntityCount sets field value
func (o *RiskDetail) SetAffectedEntityCount(v int64) {
	o.AffectedEntityCount = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RiskDetail) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RiskDetail) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RiskDetail) SetDescription(v string) {
	o.Description = &v
}

// GetModified returns the Modified field value
func (o *RiskDetail) GetModified() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetModifiedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modified, true
}

// SetModified sets field value
func (o *RiskDetail) SetModified(v time.Time) {
	o.Modified = v
}

// GetAffectedEntities returns the AffectedEntities field value
func (o *RiskDetail) GetAffectedEntities() []RiskAffectedEntityItem {
	if o == nil {
		var ret []RiskAffectedEntityItem
		return ret
	}

	return o.AffectedEntities
}

// GetAffectedEntitiesOk returns a tuple with the AffectedEntities field value
// and a boolean to check if the value has been set.
func (o *RiskDetail) GetAffectedEntitiesOk() ([]RiskAffectedEntityItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.AffectedEntities, true
}

// SetAffectedEntities sets field value
func (o *RiskDetail) SetAffectedEntities(v []RiskAffectedEntityItem) {
	o.AffectedEntities = v
}

func (o RiskDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created"] = o.Created
	toSerialize["notificationId"] = o.NotificationId
	toSerialize["runDate"] = o.RunDate
	toSerialize["groupKey"] = o.GroupKey
	if !IsNil(o.ApplicationId) {
		toSerialize["applicationId"] = o.ApplicationId
	}
	toSerialize["status"] = o.Status
	toSerialize["criticality"] = o.Criticality
	toSerialize["entity"] = o.Entity
	toSerialize["activity"] = o.Activity
	toSerialize["timeFrame"] = o.TimeFrame
	toSerialize["reportedDate"] = o.ReportedDate
	toSerialize["affectedEntityCount"] = o.AffectedEntityCount
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["modified"] = o.Modified
	toSerialize["affectedEntities"] = o.AffectedEntities

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created",
		"notificationId",
		"runDate",
		"groupKey",
		"status",
		"criticality",
		"entity",
		"activity",
		"timeFrame",
		"reportedDate",
		"affectedEntityCount",
		"modified",
		"affectedEntities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskDetail := _RiskDetail{}

	err = json.Unmarshal(data, &varRiskDetail)

	if err != nil {
		return err
	}

	*o = RiskDetail(varRiskDetail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created")
		delete(additionalProperties, "notificationId")
		delete(additionalProperties, "runDate")
		delete(additionalProperties, "groupKey")
		delete(additionalProperties, "applicationId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "criticality")
		delete(additionalProperties, "entity")
		delete(additionalProperties, "activity")
		delete(additionalProperties, "timeFrame")
		delete(additionalProperties, "reportedDate")
		delete(additionalProperties, "affectedEntityCount")
		delete(additionalProperties, "description")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "affectedEntities")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskDetail struct {
	value *RiskDetail
	isSet bool
}

func (v NullableRiskDetail) Get() *RiskDetail {
	return v.value
}

func (v *NullableRiskDetail) Set(val *RiskDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableRiskDetail(val *RiskDetail) *NullableRiskDetail {
	return &NullableRiskDetail{value: val, isSet: true}
}

func (v NullableRiskDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
