/*
Talon.One API

Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.

API version:
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package talon

import (
	"encoding/json"
	"fmt"
)

// checks if the SortSelectorStepField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SortSelectorStepField{}

// SortSelectorStepField struct for SortSelectorStepField
type SortSelectorStepField struct {
	// The attribute path the items are sorted by.
	Expression string `json:"expression"`
	// The sort direction for this field.
	Direction            string `json:"direction"`
	AdditionalProperties map[string]interface{}
}

type _SortSelectorStepField SortSelectorStepField

// NewSortSelectorStepField instantiates a new SortSelectorStepField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func BuildSortSelectorStepField(expression string, direction string) *SortSelectorStepField {
	this := SortSelectorStepField{}
	this.Expression = expression
	this.Direction = direction
	return &this
}

// NewSortSelectorStepFieldWithDefaults instantiates a new SortSelectorStepField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSortSelectorStepFieldWithDefaults() *SortSelectorStepField {
	this := SortSelectorStepField{}
	return &this
}

// GetExpression returns the Expression field value
func (o *SortSelectorStepField) GetExpression() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value
// and a boolean to check if the value has been set.
func (o *SortSelectorStepField) GetExpressionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expression, true
}

// SetExpression sets field value
func (o *SortSelectorStepField) SetExpression(v string) {
	o.Expression = v
}

// GetDirection returns the Direction field value
func (o *SortSelectorStepField) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *SortSelectorStepField) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *SortSelectorStepField) SetDirection(v string) {
	o.Direction = v
}

func (o SortSelectorStepField) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SortSelectorStepField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expression"] = o.Expression
	toSerialize["direction"] = o.Direction

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SortSelectorStepField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expression",
		"direction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSortSelectorStepField := _SortSelectorStepField{}

	err = json.Unmarshal(data, &varSortSelectorStepField)

	if err != nil {
		return err
	}

	*o = SortSelectorStepField(varSortSelectorStepField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "expression")
		delete(additionalProperties, "direction")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSortSelectorStepField struct {
	value *SortSelectorStepField
	isSet bool
}

func (v NullableSortSelectorStepField) Get() *SortSelectorStepField {
	return v.value
}

func (v *NullableSortSelectorStepField) Set(val *SortSelectorStepField) {
	v.value = val
	v.isSet = true
}

func (v NullableSortSelectorStepField) IsSet() bool {
	return v.isSet
}

func (v *NullableSortSelectorStepField) Unset() {
	v.value = nil
	v.isSet = false
}

func BuildNullableSortSelectorStepField(val *SortSelectorStepField) *NullableSortSelectorStepField {
	return &NullableSortSelectorStepField{value: val, isSet: true}
}

func (v NullableSortSelectorStepField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSortSelectorStepField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
